# Load Packages

In [1]:
import pandas as pd
import numpy as np
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
import os
from pathlib import Path

current_path = os.getcwd()
print(current_path)
new_path = '/Users/aminudidnaiman/spotify_analytics'
os.chdir(new_path)

print("Now in:",os.getcwd())
from utils.data_processing import (
    extract_top_artist_data,
    extract_top_tracks_data,
    get_albums_info,
    get_tracks_info
)

/Users/aminudidnaiman/spotify_analytics/test
Now in: /Users/aminudidnaiman/spotify_analytics

# Extract Spotify Credentials

In [2]:
env_path = Path("..") / ".env"
load_dotenv(dotenv_path=env_path)
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")
REDIRECT_URI = os.getenv("REDIRECT_URI")

# Extract Spotify Data

## Fetch Top Tracks

In [3]:
# Optional: remove existing cache for fresh login
if os.path.exists(".cache-my-music-app"):
    os.remove(".cache-my-music-app")

# Create the OAuth object
sp_oauth = SpotifyOAuth(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    redirect_uri=REDIRECT_URI,
    scope=["user-top-read", "user-library-read", "playlist-read-private"],
    cache_path=".cache-my-music-app"
)

# Create the Spotify client using the SpotifyOAuth instance directly
sp = spotipy.Spotify(auth_manager=sp_oauth)

# Test API call
try:
    results = sp.current_user_top_tracks(limit=10)
    for idx, item in enumerate(results['items']):
        print(f"{idx+1}. {item['name']} - {item['artists'][0]['name']}")
except spotipy.exceptions.SpotifyException as e:
    print(f"Error: {e}")


print("Fetching your top tracks...")

short_term_track_data = extract_top_tracks_data(sp,'short_term')
medium_term_track_data = extract_top_tracks_data(sp,'medium_term')
long_term_track_data = extract_top_tracks_data(sp,'long_term')

1. CASANOVA POSSE - ALI
2. HER - MINNIE
3. Imaginary Friend - ITZY
4. Air - YEJI
5. I TRUST YOU - エミリア(CV:高橋李依)
6. Shopper - IU
7. Secret - IU
8. Whiplash - aespa
9. NEMONEMO - YENA
10. FREAK - YUQI
Fetching your top tracks...

## Fetch Top Artists

In [4]:
short_term_artists = extract_top_artist_data(sp,'short_term')
medium_term_artists = extract_top_artist_data(sp,'medium_term')
long_term_artists = extract_top_artist_data(sp,'long_term')

short_term_artists

,artist_name,popularity,genres,artist_id,followers,image_url
0,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE,8361617,https://i.scdn.co/image/ab6761610000e5ebf7a109...
1,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN,807593,https://i.scdn.co/image/ab6761610000e5eb1135e1...
2,IU,71,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU,9135223,https://i.scdn.co/image/ab6761610000e5ebbd0642...
3,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu,3064731,https://i.scdn.co/image/ab6761610000e5ebb5d9eb...
4,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX,761745,https://i.scdn.co/image/ab6761610000e5eb1a9a17...
5,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3,8351660,https://i.scdn.co/image/ab6761610000e5eb344806...
6,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m,114620,https://i.scdn.co/image/ab6761610000e5eb5bf460...
7,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0,21665446,https://i.scdn.co/image/ab6761610000e5ebca6c14...
8,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6,833634,https://i.scdn.co/image/ab6761610000e5eb569026...
9,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl,3607044,https://i.scdn.co/image/ab6761610000e5ebb75519...
10,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx,10489801,https://i.scdn.co/image/ab6761610000e5eb7fd163...
11,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ,5451531,https://i.scdn.co/image/ab6761610000e5eb538dad...
12,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p,6909574,https://i.scdn.co/image/ab6761610000e5eb593f35...
13,THE SIXTH LIE,40,"anime, j-rock, j-pop",2sCc8pMRgv99AweDSrFFZt,30484,https://i.scdn.co/image/ab6761610000e5ebca92c4...
14,KISS OF LIFE,73,k-pop,4TEK9tIkcoxib4GxT3O4ky,2125187,https://i.scdn.co/image/ab6761610000e5eb33a8cc...
15,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS,4271004,https://i.scdn.co/image/ab6761610000e5ebb419d6...
16,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF,740603,https://i.scdn.co/image/ab6761610000e5eb369406...
17,SEULGI,62,k-pop,2QM5S4yO6xHgnNvF0nbZZq,1212544,https://i.scdn.co/image/ab6761610000e5eb9879ac...
18,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs,5685017,https://i.scdn.co/image/ab6761610000e5eb9e33dd...
19,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo,994169,https://i.scdn.co/image/ab6761610000e5eb8bb041...
20,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik,3032922,https://i.scdn.co/image/ab6761610000e5ebe62cff...
21,JIHYO,55,k-pop,7F1iAHRYxR3MY7yAEuFqgL,979380,https://i.scdn.co/image/ab6761610000e5eb92d8ef...
22,CSR,35,"bubblegum pop, k-pop",06MX3Ecb8PHyNFmq8irTWC,90161,https://i.scdn.co/image/ab6761610000e5eba6b8bd...
23,SOOJIN,43,k-pop,0kB3Vlf3xDNZQz6NjAPJV8,431729,https://i.scdn.co/image/ab6761610000e5ebc013b5...
24,ARTMS,52,k-pop,213zHiFZwtDVEqyxeCbk07,171535,https://i.scdn.co/image/ab6761610000e5eb0576f9...
25,Cherry Bullet,41,"k-pop, bubblegum pop",3IJCdgkBZbieocLZ4e94GZ,444843,https://i.scdn.co/image/ab6761610000e5eb741522...
26,TEN,69,k-pop,3Q5Qep7ytrjVleNnMnntgQ,843666,https://i.scdn.co/image/ab6761610000e5eb8f8c7f...
27,G-DRAGON,76,"k-pop, k-rap",30b9WulBM8sFuBo17nNq9c,3461202,https://i.scdn.co/image/ab6761610000e5eb783a6a...
28,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ,18137033,https://i.scdn.co/image/ab6761610000e5eb57138b...
29,DAY6,69,"k-rock, k-pop",5TnQc2N1iKlFjYD7CPGvFc,3670925,https://i.scdn.co/image/ab6761610000e5eb10e83b...
30,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V,119923718,https://i.scdn.co/image/ab6761610000e5eb399444...
31,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU,57698296,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...
32,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX,810891,https://i.scdn.co/image/ab6761610000e5eb9cc45f...

## Extract additional information on Top Tracks

In [5]:
short_term_track_id  = short_term_track_data['track_id'].unique().tolist()
medium_term_track_id  = medium_term_track_data['track_id'].unique().tolist()
long_term_track_id  = long_term_track_data['track_id'].unique().tolist()

short_term_tracks = get_tracks_info(sp,short_term_track_id)
medium_term_tracks = get_tracks_info(sp,medium_term_track_id)
long_term_tracks = get_tracks_info(sp,long_term_track_id)

## Extract additional information on Albums

In [6]:
short_term_album_id  = short_term_track_data['album_id'].unique().tolist()
medium_term_album_id  = medium_term_track_data['album_id'].unique().tolist()
long_term_album_id  = long_term_track_data['album_id'].unique().tolist()

short_term_albums = get_albums_info(sp,short_term_album_id)
medium_term_albums = get_albums_info(sp,medium_term_album_id)
long_term_albums = get_albums_info(sp,long_term_album_id)

# Data Analysis

In [8]:
top_tracks_df = long_term_track_data
track_info_df = long_term_tracks
album_info_df = long_term_albums
artist_info_df = long_term_artists

In [29]:
duplicated_suffix = '_dup'
track_merged_df = top_tracks_df.merge(track_info_df,how = 'inner',on = ['track_id'],suffixes=('',duplicated_suffix))
track_merged_df = track_merged_df.loc[:,~track_merged_df.columns.str.endswith(duplicated_suffix)]
track_album_merged_df = track_merged_df.merge(album_info_df,how = 'left',on = ['album_id'],suffixes=('',duplicated_suffix))
track_album_merged_df = track_album_merged_df.loc[:,~track_album_merged_df.columns.str.endswith(duplicated_suffix)]
track_album_merged_df

,track_name,artist_name,album_name,album_id,release_date,popularity,duration_ms,explicit,track_id,duration_min,...,label,album_type,external_url,album_uri,release_date_precision,images,genres,artists,track_ids,available_markets
0,Nobody - from Kaiju No. 8,OneRepublic,Nobody (from Kaiju No. 8),3YmKf1haPAblZIrIPpuRTf,2024-04-12,70,153626,False,47N81NMkB488fuOwOC3Oip,2.560433,...,Mosley Music/Interscope Records,single,https://open.spotify.com/album/3YmKf1haPAblZIr...,spotify:album:3YmKf1haPAblZIrIPpuRTf,day,[https://i.scdn.co/image/ab67616d0000b2732b386...,,OneRepublic,[47N81NMkB488fuOwOC3Oip],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
1,I GOT YOU,TWICE,I GOT YOU,6RZHj6L3NqrvcKeiBHQbjL,2024-02-02,59,173240,False,35dhwUoJNlxrPyEIJkfDnx,2.887333,...,Republic Records - TWICE,single,https://open.spotify.com/album/6RZHj6L3NqrvcKe...,spotify:album:6RZHj6L3NqrvcKeiBHQbjL,day,[https://i.scdn.co/image/ab67616d0000b273d6a44...,,TWICE,"[35dhwUoJNlxrPyEIJkfDnx, 2iMtwujjXUGjpUraeSrvIm]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
2,FREAK,YUQI,YUQ1,7LYc8ngbhwha4aGJ5kVauc,2024-04-23,57,171080,False,6ERs9uORCo1MfV0m9ixCuv,2.851333,...,Cube Entertainment,album,https://open.spotify.com/album/7LYc8ngbhwha4aG...,spotify:album:7LYc8ngbhwha4aGJ5kVauc,day,[https://i.scdn.co/image/ab67616d0000b2736f99c...,,YUQI,"[6JgEbE6tFhcKILTL4Z82VA, 6kRV7e933KQw0BoXBkSoA...",[]
3,DIVE,TWICE,DIVE,0riep5s1F9ynpobjOSzbcr,2024-07-10,58,181860,False,5vK3WrTOp6rEoASx1jAsp1,3.031000,...,WM Japan,single,https://open.spotify.com/album/0riep5s1F9ynpob...,spotify:album:0riep5s1F9ynpobjOSzbcr,day,[https://i.scdn.co/image/ab67616d0000b27303661...,,TWICE,[5vK3WrTOp6rEoASx1jAsp1],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
4,Fate,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,62,161546,False,2vNPGH1x5ZwxTjlvzLCyc2,2.692433,...,Cube Entertainment,album,https://open.spotify.com/album/0mC9MXPddkzggVs...,spotify:album:0mC9MXPddkzggVsOXh5gd3,day,[https://i.scdn.co/image/ab67616d0000b27342281...,,(G)I-DLE,"[0uLcuydgTo4ErT6aQQayuw, 3GwmjxMoBSFbcYVvZooKO...",[]
5,Doughnut,TWICE,Celebrate,1nqz3cEjuvCMo8RHLBI9kM,2022-07-27,53,263680,False,65rmgd5uMb4Rgqb5dSiU0p,4.394667,...,WM Japan,album,https://open.spotify.com/album/1nqz3cEjuvCMo8R...,spotify:album:1nqz3cEjuvCMo8RHLBI9kM,day,[https://i.scdn.co/image/ab67616d0000b27396f40...,,TWICE,"[4Y0chGCyYIRpdUqHJjndF7, 2Ij1NaPpsFSKJ0M65tSV4...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
6,MORE & MORE,TWICE,MORE & MORE,5KsduuDNWzt65TaHzmtciv,2020-06-01,63,199653,False,3omvXShuRPM3zbDpWYqf5g,3.327550,...,Republic Records - TWICE,album,https://open.spotify.com/album/5KsduuDNWzt65Ta...,spotify:album:5KsduuDNWzt65TaHzmtciv,day,[https://i.scdn.co/image/ab67616d0000b27324869...,,TWICE,"[3omvXShuRPM3zbDpWYqf5g, 128rj96Z6tTEU3h3awSMd...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
7,Red Rover,YUQI,YUQ1,7LYc8ngbhwha4aGJ5kVauc,2024-04-23,47,123320,False,4TQBHR8LcbBUv0LvLmn54H,2.055333,...,Cube Entertainment,album,https://open.spotify.com/album/7LYc8ngbhwha4aG...,spotify:album:7LYc8ngbhwha4aGJ5kVauc,day,[https://i.scdn.co/image/ab67616d0000b2736f99c...,,YUQI,"[6JgEbE6tFhcKILTL4Z82VA, 6kRV7e933KQw0BoXBkSoA...",[]
8,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,20Bf2RVERC5Bc2eo3vyvJv,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550,...,ATLUS GAME MUSIC,album,https://open.spotify.com/album/20Bf2RVERC5Bc2e...,spotify:album:20Bf2RVERC5Bc2eo3vyvJv,day,[https://i.scdn.co/image/ab67616d0000b273e59bd...,,"アトラスサウンドチーム, ATLUS GAME MUSIC","[3Jl2LQmRwbXEF2lO1RTvxn, 1d5r3NM4fqH8po53LkMzB...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
9,YES or YES,TWICE,YES or YES,25VunQEW0x2W6ALND2Mh4g,2018-11-05,68,237680,False,26OVhEqFDQH0Ij77QtmGP9,3.961333,...,Republic Records - TWICE,album,https://open.spotify.com/album/25VunQEW0x2W6AL...,spotify:album:25VunQEW0x2W6ALND2Mh4g,day,[https://i.scdn.co/image/ab67616d0000b273140ba...,,TWICE,"[26OVhEqFDQH0Ij77QtmGP9, 7fEMfYZnjQ28Cpzi7QnkA...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
10,"""good guy""",Against The Current,"""good guy""",6bj1lsHiVqvJyqjv7qtrV4,2023-04-21,48,208052,True,3bfElZNhtvtGvWMVgCBgZK,3.467533,...,Against the Current,single,https://open.spotify.com/album/6bj1lsHiVqvJyqj...,spotify:album:6bj1lsHiVqvJyqjv7qtrV4,day,[https://i.scdn.co/image/ab67616d0000b2737d61e...,,Against The Current,[3bfElZNhtvtGvWMVgCBgZK],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
11,Shopper,IU,The Winning,08CvAj58nVMpq1Nw7T6maj,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333,...,EDAM Entertainment,single,https://open.spotify.com/album/08CvAj58nVMpq1N...,spotify:album:08CvAj58nVMpq1Nw7T6maj,day,[https://i.scdn.co/image/ab67616d0000b2735048e...,,IU,"[1c6kkrWnpy68eYDfBdxNtF, 0UTtK6hregIBOsefavRI2...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
12,POP!,NAYEON,IM NAYEON,0wqjfojWuTcbEvwaizvTMw,2022-06-24,72,168106,False,3lOMJTQTd6J34faYwASc33,2.801767,...,Republic Records – NAYEON (TWICE),album,https://open.spotify.com/album/0wqjfojWuTcbEvw...,spotify:album:0wqjfojWuTcbEvwaizvTMw,day,[https://i.scdn.co/image/ab67616d0000b2735fb4a...,,NAYEON,"[3lOMJTQTd6J34faYwASc33, 4zHvWi4iFAG45lgiN7smL...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
13,青のすみか,Tatsuya Kitani,青のすみか,4QjNVlIw8Rx6jItSZtn2VS,2023-07-07,72,196466,False,12usPU2WnqgCHAW1EK2dfd,3.274433,...,Sony Music Labels Inc.,single,https://open.spotify.com/album/4QjNVlIw8Rx6jIt...,spotify:album:4QjNVlIw8Rx6jItSZtn2VS,day,[https://i.scdn.co/image/ab67616d0000b273e9ce7...,,Tatsuya Kitani,[12usPU2WnqgCHAW1EK2dfd],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
14,CASANOVA POSSE,ALI,CASANOVA POSSE,2xfq9tUp4QOlCGT6j4k0g9,2025-01-10,65,240653,False,26Lip4WX1oWceF9tb8m2qw,4.010883,...,Sony Music Labels Inc.,single,https://open.spotify.com/album/2xfq9tUp4QOlCGT...,spotify:album:2xfq9tUp4QOlCGT6j4k0g9,day,[https://i.scdn.co/image/ab67616d0000b2733fc87...,,ALI,[26Lip4WX1oWceF9tb8m2qw],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
15,Talk that Talk,TWICE,BETWEEN 1&2,3NZ94nQbqimcu2i71qhc4f,2022-08-26,69,177466,False,0RDqNCRBGrSegk16Avfzuq,2.957767,...,Republic Records - TWICE,album,https://open.spotify.com/album/3NZ94nQbqimcu2i...,spotify:album:3NZ94nQbqimcu2i71qhc4f,day,[https://i.scdn.co/image/ab67616d0000b273c3040...,,TWICE,"[0RDqNCRBGrSegk16Avfzuq, 3sOEVB8DirQtZc0qhw8lJ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
16,Perfect World,TWICE,Perfect World,17rk8h2IU4wwSFXw9j2uR6,2021-07-28,58,182680,False,0iuZMy88H6vxDA2oaJNhJg,3.044667,...,WM Japan,album,https://open.spotify.com/album/17rk8h2IU4wwSFX...,spotify:album:17rk8h2IU4wwSFXw9j2uR6,day,[https://i.scdn.co/image/ab67616d0000b273579e9...,,TWICE,"[0iuZMy88H6vxDA2oaJNhJg, 1Wrn6btrungVsBjyViLnu...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
17,晴る,ヨルシカ,晴る,4O53dhmIctih3p2suAAgga,2024-01-05,74,270705,False,5eY7692tmgHB9dbmq6wa2M,4.511750,...,Universal Music LLC,single,https://open.spotify.com/album/4O53dhmIctih3p2...,spotify:album:4O53dhmIctih3p2suAAgga,day,[https://i.scdn.co/image/ab67616d0000b2735e763...,,ヨルシカ,[5eY7692tmgHB9dbmq6wa2M],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
18,Super Lady,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,64,152186,False,5qI5EUqfDJpQ7w6sMECK7U,2.536433,...,Cube Entertainment,album,https://open.spotify.com/album/0mC9MXPddkzggVs...,spotify:album:0mC9MXPddkzggVsOXh5gd3,day,[https://i.scdn.co/image/ab67616d0000b27342281...,,(G)I-DLE,"[0uLcuydgTo4ErT6aQQayuw, 3GwmjxMoBSFbcYVvZooKO...",[]
19,Long Live (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),5AEDGbliTTfjOB8TSm1sxt,2023-07-07,73,317960,False,4hqJ4bSlYJOXb6Z4SRmzxs,5.299333,...,Taylor Swift,album,https://open.spotify.com/album/5AEDGbliTTfjOB8...,spotify:album:5AEDGbliTTfjOB8TSm1sxt,day,[https://i.scdn.co/image/ab67616d0000b2730b04d...,,Taylor Swift,"[7G0gBu6nLdhFDPRLc0HdDG, 3MytWN8L7shNYzGl4tAKR...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
20,Klaxon,(G)I-DLE,I SWAY,5WzUVTkKAvOayPui3DnsDz,2024-07-08,63,175106,False,294hRgOqnGW2BemqP8D35X,2.918433,...,Cube Entertainment,single,https://open.spotify.com/album/5WzUVTkKAvOayPu...,spotify:album:5WzUVTkKAvOayPui3DnsDz,day,[https://i.scdn.co/image/ab67616d0000b27366f7b...,,(G)I-DLE,"[0d2ykpjGQwxSw7huc3l7vw, 2QcT3mwErl92KduUArSxZ...",[]
21,No Celestial,LE SSERAFIM,ANTIFRAGILE,3u0ggfmK0vjuHMNdUbtaa9,2022-10-17,60,166491,False,21ApmVGIzIAIDSBdHu6SVt,2.774850,...,SOURCE MUSIC,single,https://open.spotify.com/album/3u0ggfmK0vjuHMN...,spotify:album:3u0ggfmK0vjuHMNdUbtaa9,day,[https://i.scdn.co/image/ab67616d0000b273a9919...,,LE SSERAFIM,"[0JosgxxZKZ87QbW5TISJDE, 4fsQ0K37TOXa3hEQfjEic...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
22,ONE SPARK,TWICE,With YOU-th,575TQDOQqc0MAheeEeKWUR,2024-02-23,67,183559,False,7cIn67LEvk16v6komC8znS,3.059317,...,Republic Records - TWICE,single,https://open.spotify.com/album/575TQDOQqc0MAhe...,spotify:album:575TQDOQqc0MAheeEeKWUR,day,[https://i.scdn.co/image/ab67616d0000b273bd8c7...,,TWICE,"[0mgveJEIGjcN51w4JIQtI6, 7cIn67LEvk16v6komC8zn...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
23,Live My Life,aespa,Armageddon - The 1st Album,3gHhPm8z8tid1kvpniUKuK,2024-05-27,63,159133,False,1x1oCGsFUDViOvcISuoKW0,2.652217,...,SM Entertainment,album,https://open.spotify.com/album/3gHhPm8z8tid1kv...,spotify:album:3gHhPm8z8tid1kvpniUKuK,day,[https://i.scdn.co/image/ab67616d0000b2730fc59...,,aespa,"[2VdSktBqFfkW7y6q5Ik4Z4, 5eWcGfUCrVFMoYskyfkEP...","[AG, BB, BG, BS, DM, DO, GD, HK, HT, ID, IL, J..."
24,Imaginary Friend,ITZY,GOLD,4CRfobFgSG0GOzplgTI79s,2024-10-15,66,202429,False,06BeeZaS4YArThfTMu80QS,3.373817,...,Republic Records - ITZY,album,https://open.spotify.com/album/4CRfobFgSG0GOzp...,spotify:album:4CRfobFgSG0GOzplgTI79s,day,[https://i.scdn.co/image/ab67616d0000b273dd734...,,ITZY,"[1dqN2j0jL4qB72CNgCdQ09, 06BeeZaS4YArThfTMu80Q...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
25,Air,YEJI,AIR,6sJnzoRI9pXUo0gZxIviUS,2025-03-10,75,194800,False,6HSns0qPQQfgekCrBF0Dkf,3.246667,...,Republic Records – YEJI (ITZY),single,https://open.spotify.com/album/6sJnzoRI9pXUo0g...,spotify:album:6sJnzoRI9pXUo0gZxIviUS,day,[https://i.scdn.co/image/ab67616d0000b27338d7a...,,YEJI,"[6HSns0qPQQfgekCrBF0Dkf, 5xOUBAvwWYyuPmej4iRcV...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
26,HER,MINNIE,HER,3sbZ4PoHTIZL8bLSLwt84h,2025-01-21,68,159797,False,2MbPhDgeXVipowltFneRH2,2.663283,...,Cube Entertainment,single,https://open.spotify.com/album/3sbZ4PoHTIZL8bL...,spotify:album:3sbZ4PoHTIZL8bLSLwt84h,day,[https://i.scdn.co/image/ab67616d0000b2735b264...,,MINNIE,"[4wqyCBpp9zwtpSehLRciXT, 6XtNw289lraKPESASgB5H...",[]
27,境界線,amazarashi,七号線ロストボーイズ,0pqrWNxpcWBvR9A5A9JHHl,2022-04-13,49,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550,...,Sony Music Labels Inc.,album,https://open.spotify.com/album/0pqrWNxpcWBvR9A...,spotify:album:0pqrWNxpcWBvR9A5A9JHHl,day,[https://i.scdn.co/image/ab67616d0000b2730262e...,,amazarashi,"[4g5yln7dtUaWz2bhD7s3Lp, 6C7rH9snYqVLTeFkmXv0g...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
28,I TRUST YOU,エミリア(CV:高橋李依),"SONG FROM TV SERIES ""RE:ZERO -STARTING LIFE IN...",530vXGXkG5czn3hHdMPSMD,2024-11-14,34,255396,False,7Ccvd3UVSfORSNyeOO069h,4.256600,...,KADOKAWA,compilation,https://open.spotify.com/album/530vXGXkG5czn3h...,spotify:album:530vXGXkG5czn3hHdMPSMD,day,[https://i.scdn.co/image/ab67616d0000b2730dc35...,,Various Artists,"[25j7bzRhgwL29jfgReVFdy, 1aXQG0fOcIHIjPIpDLIl4...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
29,Alcohol-Free,TWICE,Taste of Love,00vb6sViDbJLmLLchfbRh4,2021-06-11,66,210573,False,0BTaaKT4RMbs5M73tOHX5Y,3.509550,...,Republic Records - TWICE,single,https://open.spotify.com/album/00vb6sViDbJLmLL...,spotify:album:00vb6sViDbJLmLLchfbRh4,day,[https://i.scdn.co/image/ab67616d0000b273feede...,,TWICE,"[0BTaaKT4RMbs5M73tOHX5Y, 3YdqewCLgGsFhruA3EhIL...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
30,Beyond the Horizon,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,47,212826,False,27f7ZEBoJIJ3HzOpzqmDqO,3.547100,...,WM Japan,album,https://open.spotify.com/album/7tgTOUXm74GKA12...,spotify:album:7tgTOUXm74GKA12wsQIUPu,day,[https://i.scdn.co/image/ab67616d0000b273c1486...,,TWICE,"[27f7ZEBoJIJ3HzOpzqmDqO, 3JstVDAZKy4O8SZ5yoXdQ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
31,Ocean Deep,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,47,220106,False,6jya1u1sEhObLCDFGyWuAW,3.668433,...,WM Japan,album,https://open.spotify.com/album/7tgTOUXm74GKA12...,spotify:album:7tgTOUXm74GKA12wsQIUPu,day,[https://i.scdn.co/image/ab67616d0000b273c1486...,,TWICE,"[27f7ZEBoJIJ3HzOpzqmDqO, 3JstVDAZKy4O8SZ5yoXdQ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
32,Sunshine,OneRepublic,Sunshine,2YSlIS6gM38w7ZJNj8F3s6,2021-11-10,74,163854,False,5r43qanLhUCdBj8HN3fa6B,2.730900,...,Mosley Music/Interscope Records,single,https://open.spotify.com/album/2YSlIS6gM38w7ZJ...,spotify:album:2YSlIS6gM38w7ZJNj8F3s6,day,[https://i.scdn.co/image/ab67616d0000b2733b248...,,OneRepublic,[5r43qanLhUCdBj8HN3fa6B],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
33,LOVE FOOLISH,TWICE,Feel Special,3NQBPabmRm3LzVcmtkTLfo,2019-09-23,53,191226,False,1MdEg2lk4EakgWnCvFUGEZ,3.187100,...,Republic Records - TWICE,album,https://open.spotify.com/album/3NQBPabmRm3LzVc...,spotify:album:3NQBPabmRm3LzVcmtkTLfo,day,[https://i.scdn.co/image/ab67616d0000b273a6b5e...,,TWICE,"[3Hz3tTQwOdM6XkA0ALB2G9, 6uy9lTlZ3xaMYQPk6eaJa...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
34,DIVE,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,57,181860,False,3JstVDAZKy4O8SZ5yoXdQr,3.031000,...,WM Japan,album,https://open.spotify.com/album/7tgTOUXm74GKA12...,spotify:album:7tgTOUXm74GKA12wsQIUPu,day,[https://i.scdn.co/image/ab67616d0000b273c1486...,,TWICE,"[27f7ZEBoJIJ3HzOpzqmDqO, 3JstVDAZKy4O8SZ5yoXdQ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
35,Feel Special,TWICE,Feel Special,3NQBPabmRm3LzVcmtkTLfo,2019-09-23,71,206866,False,3Hz3tTQwOdM6XkA0ALB2G9,3.447767,...,Republic Records - TWICE,album,https://open.spotify.com/album/3NQBPabmRm3LzVc...,spotify:album:3NQBPabmRm3LzVcmtkTLfo,day,[https://i.scdn.co/image/ab67616d0000b273a6b5e...,,TWICE,"[3Hz3tTQwOdM6XkA0ALB2G9, 6uy9lTlZ3xaMYQPk6eaJa...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
36,Hare Hare,TWICE,Hare Hare,7hF6oiU4zaIQIGjLhje1eG,2023-05-31,46,203546,False,3QcJghvqRS17RoPPP0C2sp,3.392433,...,WM Japan,single,https://open.spotify.com/album/7hF6oiU4zaIQIGj...,spotify:album:7hF6oiU4zaIQIGjLhje1eG,day,[https://i.scdn.co/image/ab67616d0000b27386220...,,TWICE,"[3QcJghvqRS17RoPPP0C2sp, 2MbxU95EQZbdRo0biiC6M...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
37,MOONLIGHT SUNRISE,TWICE,READY TO BE,7hzP5i7StxYG4StECA0rrJ,2023-03-10,61,180320,False,5IN9W6eUfk3014My9awagX,3.005333,...,Republic Records - TWICE,album,https://open.spotify.com/album/7hzP5i7StxYG4St...,spotify:album:7hzP5i7StxYG4StECA0rrJ,day,[https://i.scdn.co/image/ab67616d0000b27359f57...,,TWICE,"[4OtVQ2ZxS7yigIjGz5yKg1, 5IN9W6eUfk3014My9awag...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
38,Baby Blue Love,TWICE,Taste of Love,00vb6sViDbJLmLLchfbRh4,2021-06-11,50,166666,False,7Jzo3IObpANz6giPTUrihB,2.777767,...,Republic Records - TWICE,single,https://open.spotify.com/album/00vb6sViDbJLmLL...,spotify:album:00vb6sViDbJLmLLchfbRh4,day,[https://i.scdn.co/image/ab67616d0000b273feede...,,TWICE,"[0BTaaKT4RMbs5M73tOHX5Y, 3YdqewCLgGsFhruA3EhIL...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
39,Wife,(G)I-DLE,Wife,0C8qSTYZDkVcfnY6tIHIzK,2024-01-21,55,121226,False,6hWU8LrnjLyYHShDyNWFZj,2.020433,...,Cube Entertainment,single,https://open.spotify.com/album/0C8qSTYZDkVcfnY...,spotify:album:0C8qSTYZDkVcfnY6tIHIzK,day,[https://i.scdn.co/image/ab67616d0000b27320f99...,,(G)I-DLE,[326PEjfqveu646UhjHrth9],[]
40,Secret,IU,Last Fantasy,149BHv6qAyMgJ483vPi77C,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867,...,Kakao Entertainment,album,https://open.spotify.com/album/149BHv6qAyMgJ48...,spotify:album:149BHv6qAyMgJ483vPi77C,day,[https://i.scdn.co/image/ab67616d0000b273bf5f4...,,IU,"[38HJ2NhRdr68S1UAi9r3vc, 79PkC8ii2W7Grvvkqazgf...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
41,Likey,TWICE,Twicetagram,3hJXmK5gWN9P6jtZL0Lr2y,2017-10-30,67,207813,False,0IEVKWduAaMcZepZQVr80T,3.463550,...,Republic Records - TWICE,album,https://open.spotify.com/album/3hJXmK5gWN9P6jt...,spotify:album:3hJXmK5gWN9P6jtZL0Lr2y,day,[https://i.scdn.co/image/ab67616d0000b2736034e...,,TWICE,"[0IEVKWduAaMcZepZQVr80T, 1LQtxz9fIrZskoqDSbhKd...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
42,Mine (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),5AEDGbliTTfjOB8TSm1sxt,2023-07-07,74,231706,False,7G0gBu6nLdhFDPRLc0HdDG,3.861767,...,Taylor Swift,album,https://open.spotify.com/album/5AEDGbliTTfjOB8...,spotify:album:5AEDGbliTTfjOB8TSm1sxt,day,[https://i.scdn.co/image/ab67616d0000b2730b04d...,,Taylor Swift,"[7G0gBu6nLdhFDPRLc0HdDG, 3MytWN8L7shNYzGl4tAKR...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
43,Whiplash,aespa,Whiplash - The 5th Mini Album,3OaW4df1SA62k0arNpn6bK,2024-10-21,78,183226,False,6uPnrBgweGOcwjFL4ItAvV,3.053767,...,SM Entertainment,single,https://open.spotify.com/album/3OaW4df1SA62k0a...,spotify:album:3OaW4df1SA62k0arNpn6bK,day,[https://i.scdn.co/image/ab67616d0000b273e467a...,,aespa,"[6uPnrBgweGOcwjFL4ItAvV, 7dYEUpcXJLDcI22m0dgmn...","[AG, BB, BG, BS, DM, DO, GD, HK, HT, ID, IL, J..."
44,I GOT YOU,TWICE,With YOU-th,575TQDOQqc0MAheeEeKWUR,2024-02-23,54,173240,False,0mgveJEIGjcN51w4JIQtI6,2.887333,...,Republic Records - TWICE,single,https://open.spotify.com/album/575TQDOQqc0MAhe...,spotify:album:575TQDOQqc0MAheeEeKWUR,day,[https://i.scdn.co/image/ab67616d0000b273bd8c7...,,TWICE,"[0mgveJEIGjcN51w4JIQtI6, 7cIn67LEvk16v6komC8zn...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
45,ABCD,NAYEON,NA,5zQI9dFbS9TrhvC9clgjz7,2024-06-14,72,162840,False,0V2passWyAXnON67kfAj7y,2.714000,...,Republic Records – NAYEON (TWICE),album,https://open.spotify.com/album/5zQI9dFbS9TrhvC...,spotify:album:5zQI9dFbS9TrhvC9clgjz7,day,[https://i.scdn.co/image/ab67616d0000b27373f05...,,NAYEON,"[0V2passWyAXnON67kfAj7y, 07W0lOkOUhVhdJQ9wVepW...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
46,Wife,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,60,121226,False,1j8jqwFpFQ8YqsIJAiYFLZ,2.020433,...,Cube Entertainment,album,https://open.spotify.com/album/0mC9MXPddkzggVs...,spotify:album:0mC9MXPddkzggVsOXh5gd3,day,[https://i.scdn.co/image/ab67616d0000b27342281...,,(G)I-DLE,"[0uLcuydgTo4ErT6aQQayuw, 3GwmjxMoBSFbcYVvZooKO...",[]
47,Like A Dream,MINNIE,"Lovely Runner, Pt. 3 (Original Soundtrack)",5fqhw5RIuAu14Na1ld2FFC,2024-04-16,64,249217,False,4Kw1ykVLHoFQxOPSVd8R2E,4.153617,...,"Genie Music Corporation, Stone Music Entertain...",single,https://open.spotify.com/album/5fqhw5RIuAu14Na...,spotify:album:5fqhw5RIuAu14Na1ld2FFC,day,[https://i.scdn.co/image/ab67616d0000b273444d0...,,MINNIE,"[4Kw1ykVLHoFQxOPSVd8R2E, 770rnCCz5pJesVsQe25b9O]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
48,Killin’ Me Good,JIHYO,ZONE,1GIkapvyAw5lwdNw66hI44,2023-08-18,64,185920,False,4Cyf87ul1le0xTWRFBoYd7,3.098667,...,Republic Records – JIHYO (TWICE),album,https://open.spotify.com/album/1GIkapvyAw5lwdN...,spotify:album:1GIkapvyAw5lwdNw66hI44,day,[https://i.scdn.co/image/ab67616d0000b27392b61...,,JIHYO,"[4Cyf87ul1le0xTWRFBoYd7, 28mFFxAwJ9cx9j7z9yu64...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
49,NEMONEMO,YENA,NEMONEMO,6FLiJ4318RtpA5lYWJt2cL,2024-09-30,67,178026,False,4UwsXGVppRRJpKBHy0mtyK,2.967100,...,"Genie Music Corporation, Stone Music Entertain...",single,https://open.spotify.com/album/6FLiJ4318RtpA5l...,spotify:album:6FLiJ4318RtpA5lYWJt2cL,day,[https://i.scdn.co/image/ab67616d0000b27376bc3...,,YENA,"[4UwsXGVppRRJpKBHy0mtyK, 1T3HuFlijT5Uu4pZI60tg...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."

In [39]:
final_df = track_album_merged_df.merge(artist_info_df,how = 'left',on = ['artist_id'],suffixes=('',duplicated_suffix))
final_df = final_df.loc[:,~final_df.columns.str.endswith(duplicated_suffix)]
final_df

,track_name,artist_name,album_name,album_id,release_date,popularity,duration_ms,explicit,track_id,duration_min,...,external_url,album_uri,release_date_precision,images,genres,artists,track_ids,available_markets,followers,image_url
0,Nobody - from Kaiju No. 8,OneRepublic,Nobody (from Kaiju No. 8),3YmKf1haPAblZIrIPpuRTf,2024-04-12,70,153626,False,47N81NMkB488fuOwOC3Oip,2.560433,...,https://open.spotify.com/album/3YmKf1haPAblZIr...,spotify:album:3YmKf1haPAblZIrIPpuRTf,day,[https://i.scdn.co/image/ab67616d0000b2732b386...,,OneRepublic,[47N81NMkB488fuOwOC3Oip],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",18137033.0,https://i.scdn.co/image/ab6761610000e5eb57138b...
1,I GOT YOU,TWICE,I GOT YOU,6RZHj6L3NqrvcKeiBHQbjL,2024-02-02,59,173240,False,35dhwUoJNlxrPyEIJkfDnx,2.887333,...,https://open.spotify.com/album/6RZHj6L3NqrvcKe...,spotify:album:6RZHj6L3NqrvcKeiBHQbjL,day,[https://i.scdn.co/image/ab67616d0000b273d6a44...,,TWICE,"[35dhwUoJNlxrPyEIJkfDnx, 2iMtwujjXUGjpUraeSrvIm]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
2,FREAK,YUQI,YUQ1,7LYc8ngbhwha4aGJ5kVauc,2024-04-23,57,171080,False,6ERs9uORCo1MfV0m9ixCuv,2.851333,...,https://open.spotify.com/album/7LYc8ngbhwha4aG...,spotify:album:7LYc8ngbhwha4aGJ5kVauc,day,[https://i.scdn.co/image/ab67616d0000b2736f99c...,,YUQI,"[6JgEbE6tFhcKILTL4Z82VA, 6kRV7e933KQw0BoXBkSoA...",[],833634.0,https://i.scdn.co/image/ab6761610000e5eb569026...
3,DIVE,TWICE,DIVE,0riep5s1F9ynpobjOSzbcr,2024-07-10,58,181860,False,5vK3WrTOp6rEoASx1jAsp1,3.031000,...,https://open.spotify.com/album/0riep5s1F9ynpob...,spotify:album:0riep5s1F9ynpobjOSzbcr,day,[https://i.scdn.co/image/ab67616d0000b27303661...,,TWICE,[5vK3WrTOp6rEoASx1jAsp1],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
4,Fate,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,62,161546,False,2vNPGH1x5ZwxTjlvzLCyc2,2.692433,...,https://open.spotify.com/album/0mC9MXPddkzggVs...,spotify:album:0mC9MXPddkzggVsOXh5gd3,day,[https://i.scdn.co/image/ab67616d0000b27342281...,,(G)I-DLE,"[0uLcuydgTo4ErT6aQQayuw, 3GwmjxMoBSFbcYVvZooKO...",[],10489801.0,https://i.scdn.co/image/ab6761610000e5eb7fd163...
5,Doughnut,TWICE,Celebrate,1nqz3cEjuvCMo8RHLBI9kM,2022-07-27,53,263680,False,65rmgd5uMb4Rgqb5dSiU0p,4.394667,...,https://open.spotify.com/album/1nqz3cEjuvCMo8R...,spotify:album:1nqz3cEjuvCMo8RHLBI9kM,day,[https://i.scdn.co/image/ab67616d0000b27396f40...,,TWICE,"[4Y0chGCyYIRpdUqHJjndF7, 2Ij1NaPpsFSKJ0M65tSV4...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
6,MORE & MORE,TWICE,MORE & MORE,5KsduuDNWzt65TaHzmtciv,2020-06-01,63,199653,False,3omvXShuRPM3zbDpWYqf5g,3.327550,...,https://open.spotify.com/album/5KsduuDNWzt65Ta...,spotify:album:5KsduuDNWzt65TaHzmtciv,day,[https://i.scdn.co/image/ab67616d0000b27324869...,,TWICE,"[3omvXShuRPM3zbDpWYqf5g, 128rj96Z6tTEU3h3awSMd...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
7,Red Rover,YUQI,YUQ1,7LYc8ngbhwha4aGJ5kVauc,2024-04-23,47,123320,False,4TQBHR8LcbBUv0LvLmn54H,2.055333,...,https://open.spotify.com/album/7LYc8ngbhwha4aG...,spotify:album:7LYc8ngbhwha4aGJ5kVauc,day,[https://i.scdn.co/image/ab67616d0000b2736f99c...,,YUQI,"[6JgEbE6tFhcKILTL4Z82VA, 6kRV7e933KQw0BoXBkSoA...",[],833634.0,https://i.scdn.co/image/ab6761610000e5eb569026...
8,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,20Bf2RVERC5Bc2eo3vyvJv,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550,...,https://open.spotify.com/album/20Bf2RVERC5Bc2e...,spotify:album:20Bf2RVERC5Bc2eo3vyvJv,day,[https://i.scdn.co/image/ab67616d0000b273e59bd...,,"アトラスサウンドチーム, ATLUS GAME MUSIC","[3Jl2LQmRwbXEF2lO1RTvxn, 1d5r3NM4fqH8po53LkMzB...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",NaN,NaN
9,YES or YES,TWICE,YES or YES,25VunQEW0x2W6ALND2Mh4g,2018-11-05,68,237680,False,26OVhEqFDQH0Ij77QtmGP9,3.961333,...,https://open.spotify.com/album/25VunQEW0x2W6AL...,spotify:album:25VunQEW0x2W6ALND2Mh4g,day,[https://i.scdn.co/image/ab67616d0000b273140ba...,,TWICE,"[26OVhEqFDQH0Ij77QtmGP9, 7fEMfYZnjQ28Cpzi7QnkA...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
10,"""good guy""",Against The Current,"""good guy""",6bj1lsHiVqvJyqjv7qtrV4,2023-04-21,48,208052,True,3bfElZNhtvtGvWMVgCBgZK,3.467533,...,https://open.spotify.com/album/6bj1lsHiVqvJyqj...,spotify:album:6bj1lsHiVqvJyqjv7qtrV4,day,[https://i.scdn.co/image/ab67616d0000b2737d61e...,,Against The Current,[3bfElZNhtvtGvWMVgCBgZK],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",528949.0,https://i.scdn.co/image/ab6761610000e5eb469aba...
11,Shopper,IU,The Winning,08CvAj58nVMpq1Nw7T6maj,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333,...,https://open.spotify.com/album/08CvAj58nVMpq1N...,spotify:album:08CvAj58nVMpq1Nw7T6maj,day,[https://i.scdn.co/image/ab67616d0000b2735048e...,,IU,"[1c6kkrWnpy68eYDfBdxNtF, 0UTtK6hregIBOsefavRI2...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",9135223.0,https://i.scdn.co/image/ab6761610000e5ebbd0642...
12,POP!,NAYEON,IM NAYEON,0wqjfojWuTcbEvwaizvTMw,2022-06-24,72,168106,False,3lOMJTQTd6J34faYwASc33,2.801767,...,https://open.spotify.com/album/0wqjfojWuTcbEvw...,spotify:album:0wqjfojWuTcbEvwaizvTMw,day,[https://i.scdn.co/image/ab67616d0000b2735fb4a...,,NAYEON,"[3lOMJTQTd6J34faYwASc33, 4zHvWi4iFAG45lgiN7smL...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",2888086.0,https://i.scdn.co/image/ab6761610000e5eb8f7649...
13,青のすみか,Tatsuya Kitani,青のすみか,4QjNVlIw8Rx6jItSZtn2VS,2023-07-07,72,196466,False,12usPU2WnqgCHAW1EK2dfd,3.274433,...,https://open.spotify.com/album/4QjNVlIw8Rx6jIt...,spotify:album:4QjNVlIw8Rx6jItSZtn2VS,day,[https://i.scdn.co/image/ab67616d0000b273e9ce7...,,Tatsuya Kitani,[12usPU2WnqgCHAW1EK2dfd],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",NaN,NaN
14,CASANOVA POSSE,ALI,CASANOVA POSSE,2xfq9tUp4QOlCGT6j4k0g9,2025-01-10,65,240653,False,26Lip4WX1oWceF9tb8m2qw,4.010883,...,https://open.spotify.com/album/2xfq9tUp4QOlCGT...,spotify:album:2xfq9tUp4QOlCGT6j4k0g9,day,[https://i.scdn.co/image/ab67616d0000b2733fc87...,,ALI,[26Lip4WX1oWceF9tb8m2qw],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",NaN,NaN
15,Talk that Talk,TWICE,BETWEEN 1&2,3NZ94nQbqimcu2i71qhc4f,2022-08-26,69,177466,False,0RDqNCRBGrSegk16Avfzuq,2.957767,...,https://open.spotify.com/album/3NZ94nQbqimcu2i...,spotify:album:3NZ94nQbqimcu2i71qhc4f,day,[https://i.scdn.co/image/ab67616d0000b273c3040...,,TWICE,"[0RDqNCRBGrSegk16Avfzuq, 3sOEVB8DirQtZc0qhw8lJ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
16,Perfect World,TWICE,Perfect World,17rk8h2IU4wwSFXw9j2uR6,2021-07-28,58,182680,False,0iuZMy88H6vxDA2oaJNhJg,3.044667,...,https://open.spotify.com/album/17rk8h2IU4wwSFX...,spotify:album:17rk8h2IU4wwSFXw9j2uR6,day,[https://i.scdn.co/image/ab67616d0000b273579e9...,,TWICE,"[0iuZMy88H6vxDA2oaJNhJg, 1Wrn6btrungVsBjyViLnu...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
17,晴る,ヨルシカ,晴る,4O53dhmIctih3p2suAAgga,2024-01-05,74,270705,False,5eY7692tmgHB9dbmq6wa2M,4.511750,...,https://open.spotify.com/album/4O53dhmIctih3p2...,spotify:album:4O53dhmIctih3p2suAAgga,day,[https://i.scdn.co/image/ab67616d0000b2735e763...,,ヨルシカ,[5eY7692tmgHB9dbmq6wa2M],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",3032922.0,https://i.scdn.co/image/ab6761610000e5ebe62cff...
18,Super Lady,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,64,152186,False,5qI5EUqfDJpQ7w6sMECK7U,2.536433,...,https://open.spotify.com/album/0mC9MXPddkzggVs...,spotify:album:0mC9MXPddkzggVsOXh5gd3,day,[https://i.scdn.co/image/ab67616d0000b27342281...,,(G)I-DLE,"[0uLcuydgTo4ErT6aQQayuw, 3GwmjxMoBSFbcYVvZooKO...",[],10489801.0,https://i.scdn.co/image/ab6761610000e5eb7fd163...
19,Long Live (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),5AEDGbliTTfjOB8TSm1sxt,2023-07-07,73,317960,False,4hqJ4bSlYJOXb6Z4SRmzxs,5.299333,...,https://open.spotify.com/album/5AEDGbliTTfjOB8...,spotify:album:5AEDGbliTTfjOB8TSm1sxt,day,[https://i.scdn.co/image/ab67616d0000b2730b04d...,,Taylor Swift,"[7G0gBu6nLdhFDPRLc0HdDG, 3MytWN8L7shNYzGl4tAKR...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",135420613.0,https://i.scdn.co/image/ab6761610000e5ebe672b5...
20,Klaxon,(G)I-DLE,I SWAY,5WzUVTkKAvOayPui3DnsDz,2024-07-08,63,175106,False,294hRgOqnGW2BemqP8D35X,2.918433,...,https://open.spotify.com/album/5WzUVTkKAvOayPu...,spotify:album:5WzUVTkKAvOayPui3DnsDz,day,[https://i.scdn.co/image/ab67616d0000b27366f7b...,,(G)I-DLE,"[0d2ykpjGQwxSw7huc3l7vw, 2QcT3mwErl92KduUArSxZ...",[],10489801.0,https://i.scdn.co/image/ab6761610000e5eb7fd163...
21,No Celestial,LE SSERAFIM,ANTIFRAGILE,3u0ggfmK0vjuHMNdUbtaa9,2022-10-17,60,166491,False,21ApmVGIzIAIDSBdHu6SVt,2.774850,...,https://open.spotify.com/album/3u0ggfmK0vjuHMN...,spotify:album:3u0ggfmK0vjuHMNdUbtaa9,day,[https://i.scdn.co/image/ab67616d0000b273a9919...,,LE SSERAFIM,"[0JosgxxZKZ87QbW5TISJDE, 4fsQ0K37TOXa3hEQfjEic...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",6909574.0,https://i.scdn.co/image/ab6761610000e5eb593f35...
22,ONE SPARK,TWICE,With YOU-th,575TQDOQqc0MAheeEeKWUR,2024-02-23,67,183559,False,7cIn67LEvk16v6komC8znS,3.059317,...,https://open.spotify.com/album/575TQDOQqc0MAhe...,spotify:album:575TQDOQqc0MAheeEeKWUR,day,[https://i.scdn.co/image/ab67616d0000b273bd8c7...,,TWICE,"[0mgveJEIGjcN51w4JIQtI6, 7cIn67LEvk16v6komC8zn...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
23,Live My Life,aespa,Armageddon - The 1st Album,3gHhPm8z8tid1kvpniUKuK,2024-05-27,63,159133,False,1x1oCGsFUDViOvcISuoKW0,2.652217,...,https://open.spotify.com/album/3gHhPm8z8tid1kv...,spotify:album:3gHhPm8z8tid1kvpniUKuK,day,[https://i.scdn.co/image/ab67616d0000b2730fc59...,,aespa,"[2VdSktBqFfkW7y6q5Ik4Z4, 5eWcGfUCrVFMoYskyfkEP...","[AG, BB, BG, BS, DM, DO, GD, HK, HT, ID, IL, J...",8361617.0,https://i.scdn.co/image/ab6761610000e5ebf7a109...
24,Imaginary Friend,ITZY,GOLD,4CRfobFgSG0GOzplgTI79s,2024-10-15,66,202429,False,06BeeZaS4YArThfTMu80QS,3.373817,...,https://open.spotify.com/album/4CRfobFgSG0GOzp...,spotify:album:4CRfobFgSG0GOzplgTI79s,day,[https://i.scdn.co/image/ab67616d0000b273dd734...,,ITZY,"[1dqN2j0jL4qB72CNgCdQ09, 06BeeZaS4YArThfTMu80Q...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",8351660.0,https://i.scdn.co/image/ab6761610000e5eb344806...
25,Air,YEJI,AIR,6sJnzoRI9pXUo0gZxIviUS,2025-03-10,75,194800,False,6HSns0qPQQfgekCrBF0Dkf,3.246667,...,https://open.spotify.com/album/6sJnzoRI9pXUo0g...,spotify:album:6sJnzoRI9pXUo0gZxIviUS,day,[https://i.scdn.co/image/ab67616d0000b27338d7a...,,YEJI,"[6HSns0qPQQfgekCrBF0Dkf, 5xOUBAvwWYyuPmej4iRcV...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",114620.0,https://i.scdn.co/image/ab6761610000e5eb485cfb...
26,HER,MINNIE,HER,3sbZ4PoHTIZL8bLSLwt84h,2025-01-21,68,159797,False,2MbPhDgeXVipowltFneRH2,2.663283,...,https://open.spotify.com/album/3sbZ4PoHTIZL8bL...,spotify:album:3sbZ4PoHTIZL8bLSLwt84h,day,[https://i.scdn.co/image/ab67616d0000b2735b264...,,MINNIE,"[4wqyCBpp9zwtpSehLRciXT, 6XtNw289lraKPESASgB5H...",[],761745.0,https://i.scdn.co/image/ab6761610000e5eb0134f9...
27,境界線,amazarashi,七号線ロストボーイズ,0pqrWNxpcWBvR9A5A9JHHl,2022-04-13,49,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550,...,https://open.spotify.com/album/0pqrWNxpcWBvR9A...,spotify:album:0pqrWNxpcWBvR9A5A9JHHl,day,[https://i.scdn.co/image/ab67616d0000b2730262e...,,amazarashi,"[4g5yln7dtUaWz2bhD7s3Lp, 6C7rH9snYqVLTeFkmXv0g...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",458389.0,https://i.scdn.co/image/ab6761610000e5eb8c513f...
28,I TRUST YOU,エミリア(CV:高橋李依),"SONG FROM TV SERIES ""RE:ZERO -STARTING LIFE IN...",530vXGXkG5czn3hHdMPSMD,2024-11-14,34,255396,False,7Ccvd3UVSfORSNyeOO069h,4.256600,...,https://open.spotify.com/album/530vXGXkG5czn3h...,spotify:album:530vXGXkG5czn3hHdMPSMD,day,[https://i.scdn.co/image/ab67616d0000b2730dc35...,,Various Artists,"[25j7bzRhgwL29jfgReVFdy, 1aXQG0fOcIHIjPIpDLIl4...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",NaN,NaN
29,Alcohol-Free,TWICE,Taste of Love,00vb6sViDbJLmLLchfbRh4,2021-06-11,66,210573,False,0BTaaKT4RMbs5M73tOHX5Y,3.509550,...,https://open.spotify.com/album/00vb6sViDbJLmLL...,spotify:album:00vb6sViDbJLmLLchfbRh4,day,[https://i.scdn.co/image/ab67616d0000b273feede...,,TWICE,"[0BTaaKT4RMbs5M73tOHX5Y, 3YdqewCLgGsFhruA3EhIL...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
30,Beyond the Horizon,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,47,212826,False,27f7ZEBoJIJ3HzOpzqmDqO,3.547100,...,https://open.spotify.com/album/7tgTOUXm74GKA12...,spotify:album:7tgTOUXm74GKA12wsQIUPu,day,[https://i.scdn.co/image/ab67616d0000b273c1486...,,TWICE,"[27f7ZEBoJIJ3HzOpzqmDqO, 3JstVDAZKy4O8SZ5yoXdQ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
31,Ocean Deep,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,47,220106,False,6jya1u1sEhObLCDFGyWuAW,3.668433,...,https://open.spotify.com/album/7tgTOUXm74GKA12...,spotify:album:7tgTOUXm74GKA12wsQIUPu,day,[https://i.scdn.co/image/ab67616d0000b273c1486...,,TWICE,"[27f7ZEBoJIJ3HzOpzqmDqO, 3JstVDAZKy4O8SZ5yoXdQ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
32,Sunshine,OneRepublic,Sunshine,2YSlIS6gM38w7ZJNj8F3s6,2021-11-10,74,163854,False,5r43qanLhUCdBj8HN3fa6B,2.730900,...,https://open.spotify.com/album/2YSlIS6gM38w7ZJ...,spotify:album:2YSlIS6gM38w7ZJNj8F3s6,day,[https://i.scdn.co/image/ab67616d0000b2733b248...,,OneRepublic,[5r43qanLhUCdBj8HN3fa6B],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",18137033.0,https://i.scdn.co/image/ab6761610000e5eb57138b...
33,LOVE FOOLISH,TWICE,Feel Special,3NQBPabmRm3LzVcmtkTLfo,2019-09-23,53,191226,False,1MdEg2lk4EakgWnCvFUGEZ,3.187100,...,https://open.spotify.com/album/3NQBPabmRm3LzVc...,spotify:album:3NQBPabmRm3LzVcmtkTLfo,day,[https://i.scdn.co/image/ab67616d0000b273a6b5e...,,TWICE,"[3Hz3tTQwOdM6XkA0ALB2G9, 6uy9lTlZ3xaMYQPk6eaJa...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
34,DIVE,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,57,181860,False,3JstVDAZKy4O8SZ5yoXdQr,3.031000,...,https://open.spotify.com/album/7tgTOUXm74GKA12...,spotify:album:7tgTOUXm74GKA12wsQIUPu,day,[https://i.scdn.co/image/ab67616d0000b273c1486...,,TWICE,"[27f7ZEBoJIJ3HzOpzqmDqO, 3JstVDAZKy4O8SZ5yoXdQ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
35,Feel Special,TWICE,Feel Special,3NQBPabmRm3LzVcmtkTLfo,2019-09-23,71,206866,False,3Hz3tTQwOdM6XkA0ALB2G9,3.447767,...,https://open.spotify.com/album/3NQBPabmRm3LzVc...,spotify:album:3NQBPabmRm3LzVcmtkTLfo,day,[https://i.scdn.co/image/ab67616d0000b273a6b5e...,,TWICE,"[3Hz3tTQwOdM6XkA0ALB2G9, 6uy9lTlZ3xaMYQPk6eaJa...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
36,Hare Hare,TWICE,Hare Hare,7hF6oiU4zaIQIGjLhje1eG,2023-05-31,46,203546,False,3QcJghvqRS17RoPPP0C2sp,3.392433,...,https://open.spotify.com/album/7hF6oiU4zaIQIGj...,spotify:album:7hF6oiU4zaIQIGjLhje1eG,day,[https://i.scdn.co/image/ab67616d0000b27386220...,,TWICE,"[3QcJghvqRS17RoPPP0C2sp, 2MbxU95EQZbdRo0biiC6M...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
37,MOONLIGHT SUNRISE,TWICE,READY TO BE,7hzP5i7StxYG4StECA0rrJ,2023-03-10,61,180320,False,5IN9W6eUfk3014My9awagX,3.005333,...,https://open.spotify.com/album/7hzP5i7StxYG4St...,spotify:album:7hzP5i7StxYG4StECA0rrJ,day,[https://i.scdn.co/image/ab67616d0000b27359f57...,,TWICE,"[4OtVQ2ZxS7yigIjGz5yKg1, 5IN9W6eUfk3014My9awag...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
38,Baby Blue Love,TWICE,Taste of Love,00vb6sViDbJLmLLchfbRh4,2021-06-11,50,166666,False,7Jzo3IObpANz6giPTUrihB,2.777767,...,https://open.spotify.com/album/00vb6sViDbJLmLL...,spotify:album:00vb6sViDbJLmLLchfbRh4,day,[https://i.scdn.co/image/ab67616d0000b273feede...,,TWICE,"[0BTaaKT4RMbs5M73tOHX5Y, 3YdqewCLgGsFhruA3EhIL...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
39,Wife,(G)I-DLE,Wife,0C8qSTYZDkVcfnY6tIHIzK,2024-01-21,55,121226,False,6hWU8LrnjLyYHShDyNWFZj,2.020433,...,https://open.spotify.com/album/0C8qSTYZDkVcfnY...,spotify:album:0C8qSTYZDkVcfnY6tIHIzK,day,[https://i.scdn.co/image/ab67616d0000b27320f99...,,(G)I-DLE,[326PEjfqveu646UhjHrth9],[],10489801.0,https://i.scdn.co/image/ab6761610000e5eb7fd163...
40,Secret,IU,Last Fantasy,149BHv6qAyMgJ483vPi77C,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867,...,https://open.spotify.com/album/149BHv6qAyMgJ48...,spotify:album:149BHv6qAyMgJ483vPi77C,day,[https://i.scdn.co/image/ab67616d0000b273bf5f4...,,IU,"[38HJ2NhRdr68S1UAi9r3vc, 79PkC8ii2W7Grvvkqazgf...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",9135223.0,https://i.scdn.co/image/ab6761610000e5ebbd0642...
41,Likey,TWICE,Twicetagram,3hJXmK5gWN9P6jtZL0Lr2y,2017-10-30,67,207813,False,0IEVKWduAaMcZepZQVr80T,3.463550,...,https://open.spotify.com/album/3hJXmK5gWN9P6jt...,spotify:album:3hJXmK5gWN9P6jtZL0Lr2y,day,[https://i.scdn.co/image/ab67616d0000b2736034e...,,TWICE,"[0IEVKWduAaMcZepZQVr80T, 1LQtxz9fIrZskoqDSbhKd...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
42,Mine (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),5AEDGbliTTfjOB8TSm1sxt,2023-07-07,74,231706,False,7G0gBu6nLdhFDPRLc0HdDG,3.861767,...,https://open.spotify.com/album/5AEDGbliTTfjOB8...,spotify:album:5AEDGbliTTfjOB8TSm1sxt,day,[https://i.scdn.co/image/ab67616d0000b2730b04d...,,Taylor Swift,"[7G0gBu6nLdhFDPRLc0HdDG, 3MytWN8L7shNYzGl4tAKR...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",135420613.0,https://i.scdn.co/image/ab6761610000e5ebe672b5...
43,Whiplash,aespa,Whiplash - The 5th Mini Album,3OaW4df1SA62k0arNpn6bK,2024-10-21,78,183226,False,6uPnrBgweGOcwjFL4ItAvV,3.053767,...,https://open.spotify.com/album/3OaW4df1SA62k0a...,spotify:album:3OaW4df1SA62k0arNpn6bK,day,[https://i.scdn.co/image/ab67616d0000b273e467a...,,aespa,"[6uPnrBgweGOcwjFL4ItAvV, 7dYEUpcXJLDcI22m0dgmn...","[AG, BB, BG, BS, DM, DO, GD, HK, HT, ID, IL, J...",8361617.0,https://i.scdn.co/image/ab6761610000e5ebf7a109...
44,I GOT YOU,TWICE,With YOU-th,575TQDOQqc0MAheeEeKWUR,2024-02-23,54,173240,False,0mgveJEIGjcN51w4JIQtI6,2.887333,...,https://open.spotify.com/album/575TQDOQqc0MAhe...,spotify:album:575TQDOQqc0MAheeEeKWUR,day,[https://i.scdn.co/image/ab67616d0000b273bd8c7...,,TWICE,"[0mgveJEIGjcN51w4JIQtI6, 7cIn67LEvk16v6komC8zn...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",21665446.0,https://i.scdn.co/image/ab6761610000e5ebca6c14...
45,ABCD,NAYEON,NA,5zQI9dFbS9TrhvC9clgjz7,2024-06-14,72,162840,False,0V2passWyAXnON67kfAj7y,2.714000,...,https://open.spotify.com/album/5zQI9dFbS9TrhvC...,spotify:album:5zQI9dFbS9TrhvC9clgjz7,day,[https://i.scdn.co/image/ab67616d0000b27373f05...,,NAYEON,"[0V2passWyAXnON67kfAj7y, 07W0lOkOUhVhdJQ9wVepW...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C...",2888086.0,https://i.scdn.co/image/ab6761610000e5eb8f7649...
46,Wife,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,60,121226,False,1j8jqwFpFQ8YqsIJAiYFLZ,2.020433,...,https://open.spotify.com/album/0mC9MXPddkzggVs...,spotify:album:0mC9MXPddkzggVsOXh5gd3,day,[https://i.scdn.co/image/ab67616d0000b27342281...,,(G)I-DLE,"[0uLcuydgTo4ErT6aQQayuw, 3GwmjxMoBSFbcYVvZooKO...",[],10489801.0,https://i.scdn.co/image/ab6761610000e5eb7fd163...