# Load Data

In [1]:
import pandas as pd
import numpy as np
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
import os
from pathlib import Path

# Extract credential access Spotify API

In [2]:
env_path = Path("..") / ".env"
load_dotenv(dotenv_path=env_path)
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")
REDIRECT_URI = os.getenv("REDIRECT_URI")

# Extract Spotify data

## Helper Functions

In [3]:
def extract_top_tracks_data(spotify_client,time_range)->pd.DataFrame:
    '''
    Convert JSON file extracted from spotify 
    to dataframe for analysis
    '''
    top_tracks_json = spotify_client.current_user_top_tracks(limit=50, time_range=time_range)
    track_list = []

    for item in top_tracks_json['items']:
        track_info = {
            'track_name':item['name'],
            'artist_name': item['artists'][0]['name'],
            'album_name': item['album']['name'],
            'album_id': item['album']['id'],
            'release_date': item['album']['release_date'],
            'popularity': item['popularity'],
            'duration_ms': item['duration_ms'],
            'explicit':item['explicit'],
            'track_id': item['id']
        }
        track_list.append(track_info)
    
    data = pd.DataFrame(track_list)
    data['duration_min'] = data['duration_ms']/60000
    data['release_date'] = pd.to_datetime(data['release_date'])

    return data

def extract_top_artist_data(spotify_client,time_range)->pd.DataFrame:
    '''
    Convert JSON file extracted from Spotify
    to dataframe for analysis
    '''
    top_artist_json = spotify_client.current_user_top_artists(limit = 50,time_range = time_range)
    artist_list = []
    for item in top_artist_json['items']:
        artist_info = {
            'artist_name':item['name'],
            'popularity':item['popularity'],
            'genres': ', '.join(item['genres']),
            'artist_id': item['id'],
            'followers': item['followers']['total'],
            # Gets the largest image if exists
            'image_url': item['images'][0]['url'] if item['images'] else None
        }
        artist_list.append(artist_info)
    data = pd.DataFrame(artist_list)
    return data

def get_albums_info(spotify_client,album_ids)->pd.DataFrame:
    '''
    Extract album information from top songs 
    '''
    album_data = [] 

    for i in range(0,len(album_ids),20):
        # Spotify API limit requests to 20 albums per call 
        batch = album_ids[i:i+20]
        albums = spotify_client.albums(batch)['albums']
        for album in albums:
            album_info = {
        'album_id': album['id'],
        'album_name': album['name'],
        'release_date': album['release_date'],
        'total_tracks': album['total_tracks'],
        'label': album.get('label', ''),
        'popularity': album.get('popularity'),
        'album_type': album['album_type'],
        'external_url': album['external_urls']['spotify'],
        'album_uri': album['uri'],
        'release_date_precision': album['release_date_precision'],
        'images': [image['url'] for image in album['images']] if album['images'] else [],  # List of images with varying sizes
        'genres': ', '.join(album['genres']) if 'genres' in album else '',  # Check if genres are present
        'artists': ', '.join([artist['name'] for artist in album['artists']]),  # Add artist names
        'track_ids': [track['id'] for track in album['tracks']['items']],  # Extract track IDs
        'available_markets': album.get('available_markets', []),  # Get available markets for the album
        }
            album_data.append(album_info)
    data = pd.DataFrame(album_data)
    return data

def get_tracks_info(spotify_client,track_ids)->pd.DataFrame:
    '''
    Extract additional information on top tracks
    '''
    track_data = [] 

    for i in range(0,len(track_ids),50):
        batch = track_ids[i:i+50]
        tracks = spotify_client.tracks(batch)['tracks']
        for track in tracks:
            track_info = {
                'track_id':track['id'],
                'track_name':track['name'],
                'popularity':track['popularity'],
                'explicit':track['explicit'],
                'artist_id':track['artists'][0]['id'],
                'album_id':track['album']['id'],
                # URL provide 30s preview of track
                'preview_url':track.get('preview_url',''),
                # URL of track page in spotify 
                'track_url':track['external_urls']['spotify'],
                # External Identifier to track songs globally
                'track_external_id':track['external_ids'].get('isrc',''),
                # Check whether track saved in user device
                'is_local':track['is_local'],
            }
            track_data.append(track_info)

    track_data = pd.DataFrame(track_data)
    return track_data

# Fetch Top Tracks

In [4]:
# Optional: remove existing cache for fresh login
if os.path.exists(".cache-my-music-app"):
    os.remove(".cache-my-music-app")

# Create the OAuth object
sp_oauth = SpotifyOAuth(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    redirect_uri=REDIRECT_URI,
    scope=["user-top-read", "user-library-read", "playlist-read-private"],
    cache_path=".cache-my-music-app"
)

# Create the Spotify client using the SpotifyOAuth instance directly
sp = spotipy.Spotify(auth_manager=sp_oauth)

# Test API call
try:
    results = sp.current_user_top_tracks(limit=10)
    for idx, item in enumerate(results['items']):
        print(f"{idx+1}. {item['name']} - {item['artists'][0]['name']}")
except spotipy.exceptions.SpotifyException as e:
    print(f"Error: {e}")

print("Fetching your top tracks...")
top_tracks = sp.current_user_top_tracks(
    limit=50, time_range='medium_term'
    )

short_term_track_data = extract_top_tracks_data(sp,'short_term')
medium_term_track_data = extract_top_tracks_data(sp,'medium_term')
long_term_track_data = extract_top_tracks_data(sp,'long_term')

1. CASANOVA POSSE - ALI
2. HER - MINNIE
3. Imaginary Friend - ITZY
4. Air - YEJI
5. I TRUST YOU - エミリア(CV:高橋李依)
6. Shopper - IU
7. Secret - IU
8. Whiplash - aespa
9. FREAK - YUQI
10. NEMONEMO - YENA
Fetching your top tracks...

# Fetch Top Artist

In [5]:
short_term_artists = extract_top_artist_data(sp,'short_term')
medium_term_artists = extract_top_artist_data(sp,'medium_term')
long_term_artists = extract_top_artist_data(sp,'long_term')
long_term_artists

,artist_name,popularity,genres,artist_id,followers,image_url
0,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0,21665446,https://i.scdn.co/image/ab6761610000e5ebca6c14...
1,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx,10489801,https://i.scdn.co/image/ab6761610000e5eb7fd163...
2,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V,119923718,https://i.scdn.co/image/ab6761610000e5eb399444...
3,Taylor Swift,98,,06HL4z0CvFAxyc27GXpf02,135420613,https://i.scdn.co/image/ab6761610000e5ebe672b5...
4,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU,9135223,https://i.scdn.co/image/ab6761610000e5ebbd0642...
5,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3,8351660,https://i.scdn.co/image/ab6761610000e5eb344806...
6,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE,8361617,https://i.scdn.co/image/ab6761610000e5ebf7a109...
7,Against The Current,64,pop punk,6yhD1KjhLxIETFF7vIRf8B,528949,https://i.scdn.co/image/ab6761610000e5eb469aba...
8,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX,761745,https://i.scdn.co/image/ab6761610000e5eb1a9a17...
9,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ,5451531,https://i.scdn.co/image/ab6761610000e5eb538dad...
10,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6,833634,https://i.scdn.co/image/ab6761610000e5eb569026...
11,BURNOUT SYNDROMES,56,"anime, j-rock, j-pop",0Oazwl71qoHvXnbSxv0wOT,290783,https://i.scdn.co/image/ab6761610000e5eb6a9d23...
12,結束バンド,63,"anime, j-rock, j-pop",2nvl0N9GwyX69RRBMEZ4OD,604207,https://i.scdn.co/image/ab6761610000e5eb38df32...
13,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN,807593,https://i.scdn.co/image/ab6761610000e5eb1135e1...
14,Fall Out Boy,80,"emo, pop punk, emo pop",4UXqAaa6dQYAk18Lv7PEgX,11219001,https://i.scdn.co/image/ab6761610000e5eb362011...
15,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik,3032922,https://i.scdn.co/image/ab6761610000e5ebe62cff...
16,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS,4271004,https://i.scdn.co/image/ab6761610000e5ebb419d6...
17,MKTO,67,,2l35CQqtYRh3d8ZIiBep4v,1106949,https://i.scdn.co/image/ab6761610000e5ebbc861f...
18,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX,810891,https://i.scdn.co/image/ab6761610000e5eb9cc45f...
19,NAYEON,64,k-pop,1VwDG9aBflQupaFNjUru9A,2888086,https://i.scdn.co/image/ab6761610000e5eb8f7649...
20,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo,994169,https://i.scdn.co/image/ab6761610000e5eb8bb041...
21,YOASOBI,76,"j-pop, anime",64tJ2EAv1R6UaZqc4iOCyj,8997684,https://i.scdn.co/image/ab6761610000e5ebbfdd8a...
22,Owl City,70,,07QEuhtrNmmZ0zEcqE9SF6,2486691,https://i.scdn.co/image/ab6761610000e5ebce3fbd...
23,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ,18137033,https://i.scdn.co/image/ab6761610000e5eb57138b...
24,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU,57698296,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...
25,LiSA,71,"anime, j-pop, j-rock",0blbVefuxOGltDBa00dspv,3370607,https://i.scdn.co/image/ab6761610000e5eb774ac8...
26,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p,6909574,https://i.scdn.co/image/ab6761610000e5eb593f35...
27,The Cab,56,,2C2sVVXanbOpymYBMpsi89,561668,https://i.scdn.co/image/ff6eb786aff45ab50e9820...
28,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu,3064731,https://i.scdn.co/image/ab6761610000e5ebb5d9eb...
29,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL,979380,https://i.scdn.co/image/ab6761610000e5eb92d8ef...
30,RADWIMPS,74,"anime, j-pop, j-rock",1EowJ1WwkMzkCkRomFhui7,4455350,https://i.scdn.co/image/ab6761610000e5eb78cca9...
31,Ado,77,"j-pop, anime, vocaloid, j-rock",6mEQK9m2krja6X1cfsAjfl,5850156,https://i.scdn.co/image/ab6761610000e5ebbcb1c1...
32,Konomi Suzuki,53,"anime, j-pop, j-rock",3O0kLS5sLZ41XZRxjBKmLF,218930,https://i.scdn.co/image/ab6761610000e5ebce9e87...
33,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m,114620,https://i.scdn.co/image/ab6761610000e5eb485cfb...
34,Relaxu,45,,7Glr8id1TfFSYoK04ENmNK,7874,https://i.scdn.co/image/ab6761610000e5eb73b8b4...
35,BoyWithUke,73,,1Cd373x8qzC7SNUg5IToqp,4495994,https://i.scdn.co/image/ab6761610000e5ebc69a43...
36,Paramore,82,"pop punk, emo, emo pop",74XFHRwlV6OrjEM0A2NCMF,9302550,https://i.scdn.co/image/ab6761610000e5ebb10c34...
37,BAND-MAID,52,"j-rock, k-rock",5Wh3G01Xfxn2zzEZNpuYHH,332808,https://i.scdn.co/image/ab6761610000e5eb3dc779...
38,Lyn,63,japanese vgm,5qEtLvXzYdv0G7c7rR6irX,127494,https://i.scdn.co/image/ab6761610000e5eb391264...
39,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs,5685017,https://i.scdn.co/image/ab6761610000e5eb9e33dd...
40,Glee Cast,70,christmas,0SCbttzoZTnLFebDYmAWCm,1537373,https://i.scdn.co/image/5b5a95f260ac429405e871...
41,ROSÉ,86,k-pop,3eVa5w3URK5duf6eyVDbu9,10941714,https://i.scdn.co/image/ab6761610000e5eb727a1f...
42,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF,740603,https://i.scdn.co/image/ab6761610000e5eb369406...
43,MindaRyn,43,anime,7MSns7VCEysJJhcp67gvtZ,46241,https://i.scdn.co/image/ab6761610000e5eb4e52ed...
44,TZUYU,52,k-pop,1arCVYXeStgCY2UazBNBLK,308945,https://i.scdn.co/image/ab6761610000e5eb9f631e...
45,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl,3607044,https://i.scdn.co/image/ab6761610000e5ebb75519...
46,fripSide,51,"anime, j-pop, j-rock",7ucOhItVkxNqunNLo8AkzN,237351,https://i.scdn.co/image/ab6761610000e5eb799924...
47,amazarashi,55,"anime, j-rock, j-pop",6T4K8YuFc0JPDrYgABbxao,458389,https://i.scdn.co/image/ab6761610000e5eb8c513f...
48,BLACKPINK,80,k-pop,41MozSoPIsD1dJM0CLPjZF,53481762,https://i.scdn.co/image/ab6761610000e5ebc9690b...
49,Panic! At The Disco,78,emo,20JZFwl6HVl6yg8a4H3ZqK,12576152,https://i.scdn.co/image/ab6761610000e5ebb256ae...

# Extract additional info on Tracks

In [6]:
short_term_track_id  = short_term_track_data['track_id'].unique().tolist()
medium_term_track_id  = medium_term_track_data['track_id'].unique().tolist()
long_term_track_id  = long_term_track_data['track_id'].unique().tolist()

short_term_tracks = get_tracks_info(sp,short_term_track_id)
medium_term_tracks = get_tracks_info(sp,medium_term_track_id)
long_term_tracks = get_tracks_info(sp,long_term_track_id)

In [9]:
long_term_tracks

,track_id,track_name,popularity,explicit,artist_id,album_id,preview_url,track_url,track_external_id,is_local
0,47N81NMkB488fuOwOC3Oip,Nobody - from Kaiju No. 8,70,False,5Pwc4xIPtQLFEnJriah9YJ,3YmKf1haPAblZIrIPpuRTf,None,https://open.spotify.com/track/47N81NMkB488fuO...,USUM72403147,False
1,35dhwUoJNlxrPyEIJkfDnx,I GOT YOU,59,False,7n2Ycct7Beij7Dj7meI4X0,6RZHj6L3NqrvcKeiBHQbjL,None,https://open.spotify.com/track/35dhwUoJNlxrPyE...,US5TA2300237,False
2,6ERs9uORCo1MfV0m9ixCuv,FREAK,57,False,22aCD8IrQZjcPgZw728QT6,7LYc8ngbhwha4aGJ5kVauc,None,https://open.spotify.com/track/6ERs9uORCo1MfV0...,KRA392400004,False
3,5vK3WrTOp6rEoASx1jAsp1,DIVE,57,False,7n2Ycct7Beij7Dj7meI4X0,0riep5s1F9ynpobjOSzbcr,None,https://open.spotify.com/track/5vK3WrTOp6rEoAS...,JPWP02470699,False
4,2vNPGH1x5ZwxTjlvzLCyc2,Fate,62,False,2AfmfGFbe0A0WsTYm0SDTx,0mC9MXPddkzggVsOXh5gd3,None,https://open.spotify.com/track/2vNPGH1x5ZwxTjl...,KRA392300030,False
5,65rmgd5uMb4Rgqb5dSiU0p,Doughnut,53,False,7n2Ycct7Beij7Dj7meI4X0,1nqz3cEjuvCMo8RHLBI9kM,None,https://open.spotify.com/track/65rmgd5uMb4Rgqb...,JPWP02170915,False
6,3omvXShuRPM3zbDpWYqf5g,MORE & MORE,63,False,7n2Ycct7Beij7Dj7meI4X0,5KsduuDNWzt65TaHzmtciv,None,https://open.spotify.com/track/3omvXShuRPM3zbD...,US5TA2000050,False
7,4TQBHR8LcbBUv0LvLmn54H,Red Rover,48,False,22aCD8IrQZjcPgZw728QT6,7LYc8ngbhwha4aGJ5kVauc,None,https://open.spotify.com/track/4TQBHR8LcbBUv0L...,KRA392400007,False
8,3Jl2LQmRwbXEF2lO1RTvxn,Full Moon Full Life,65,False,4VeqFgWkP7P9eEGwzPuXcM,20Bf2RVERC5Bc2eo3vyvJv,None,https://open.spotify.com/track/3Jl2LQmRwbXEF2l...,JPK652300101,False
9,26OVhEqFDQH0Ij77QtmGP9,YES or YES,68,False,7n2Ycct7Beij7Dj7meI4X0,25VunQEW0x2W6ALND2Mh4g,None,https://open.spotify.com/track/26OVhEqFDQH0Ij7...,US5TA1800109,False
10,3bfElZNhtvtGvWMVgCBgZK,"""good guy""",48,True,6yhD1KjhLxIETFF7vIRf8B,6bj1lsHiVqvJyqjv7qtrV4,None,https://open.spotify.com/track/3bfElZNhtvtGvWM...,QZGLS2365263,False
11,1c6kkrWnpy68eYDfBdxNtF,Shopper,55,False,3HqSLMAZ3g3d5poNaI7GOU,08CvAj58nVMpq1Nw7T6maj,None,https://open.spotify.com/track/1c6kkrWnpy68eYD...,KRA382401058,False
12,3lOMJTQTd6J34faYwASc33,POP!,72,False,1VwDG9aBflQupaFNjUru9A,0wqjfojWuTcbEvwaizvTMw,None,https://open.spotify.com/track/3lOMJTQTd6J34fa...,US5TA2200041,False
13,12usPU2WnqgCHAW1EK2dfd,青のすみか,72,False,7mvhRvEAHiCTQHUnH7fgnv,4QjNVlIw8Rx6jItSZtn2VS,None,https://open.spotify.com/track/12usPU2WnqgCHAW...,JPU902302107,False
14,26Lip4WX1oWceF9tb8m2qw,CASANOVA POSSE,65,False,2Qqrew4ZcEwf9NY7UqWGfU,2xfq9tUp4QOlCGT6j4k0g9,None,https://open.spotify.com/track/26Lip4WX1oWceF9...,JPU902404263,False
15,0RDqNCRBGrSegk16Avfzuq,Talk that Talk,69,False,7n2Ycct7Beij7Dj7meI4X0,3NZ94nQbqimcu2i71qhc4f,None,https://open.spotify.com/track/0RDqNCRBGrSegk1...,US5TA2200073,False
16,0iuZMy88H6vxDA2oaJNhJg,Perfect World,58,False,7n2Ycct7Beij7Dj7meI4X0,17rk8h2IU4wwSFXw9j2uR6,None,https://open.spotify.com/track/0iuZMy88H6vxDA2...,JPWP02170588,False
17,5eY7692tmgHB9dbmq6wa2M,晴る,74,False,4UK2Lzi6fBfUi9rpDt6cik,4O53dhmIctih3p2suAAgga,None,https://open.spotify.com/track/5eY7692tmgHB9db...,JPPO02304150,False
18,5qI5EUqfDJpQ7w6sMECK7U,Super Lady,64,False,2AfmfGFbe0A0WsTYm0SDTx,0mC9MXPddkzggVsOXh5gd3,None,https://open.spotify.com/track/5qI5EUqfDJpQ7w6...,KRA392300025,False
19,4hqJ4bSlYJOXb6Z4SRmzxs,Long Live (Taylor's Version),73,False,06HL4z0CvFAxyc27GXpf02,5AEDGbliTTfjOB8TSm1sxt,None,https://open.spotify.com/track/4hqJ4bSlYJOXb6Z...,USUG12302086,False
20,294hRgOqnGW2BemqP8D35X,Klaxon,63,False,2AfmfGFbe0A0WsTYm0SDTx,5WzUVTkKAvOayPui3DnsDz,None,https://open.spotify.com/track/294hRgOqnGW2Bem...,KRA392400011,False
21,21ApmVGIzIAIDSBdHu6SVt,No Celestial,60,False,4SpbR6yFEvexJuaBpgAU5p,3u0ggfmK0vjuHMNdUbtaa9,None,https://open.spotify.com/track/21ApmVGIzIAIDSB...,USA2P2230331,False
22,7cIn67LEvk16v6komC8znS,ONE SPARK,67,False,7n2Ycct7Beij7Dj7meI4X0,575TQDOQqc0MAheeEeKWUR,None,https://open.spotify.com/track/7cIn67LEvk16v6k...,US5TA2400002,False
23,1x1oCGsFUDViOvcISuoKW0,Live My Life,63,False,6YVMFz59CuY7ngCxTxjpxE,3gHhPm8z8tid1kvpniUKuK,None,https://open.spotify.com/track/1x1oCGsFUDViOvc...,KRA302400100,False
24,06BeeZaS4YArThfTMu80QS,Imaginary Friend,66,False,2KC9Qb60EaY0kW4eH68vr3,4CRfobFgSG0GOzplgTI79s,None,https://open.spotify.com/track/06BeeZaS4YArThf...,US5TA2400234,False
25,6HSns0qPQQfgekCrBF0Dkf,Air,75,False,3skli1w2n0nOZ4qkDbvV2m,6sJnzoRI9pXUo0gZxIviUS,None,https://open.spotify.com/track/6HSns0qPQQfgekC...,US5TA2500003,False
26,2MbPhDgeXVipowltFneRH2,HER,69,False,2pHkxVNynHBwQHhGaoBIXX,3sbZ4PoHTIZL8bLSLwt84h,None,https://open.spotify.com/track/2MbPhDgeXVipowl...,KRA392400036,False
27,3jfSorOGnWLPgYqtIuL6OI,境界線,48,False,6T4K8YuFc0JPDrYgABbxao,0pqrWNxpcWBvR9A5A9JHHl,None,https://open.spotify.com/track/3jfSorOGnWLPgYq...,JPU902102765,False
28,7Ccvd3UVSfORSNyeOO069h,I TRUST YOU,34,False,74NNqfYPIeWy9p6DTDxkcK,530vXGXkG5czn3hHdMPSMD,None,https://open.spotify.com/track/7Ccvd3UVSfORSNy...,JPD732401868,False
29,0BTaaKT4RMbs5M73tOHX5Y,Alcohol-Free,66,False,7n2Ycct7Beij7Dj7meI4X0,00vb6sViDbJLmLLchfbRh4,None,https://open.spotify.com/track/0BTaaKT4RMbs5M7...,US5TA2100022,False
30,27f7ZEBoJIJ3HzOpzqmDqO,Beyond the Horizon,47,False,7n2Ycct7Beij7Dj7meI4X0,7tgTOUXm74GKA12wsQIUPu,None,https://open.spotify.com/track/27f7ZEBoJIJ3HzO...,JPWP02470698,False
31,6jya1u1sEhObLCDFGyWuAW,Ocean Deep,47,False,7n2Ycct7Beij7Dj7meI4X0,7tgTOUXm74GKA12wsQIUPu,None,https://open.spotify.com/track/6jya1u1sEhObLCD...,JPWP02470700,False
32,5r43qanLhUCdBj8HN3fa6B,Sunshine,74,False,5Pwc4xIPtQLFEnJriah9YJ,2YSlIS6gM38w7ZJNj8F3s6,None,https://open.spotify.com/track/5r43qanLhUCdBj8...,USUM72100506,False
33,1MdEg2lk4EakgWnCvFUGEZ,LOVE FOOLISH,53,False,7n2Ycct7Beij7Dj7meI4X0,3NQBPabmRm3LzVcmtkTLfo,None,https://open.spotify.com/track/1MdEg2lk4EakgWn...,US5TA1900078,False
34,3JstVDAZKy4O8SZ5yoXdQr,DIVE,57,False,7n2Ycct7Beij7Dj7meI4X0,7tgTOUXm74GKA12wsQIUPu,None,https://open.spotify.com/track/3JstVDAZKy4O8SZ...,JPWP02470699,False
35,3Hz3tTQwOdM6XkA0ALB2G9,Feel Special,71,False,7n2Ycct7Beij7Dj7meI4X0,3NQBPabmRm3LzVcmtkTLfo,None,https://open.spotify.com/track/3Hz3tTQwOdM6XkA...,US5TA1900074,False
36,3QcJghvqRS17RoPPP0C2sp,Hare Hare,46,False,7n2Ycct7Beij7Dj7meI4X0,7hF6oiU4zaIQIGjLhje1eG,None,https://open.spotify.com/track/3QcJghvqRS17RoP...,JPWP02370259,False
37,5IN9W6eUfk3014My9awagX,MOONLIGHT SUNRISE,61,False,7n2Ycct7Beij7Dj7meI4X0,7hzP5i7StxYG4StECA0rrJ,None,https://open.spotify.com/track/5IN9W6eUfk3014M...,US5TA2200206,False
38,7Jzo3IObpANz6giPTUrihB,Baby Blue Love,50,False,7n2Ycct7Beij7Dj7meI4X0,00vb6sViDbJLmLLchfbRh4,None,https://open.spotify.com/track/7Jzo3IObpANz6gi...,US5TA2100026,False
39,6hWU8LrnjLyYHShDyNWFZj,Wife,56,False,2AfmfGFbe0A0WsTYm0SDTx,0C8qSTYZDkVcfnY6tIHIzK,None,https://open.spotify.com/track/6hWU8LrnjLyYHSh...,KRA392300032,False
40,38HJ2NhRdr68S1UAi9r3vc,Secret,37,False,3HqSLMAZ3g3d5poNaI7GOU,149BHv6qAyMgJ483vPi77C,None,https://open.spotify.com/track/38HJ2NhRdr68S1U...,KRA381002288,False
41,0IEVKWduAaMcZepZQVr80T,Likey,66,False,7n2Ycct7Beij7Dj7meI4X0,3hJXmK5gWN9P6jtZL0Lr2y,None,https://open.spotify.com/track/0IEVKWduAaMcZep...,US5TA1700096,False
42,7G0gBu6nLdhFDPRLc0HdDG,Mine (Taylor's Version),74,False,06HL4z0CvFAxyc27GXpf02,5AEDGbliTTfjOB8TSm1sxt,None,https://open.spotify.com/track/7G0gBu6nLdhFDPR...,USUG12302073,False
43,6uPnrBgweGOcwjFL4ItAvV,Whiplash,78,False,6YVMFz59CuY7ngCxTxjpxE,3OaW4df1SA62k0arNpn6bK,None,https://open.spotify.com/track/6uPnrBgweGOcwjF...,KRA302400341,False
44,0mgveJEIGjcN51w4JIQtI6,I GOT YOU,54,False,7n2Ycct7Beij7Dj7meI4X0,575TQDOQqc0MAheeEeKWUR,None,https://open.spotify.com/track/0mgveJEIGjcN51w...,US5TA2300237,False
45,0V2passWyAXnON67kfAj7y,ABCD,72,False,1VwDG9aBflQupaFNjUru9A,5zQI9dFbS9TrhvC9clgjz7,None,https://open.spotify.com/track/0V2passWyAXnON6...,US5TA2400099,False
46,1j8jqwFpFQ8YqsIJAiYFLZ,Wife,60,False,2AfmfGFbe0A0WsTYm0SDTx,0mC9MXPddkzggVsOXh5gd3,None,https://open.spotify.com/track/1j8jqwFpFQ8YqsI...,KRA392300032,False
47,4Cyf87ul1le0xTWRFBoYd7,Killin’ Me Good,64,False,7F1iAHRYxR3MY7yAEuFqgL,1GIkapvyAw5lwdNw66hI44,None,https://open.spotify.com/track/4Cyf87ul1le0xTW...,US5TA2300087,False
48,4UwsXGVppRRJpKBHy0mtyK,NEMONEMO,67,False,49muoiIu4uea4PO8vueUNN,6FLiJ4318RtpA5lYWJt2cL,None,https://open.spotify.com/track/4UwsXGVppRRJpKB...,KRMIM2465530,False
49,0mtmrbRFsectINNpHdDkUQ,Just Imagine It,50,False,2l35CQqtYRh3d8ZIiBep4v,1TCiADBOmKJgdxULZPrK2a,None,https://open.spotify.com/track/0mtmrbRFsectINN...,USSM11505904,False

# Fetch Top Albums

In [7]:
short_term_track_album_id  = short_term_track_data['album_id'].unique().tolist()
medium_term_track_album_id  = medium_term_track_data['album_id'].unique().tolist()
long_term_track_album_id  = long_term_track_data['album_id'].unique().tolist()

short_term_albums = get_albums_info(sp,short_term_track_album_id)
medium_term_albums = get_albums_info(sp,medium_term_track_album_id)
long_term_albums = get_albums_info(sp,long_term_track_album_id)

In [8]:
long_term_albums

,album_id,album_name,release_date,total_tracks,label,popularity,album_type,external_url,album_uri,release_date_precision,images,genres,artists,track_ids,available_markets
0,3YmKf1haPAblZIrIPpuRTf,Nobody (from Kaiju No. 8),2024-04-12,1,Mosley Music/Interscope Records,58,single,https://open.spotify.com/album/3YmKf1haPAblZIr...,spotify:album:3YmKf1haPAblZIrIPpuRTf,day,[https://i.scdn.co/image/ab67616d0000b2732b386...,,OneRepublic,[47N81NMkB488fuOwOC3Oip],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
1,6RZHj6L3NqrvcKeiBHQbjL,I GOT YOU,2024-02-02,2,Republic Records - TWICE,48,single,https://open.spotify.com/album/6RZHj6L3NqrvcKe...,spotify:album:6RZHj6L3NqrvcKeiBHQbjL,day,[https://i.scdn.co/image/ab67616d0000b273d6a44...,,TWICE,"[35dhwUoJNlxrPyEIJkfDnx, 2iMtwujjXUGjpUraeSrvIm]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
2,7LYc8ngbhwha4aGJ5kVauc,YUQ1,2024-04-23,7,Cube Entertainment,51,album,https://open.spotify.com/album/7LYc8ngbhwha4aG...,spotify:album:7LYc8ngbhwha4aGJ5kVauc,day,[https://i.scdn.co/image/ab67616d0000b2736f99c...,,YUQI,"[6JgEbE6tFhcKILTL4Z82VA, 6kRV7e933KQw0BoXBkSoA...",[]
3,0riep5s1F9ynpobjOSzbcr,DIVE,2024-07-10,1,WM Japan,46,single,https://open.spotify.com/album/0riep5s1F9ynpob...,spotify:album:0riep5s1F9ynpobjOSzbcr,day,[https://i.scdn.co/image/ab67616d0000b27303661...,,TWICE,[5vK3WrTOp6rEoASx1jAsp1],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
4,0mC9MXPddkzggVsOXh5gd3,2,2024-01-29,8,Cube Entertainment,60,album,https://open.spotify.com/album/0mC9MXPddkzggVs...,spotify:album:0mC9MXPddkzggVsOXh5gd3,day,[https://i.scdn.co/image/ab67616d0000b27342281...,,(G)I-DLE,"[0uLcuydgTo4ErT6aQQayuw, 3GwmjxMoBSFbcYVvZooKO...",[]
5,1nqz3cEjuvCMo8RHLBI9kM,Celebrate,2022-07-27,9,WM Japan,50,album,https://open.spotify.com/album/1nqz3cEjuvCMo8R...,spotify:album:1nqz3cEjuvCMo8RHLBI9kM,day,[https://i.scdn.co/image/ab67616d0000b27396f40...,,TWICE,"[4Y0chGCyYIRpdUqHJjndF7, 2Ij1NaPpsFSKJ0M65tSV4...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
6,5KsduuDNWzt65TaHzmtciv,MORE & MORE,2020-06-01,7,Republic Records - TWICE,54,album,https://open.spotify.com/album/5KsduuDNWzt65Ta...,spotify:album:5KsduuDNWzt65TaHzmtciv,day,[https://i.scdn.co/image/ab67616d0000b27324869...,,TWICE,"[3omvXShuRPM3zbDpWYqf5g, 128rj96Z6tTEU3h3awSMd...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
7,20Bf2RVERC5Bc2eo3vyvJv,Persona 3 Reload Original Soundtrack,2024-04-24,62,ATLUS GAME MUSIC,71,album,https://open.spotify.com/album/20Bf2RVERC5Bc2e...,spotify:album:20Bf2RVERC5Bc2eo3vyvJv,day,[https://i.scdn.co/image/ab67616d0000b273e59bd...,,"アトラスサウンドチーム, ATLUS GAME MUSIC","[3Jl2LQmRwbXEF2lO1RTvxn, 1d5r3NM4fqH8po53LkMzB...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
8,25VunQEW0x2W6ALND2Mh4g,YES or YES,2018-11-05,7,Republic Records - TWICE,58,album,https://open.spotify.com/album/25VunQEW0x2W6AL...,spotify:album:25VunQEW0x2W6ALND2Mh4g,day,[https://i.scdn.co/image/ab67616d0000b273140ba...,,TWICE,"[26OVhEqFDQH0Ij77QtmGP9, 7fEMfYZnjQ28Cpzi7QnkA...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
9,6bj1lsHiVqvJyqjv7qtrV4,"""good guy""",2023-04-21,1,Against the Current,36,single,https://open.spotify.com/album/6bj1lsHiVqvJyqj...,spotify:album:6bj1lsHiVqvJyqjv7qtrV4,day,[https://i.scdn.co/image/ab67616d0000b2737d61e...,,Against The Current,[3bfElZNhtvtGvWMVgCBgZK],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
10,08CvAj58nVMpq1Nw7T6maj,The Winning,2024-02-20,5,EDAM Entertainment,55,single,https://open.spotify.com/album/08CvAj58nVMpq1N...,spotify:album:08CvAj58nVMpq1Nw7T6maj,day,[https://i.scdn.co/image/ab67616d0000b2735048e...,,IU,"[1c6kkrWnpy68eYDfBdxNtF, 0UTtK6hregIBOsefavRI2...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
11,0wqjfojWuTcbEvwaizvTMw,IM NAYEON,2022-06-24,7,Republic Records – NAYEON (TWICE),64,album,https://open.spotify.com/album/0wqjfojWuTcbEvw...,spotify:album:0wqjfojWuTcbEvwaizvTMw,day,[https://i.scdn.co/image/ab67616d0000b2735fb4a...,,NAYEON,"[3lOMJTQTd6J34faYwASc33, 4zHvWi4iFAG45lgiN7smL...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
12,4QjNVlIw8Rx6jItSZtn2VS,青のすみか,2023-07-07,1,Sony Music Labels Inc.,61,single,https://open.spotify.com/album/4QjNVlIw8Rx6jIt...,spotify:album:4QjNVlIw8Rx6jItSZtn2VS,day,[https://i.scdn.co/image/ab67616d0000b273e9ce7...,,Tatsuya Kitani,[12usPU2WnqgCHAW1EK2dfd],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
13,2xfq9tUp4QOlCGT6j4k0g9,CASANOVA POSSE,2025-01-10,1,Sony Music Labels Inc.,54,single,https://open.spotify.com/album/2xfq9tUp4QOlCGT...,spotify:album:2xfq9tUp4QOlCGT6j4k0g9,day,[https://i.scdn.co/image/ab67616d0000b2733fc87...,,ALI,[26Lip4WX1oWceF9tb8m2qw],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
14,3NZ94nQbqimcu2i71qhc4f,BETWEEN 1&2,2022-08-26,7,Republic Records - TWICE,61,album,https://open.spotify.com/album/3NZ94nQbqimcu2i...,spotify:album:3NZ94nQbqimcu2i71qhc4f,day,[https://i.scdn.co/image/ab67616d0000b273c3040...,,TWICE,"[0RDqNCRBGrSegk16Avfzuq, 3sOEVB8DirQtZc0qhw8lJ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
15,17rk8h2IU4wwSFXw9j2uR6,Perfect World,2021-07-28,10,WM Japan,54,album,https://open.spotify.com/album/17rk8h2IU4wwSFX...,spotify:album:17rk8h2IU4wwSFXw9j2uR6,day,[https://i.scdn.co/image/ab67616d0000b273579e9...,,TWICE,"[0iuZMy88H6vxDA2oaJNhJg, 1Wrn6btrungVsBjyViLnu...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
16,4O53dhmIctih3p2suAAgga,晴る,2024-01-05,1,Universal Music LLC,63,single,https://open.spotify.com/album/4O53dhmIctih3p2...,spotify:album:4O53dhmIctih3p2suAAgga,day,[https://i.scdn.co/image/ab67616d0000b2735e763...,,ヨルシカ,[5eY7692tmgHB9dbmq6wa2M],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
17,5AEDGbliTTfjOB8TSm1sxt,Speak Now (Taylor's Version),2023-07-07,22,Taylor Swift,81,album,https://open.spotify.com/album/5AEDGbliTTfjOB8...,spotify:album:5AEDGbliTTfjOB8TSm1sxt,day,[https://i.scdn.co/image/ab67616d0000b2730b04d...,,Taylor Swift,"[7G0gBu6nLdhFDPRLc0HdDG, 3MytWN8L7shNYzGl4tAKR...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
18,5WzUVTkKAvOayPui3DnsDz,I SWAY,2024-07-08,4,Cube Entertainment,53,single,https://open.spotify.com/album/5WzUVTkKAvOayPu...,spotify:album:5WzUVTkKAvOayPui3DnsDz,day,[https://i.scdn.co/image/ab67616d0000b27366f7b...,,(G)I-DLE,"[0d2ykpjGQwxSw7huc3l7vw, 2QcT3mwErl92KduUArSxZ...",[]
19,3u0ggfmK0vjuHMNdUbtaa9,ANTIFRAGILE,2022-10-17,5,SOURCE MUSIC,64,single,https://open.spotify.com/album/3u0ggfmK0vjuHMN...,spotify:album:3u0ggfmK0vjuHMNdUbtaa9,day,[https://i.scdn.co/image/ab67616d0000b273a9919...,,LE SSERAFIM,"[0JosgxxZKZ87QbW5TISJDE, 4fsQ0K37TOXa3hEQfjEic...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
20,575TQDOQqc0MAheeEeKWUR,With YOU-th,2024-02-23,6,Republic Records - TWICE,59,single,https://open.spotify.com/album/575TQDOQqc0MAhe...,spotify:album:575TQDOQqc0MAheeEeKWUR,day,[https://i.scdn.co/image/ab67616d0000b273bd8c7...,,TWICE,"[0mgveJEIGjcN51w4JIQtI6, 7cIn67LEvk16v6komC8zn...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
21,3gHhPm8z8tid1kvpniUKuK,Armageddon - The 1st Album,2024-05-27,10,SM Entertainment,68,album,https://open.spotify.com/album/3gHhPm8z8tid1kv...,spotify:album:3gHhPm8z8tid1kvpniUKuK,day,[https://i.scdn.co/image/ab67616d0000b2730fc59...,,aespa,"[2VdSktBqFfkW7y6q5Ik4Z4, 5eWcGfUCrVFMoYskyfkEP...","[AG, BB, BG, BS, DM, DO, GD, HK, HT, ID, IL, J..."
22,4CRfobFgSG0GOzplgTI79s,GOLD,2024-10-15,11,Republic Records - ITZY,61,album,https://open.spotify.com/album/4CRfobFgSG0GOzp...,spotify:album:4CRfobFgSG0GOzplgTI79s,day,[https://i.scdn.co/image/ab67616d0000b273dd734...,,ITZY,"[1dqN2j0jL4qB72CNgCdQ09, 06BeeZaS4YArThfTMu80Q...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
23,6sJnzoRI9pXUo0gZxIviUS,AIR,2025-03-10,4,Republic Records – YEJI (ITZY),67,single,https://open.spotify.com/album/6sJnzoRI9pXUo0g...,spotify:album:6sJnzoRI9pXUo0gZxIviUS,day,[https://i.scdn.co/image/ab67616d0000b27338d7a...,,YEJI,"[6HSns0qPQQfgekCrBF0Dkf, 5xOUBAvwWYyuPmej4iRcV...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
24,3sbZ4PoHTIZL8bLSLwt84h,HER,2025-01-21,7,Cube Entertainment,63,single,https://open.spotify.com/album/3sbZ4PoHTIZL8bL...,spotify:album:3sbZ4PoHTIZL8bLSLwt84h,day,[https://i.scdn.co/image/ab67616d0000b2735b264...,,MINNIE,"[4wqyCBpp9zwtpSehLRciXT, 6XtNw289lraKPESASgB5H...",[]
25,0pqrWNxpcWBvR9A5A9JHHl,七号線ロストボーイズ,2022-04-13,11,Sony Music Labels Inc.,41,album,https://open.spotify.com/album/0pqrWNxpcWBvR9A...,spotify:album:0pqrWNxpcWBvR9A5A9JHHl,day,[https://i.scdn.co/image/ab67616d0000b2730262e...,,amazarashi,"[4g5yln7dtUaWz2bhD7s3Lp, 6C7rH9snYqVLTeFkmXv0g...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
26,530vXGXkG5czn3hHdMPSMD,"SONG FROM TV SERIES ""RE:ZERO -STARTING LIFE IN...",2024-11-14,8,KADOKAWA,27,compilation,https://open.spotify.com/album/530vXGXkG5czn3h...,spotify:album:530vXGXkG5czn3hHdMPSMD,day,[https://i.scdn.co/image/ab67616d0000b2730dc35...,,Various Artists,"[25j7bzRhgwL29jfgReVFdy, 1aXQG0fOcIHIjPIpDLIl4...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
27,00vb6sViDbJLmLLchfbRh4,Taste of Love,2021-06-11,6,Republic Records - TWICE,57,single,https://open.spotify.com/album/00vb6sViDbJLmLL...,spotify:album:00vb6sViDbJLmLLchfbRh4,day,[https://i.scdn.co/image/ab67616d0000b273feede...,,TWICE,"[0BTaaKT4RMbs5M73tOHX5Y, 3YdqewCLgGsFhruA3EhIL...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
28,7tgTOUXm74GKA12wsQIUPu,DIVE,2024-07-17,10,WM Japan,54,album,https://open.spotify.com/album/7tgTOUXm74GKA12...,spotify:album:7tgTOUXm74GKA12wsQIUPu,day,[https://i.scdn.co/image/ab67616d0000b273c1486...,,TWICE,"[27f7ZEBoJIJ3HzOpzqmDqO, 3JstVDAZKy4O8SZ5yoXdQ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
29,2YSlIS6gM38w7ZJNj8F3s6,Sunshine,2021-11-10,1,Mosley Music/Interscope Records,63,single,https://open.spotify.com/album/2YSlIS6gM38w7ZJ...,spotify:album:2YSlIS6gM38w7ZJNj8F3s6,day,[https://i.scdn.co/image/ab67616d0000b2733b248...,,OneRepublic,[5r43qanLhUCdBj8HN3fa6B],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
30,3NQBPabmRm3LzVcmtkTLfo,Feel Special,2019-09-23,7,Republic Records - TWICE,61,album,https://open.spotify.com/album/3NQBPabmRm3LzVc...,spotify:album:3NQBPabmRm3LzVcmtkTLfo,day,[https://i.scdn.co/image/ab67616d0000b273a6b5e...,,TWICE,"[3Hz3tTQwOdM6XkA0ALB2G9, 6uy9lTlZ3xaMYQPk6eaJa...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
31,7hF6oiU4zaIQIGjLhje1eG,Hare Hare,2023-05-31,4,WM Japan,41,single,https://open.spotify.com/album/7hF6oiU4zaIQIGj...,spotify:album:7hF6oiU4zaIQIGjLhje1eG,day,[https://i.scdn.co/image/ab67616d0000b27386220...,,TWICE,"[3QcJghvqRS17RoPPP0C2sp, 2MbxU95EQZbdRo0biiC6M...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
32,7hzP5i7StxYG4StECA0rrJ,READY TO BE,2023-03-10,7,Republic Records - TWICE,60,album,https://open.spotify.com/album/7hzP5i7StxYG4St...,spotify:album:7hzP5i7StxYG4StECA0rrJ,day,[https://i.scdn.co/image/ab67616d0000b27359f57...,,TWICE,"[4OtVQ2ZxS7yigIjGz5yKg1, 5IN9W6eUfk3014My9awag...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
33,0C8qSTYZDkVcfnY6tIHIzK,Wife,2024-01-21,1,Cube Entertainment,44,single,https://open.spotify.com/album/0C8qSTYZDkVcfnY...,spotify:album:0C8qSTYZDkVcfnY6tIHIzK,day,[https://i.scdn.co/image/ab67616d0000b27320f99...,,(G)I-DLE,[326PEjfqveu646UhjHrth9],[]
34,149BHv6qAyMgJ483vPi77C,Last Fantasy,2011-11-29,13,Kakao Entertainment,45,album,https://open.spotify.com/album/149BHv6qAyMgJ48...,spotify:album:149BHv6qAyMgJ483vPi77C,day,[https://i.scdn.co/image/ab67616d0000b273bf5f4...,,IU,"[38HJ2NhRdr68S1UAi9r3vc, 79PkC8ii2W7Grvvkqazgf...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
35,3hJXmK5gWN9P6jtZL0Lr2y,Twicetagram,2017-10-30,13,Republic Records - TWICE,61,album,https://open.spotify.com/album/3hJXmK5gWN9P6jt...,spotify:album:3hJXmK5gWN9P6jtZL0Lr2y,day,[https://i.scdn.co/image/ab67616d0000b2736034e...,,TWICE,"[0IEVKWduAaMcZepZQVr80T, 1LQtxz9fIrZskoqDSbhKd...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
36,3OaW4df1SA62k0arNpn6bK,Whiplash - The 5th Mini Album,2024-10-21,6,SM Entertainment,67,single,https://open.spotify.com/album/3OaW4df1SA62k0a...,spotify:album:3OaW4df1SA62k0arNpn6bK,day,[https://i.scdn.co/image/ab67616d0000b273e467a...,,aespa,"[6uPnrBgweGOcwjFL4ItAvV, 7dYEUpcXJLDcI22m0dgmn...","[AG, BB, BG, BS, DM, DO, GD, HK, HT, ID, IL, J..."
37,5zQI9dFbS9TrhvC9clgjz7,NA,2024-06-14,7,Republic Records – NAYEON (TWICE),63,album,https://open.spotify.com/album/5zQI9dFbS9TrhvC...,spotify:album:5zQI9dFbS9TrhvC9clgjz7,day,[https://i.scdn.co/image/ab67616d0000b27373f05...,,NAYEON,"[0V2passWyAXnON67kfAj7y, 07W0lOkOUhVhdJQ9wVepW...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
38,1GIkapvyAw5lwdNw66hI44,ZONE,2023-08-18,7,Republic Records – JIHYO (TWICE),58,album,https://open.spotify.com/album/1GIkapvyAw5lwdN...,spotify:album:1GIkapvyAw5lwdNw66hI44,day,[https://i.scdn.co/image/ab67616d0000b27392b61...,,JIHYO,"[4Cyf87ul1le0xTWRFBoYd7, 28mFFxAwJ9cx9j7z9yu64...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
39,6FLiJ4318RtpA5lYWJt2cL,NEMONEMO,2024-09-30,3,"Genie Music Corporation, Stone Music Entertain...",56,single,https://open.spotify.com/album/6FLiJ4318RtpA5l...,spotify:album:6FLiJ4318RtpA5lYWJt2cL,day,[https://i.scdn.co/image/ab67616d0000b27376bc3...,,YENA,"[4UwsXGVppRRJpKBHy0mtyK, 1T3HuFlijT5Uu4pZI60tg...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
40,1TCiADBOmKJgdxULZPrK2a,Bad Girls EP,2015-07-24,4,Columbia/M2V,46,single,https://open.spotify.com/album/1TCiADBOmKJgdxU...,spotify:album:1TCiADBOmKJgdxULZPrK2a,day,[https://i.scdn.co/image/ab67616d0000b273acba4...,,MKTO,"[1x4L0kuqFaIdOYENE3I7xK, 5UtRpIn3CP97VYVTSoTUU...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."