# Load Data

In [1]:
import pandas as pd
import numpy as np
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
import os
from pathlib import Path

# Extract credential access Spotify API

In [2]:
env_path = Path("..") / ".env"
load_dotenv(dotenv_path=env_path)
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")
REDIRECT_URI = os.getenv("REDIRECT_URI")

# Extract Spotify data

## Helper Functions

In [ ]:
def extract_top_tracks_data(spotify_client,time_range)->pd.DataFrame:
    '''
    Convert JSON file extracted from spotify 
    to dataframe for analysis
    '''
    top_tracks_json = spotify_client.current_user_top_tracks(limit=50, time_range=time_range)
    track_list = []

    for item in top_tracks_json['items']:
        track_info = {
            'track_name':item['name'],
            'artist_name': item['artists'][0]['name'],
            'album_name': item['album']['name'],
            'release_date': item['album']['release_date'],
            'popularity': item['popularity'],
            'duration_ms': item['duration_ms'],
            'explicit':item['explicit'],
            'track_id': item['id']
        }
        track_list.append(track_info)
    
    data = pd.DataFrame(track_list)
    data['duration_min'] = data['duration_ms']/60000
    data['release_date'] = pd.to_datetime(data['release_date'])

    return data

def extract_top_artist_data(spotify_client,time_range)->pd.DataFrame:
    '''
    Convert JSON file extracted from Spotify
    to dataframe for analysis
    '''
    top_artist_json = spotify_client.current_user_top_artists(limit = 50,time_range = time_range)
    artist_list = []
    for item in top_artist_json['items']:
        print(item)
        artist_info = {
            'artist_name':item['name'],
            'popularity':item['popularity'],
            'genres': ', '.join(item['genres']),
            'artist_id':item['id']
        }
        artist_list.append(artist_info)
    
    data = pd.DataFrame(artist_list)
    return data

# Fetch Top Tracks

In [4]:
# Optional: remove existing cache for fresh login
if os.path.exists(".cache-my-music-app"):
    os.remove(".cache-my-music-app")

# Create the OAuth object
sp_oauth = SpotifyOAuth(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    redirect_uri=REDIRECT_URI,
    scope=["user-top-read", "user-library-read", "playlist-read-private"],
    cache_path=".cache-my-music-app"
)

# Create the Spotify client using the SpotifyOAuth instance directly
sp = spotipy.Spotify(auth_manager=sp_oauth)

# Test API call
try:
    results = sp.current_user_top_tracks(limit=10)
    for idx, item in enumerate(results['items']):
        print(f"{idx+1}. {item['name']} - {item['artists'][0]['name']}")
except spotipy.exceptions.SpotifyException as e:
    print(f"Error: {e}")

print("Fetching your top tracks...")
top_tracks = sp.current_user_top_tracks(
    limit=50, time_range='medium_term'
    )

short_term_track_data = extract_top_tracks_data(sp,'short_term')
medium_term_track_data = extract_top_tracks_data(sp,'medium_term')
long_term_track_data = extract_top_tracks_data(sp,'long_term')

1. CASANOVA POSSE - ALI
2. HER - MINNIE
3. Imaginary Friend - ITZY
4. Air - YEJI
5. I TRUST YOU - エミリア(CV:高橋李依)
6. Shopper - IU
7. Secret - IU
8. Whiplash - aespa
9. FREAK - YUQI
10. NEMONEMO - YENA
Fetching your top tracks...

In [5]:
long_term_track_data

,track_name,artist_name,album_name,release_date,popularity,duration_ms,explicit,track_id,duration_min
0,Nobody - from Kaiju No. 8,OneRepublic,Nobody (from Kaiju No. 8),2024-04-12,70,153626,False,47N81NMkB488fuOwOC3Oip,2.560433
1,I GOT YOU,TWICE,I GOT YOU,2024-02-02,59,173240,False,35dhwUoJNlxrPyEIJkfDnx,2.887333
2,FREAK,YUQI,YUQ1,2024-04-23,57,171080,False,6ERs9uORCo1MfV0m9ixCuv,2.851333
3,DIVE,TWICE,DIVE,2024-07-10,57,181860,False,5vK3WrTOp6rEoASx1jAsp1,3.031000
4,Fate,(G)I-DLE,2,2024-01-29,62,161546,False,2vNPGH1x5ZwxTjlvzLCyc2,2.692433
5,Doughnut,TWICE,Celebrate,2022-07-27,53,263680,False,65rmgd5uMb4Rgqb5dSiU0p,4.394667
6,MORE & MORE,TWICE,MORE & MORE,2020-06-01,63,199653,False,3omvXShuRPM3zbDpWYqf5g,3.327550
7,Red Rover,YUQI,YUQ1,2024-04-23,48,123320,False,4TQBHR8LcbBUv0LvLmn54H,2.055333
8,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550
9,YES or YES,TWICE,YES or YES,2018-11-05,68,237680,False,26OVhEqFDQH0Ij77QtmGP9,3.961333
10,"""good guy""",Against The Current,"""good guy""",2023-04-21,48,208052,True,3bfElZNhtvtGvWMVgCBgZK,3.467533
11,Shopper,IU,The Winning,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333
12,POP!,NAYEON,IM NAYEON,2022-06-24,72,168106,False,3lOMJTQTd6J34faYwASc33,2.801767
13,青のすみか,Tatsuya Kitani,青のすみか,2023-07-07,72,196466,False,12usPU2WnqgCHAW1EK2dfd,3.274433
14,CASANOVA POSSE,ALI,CASANOVA POSSE,2025-01-10,65,240653,False,26Lip4WX1oWceF9tb8m2qw,4.010883
15,Talk that Talk,TWICE,BETWEEN 1&2,2022-08-26,69,177466,False,0RDqNCRBGrSegk16Avfzuq,2.957767
16,Perfect World,TWICE,Perfect World,2021-07-28,58,182680,False,0iuZMy88H6vxDA2oaJNhJg,3.044667
17,晴る,ヨルシカ,晴る,2024-01-05,74,270705,False,5eY7692tmgHB9dbmq6wa2M,4.511750
18,Super Lady,(G)I-DLE,2,2024-01-29,64,152186,False,5qI5EUqfDJpQ7w6sMECK7U,2.536433
19,Long Live (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),2023-07-07,73,317960,False,4hqJ4bSlYJOXb6Z4SRmzxs,5.299333
20,Klaxon,(G)I-DLE,I SWAY,2024-07-08,63,175106,False,294hRgOqnGW2BemqP8D35X,2.918433
21,No Celestial,LE SSERAFIM,ANTIFRAGILE,2022-10-17,60,166491,False,21ApmVGIzIAIDSBdHu6SVt,2.774850
22,ONE SPARK,TWICE,With YOU-th,2024-02-23,67,183559,False,7cIn67LEvk16v6komC8znS,3.059317
23,Live My Life,aespa,Armageddon - The 1st Album,2024-05-27,63,159133,False,1x1oCGsFUDViOvcISuoKW0,2.652217
24,Imaginary Friend,ITZY,GOLD,2024-10-15,66,202429,False,06BeeZaS4YArThfTMu80QS,3.373817
25,Air,YEJI,AIR,2025-03-10,75,194800,False,6HSns0qPQQfgekCrBF0Dkf,3.246667
26,HER,MINNIE,HER,2025-01-21,69,159797,False,2MbPhDgeXVipowltFneRH2,2.663283
27,境界線,amazarashi,七号線ロストボーイズ,2022-04-13,48,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550
28,I TRUST YOU,エミリア(CV:高橋李依),"SONG FROM TV SERIES ""RE:ZERO -STARTING LIFE IN...",2024-11-14,34,255396,False,7Ccvd3UVSfORSNyeOO069h,4.256600
29,Alcohol-Free,TWICE,Taste of Love,2021-06-11,66,210573,False,0BTaaKT4RMbs5M73tOHX5Y,3.509550
30,Beyond the Horizon,TWICE,DIVE,2024-07-17,47,212826,False,27f7ZEBoJIJ3HzOpzqmDqO,3.547100
31,Ocean Deep,TWICE,DIVE,2024-07-17,47,220106,False,6jya1u1sEhObLCDFGyWuAW,3.668433
32,Sunshine,OneRepublic,Sunshine,2021-11-10,74,163854,False,5r43qanLhUCdBj8HN3fa6B,2.730900
33,LOVE FOOLISH,TWICE,Feel Special,2019-09-23,53,191226,False,1MdEg2lk4EakgWnCvFUGEZ,3.187100
34,DIVE,TWICE,DIVE,2024-07-17,57,181860,False,3JstVDAZKy4O8SZ5yoXdQr,3.031000
35,Feel Special,TWICE,Feel Special,2019-09-23,71,206866,False,3Hz3tTQwOdM6XkA0ALB2G9,3.447767
36,Hare Hare,TWICE,Hare Hare,2023-05-31,46,203546,False,3QcJghvqRS17RoPPP0C2sp,3.392433
37,MOONLIGHT SUNRISE,TWICE,READY TO BE,2023-03-10,61,180320,False,5IN9W6eUfk3014My9awagX,3.005333
38,Baby Blue Love,TWICE,Taste of Love,2021-06-11,50,166666,False,7Jzo3IObpANz6giPTUrihB,2.777767
39,Wife,(G)I-DLE,Wife,2024-01-21,56,121226,False,6hWU8LrnjLyYHShDyNWFZj,2.020433
40,Secret,IU,Last Fantasy,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867
41,Likey,TWICE,Twicetagram,2017-10-30,66,207813,False,0IEVKWduAaMcZepZQVr80T,3.463550
42,Mine (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),2023-07-07,74,231706,False,7G0gBu6nLdhFDPRLc0HdDG,3.861767
43,Whiplash,aespa,Whiplash - The 5th Mini Album,2024-10-21,78,183226,False,6uPnrBgweGOcwjFL4ItAvV,3.053767
44,I GOT YOU,TWICE,With YOU-th,2024-02-23,54,173240,False,0mgveJEIGjcN51w4JIQtI6,2.887333
45,ABCD,NAYEON,NA,2024-06-14,72,162840,False,0V2passWyAXnON67kfAj7y,2.714000
46,Wife,(G)I-DLE,2,2024-01-29,60,121226,False,1j8jqwFpFQ8YqsIJAiYFLZ,2.020433
47,Killin’ Me Good,JIHYO,ZONE,2023-08-18,64,185920,False,4Cyf87ul1le0xTWRFBoYd7,3.098667
48,NEMONEMO,YENA,NEMONEMO,2024-09-30,67,178026,False,4UwsXGVppRRJpKBHy0mtyK,2.967100
49,Just Imagine It,MKTO,Bad Girls EP,2015-07-24,50,250746,False,0mtmrbRFsectINNpHdDkUQ,4.179100

In [6]:
short_term_track_data

,track_name,artist_name,album_name,release_date,popularity,duration_ms,explicit,track_id,duration_min
0,Air,YEJI,Air,2025-03-10,55,194800,False,2HhIndg75YiKjuUgGiMjSA,3.246667
1,Draw the Moon (feat. MIYAVI),MINNIE,"Webtoon <Myst, Might, Mayhem> OST Part. 2 Draw...",2025-03-21,45,210146,False,4B3JCEcAeTofpsfsEianeS,3.502433
2,Radio (Dum-Dum),YUQI,Radio (Dum-Dum),2025-03-17,67,152373,False,0mXXjVVAhaasNXga2HMgJK,2.539550
3,I,TAEYEON,I - The 1st Mini Album,2015-10-07,61,206038,False,5ZkITfPpcNPnyYGTibkO6m,3.433967
4,Invasion,YEJI,Air,2025-03-10,40,167800,False,3ePablAj7jk2c1j5CKEtAv,2.796667
5,HAPPY,DAY6,Fourever,2024-03-18,64,189934,False,1k68vKHNQXU5CHqcM7Yp7N,3.165567
6,"Can’t Slow Me, No",YEJI,Air,2025-03-10,38,178573,False,7EbaA7z7wP3G7xfYZVlVJS,2.976217
7,Shopper,IU,The Winning,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333
8,SMILEY-Japanese Ver.- (feat.ちゃんみな),YENA,SMILEY-Japanese Ver.- (feat.ちゃんみな),2023-08-07,39,176882,False,4RhkH4fGvvEzxvRlUcYH9L,2.948033
9,NEMONEMO,YENA,NEMONEMO,2024-09-30,67,178026,False,4UwsXGVppRRJpKBHy0mtyK,2.967100
10,Lxxk 2 U,YENA,ˣ‿ˣ (SMiLEY),2022-01-17,43,182853,False,5U7emXCoCl8EOEJUVNbguC,3.047550
11,Supernova,aespa,Armageddon - The 1st Album,2024-05-27,64,178880,False,2JhbSmNAyM9kYiqwa8Tpla,2.981333
12,FOREVER,BABYMONSTER,DRIP,2024-11-01,62,212734,False,7a6vvAM1cjAuyVQpqv9pmu,3.545567
13,Autumn morning,IU,가을 아침 [Gaeul Achim] : Autumn morning,2017-09-22,49,218884,False,100N8P8WYnz9eCYuLYGflV,3.648067
14,Secret,IU,Last Fantasy,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867
15,Whiplash,aespa,Whiplash - The 5th Mini Album,2024-10-21,73,183226,False,7Cnpb1vBbC46RgVyyKLH7p,3.053767
16,HER,MINNIE,HER,2025-01-21,45,159797,False,1Jm2piFQ1Nq3fGHwu3fyvT,2.663283
17,ひたむき,SUPER BEAVER,音楽,2024-02-21,50,246800,False,4Jp91ygcS0CBz8MwtvoBrU,4.113333
18,Well… (ROCK VER.),IU,Growing Up,2009-04-23,39,190589,False,6zpiGeoHYRF5vtrboE3rAC,3.176483
19,Live My Life,aespa,Armageddon - The 1st Album,2024-05-27,58,159133,False,71lnolmea3IZeG90Gj7jHg,2.652217
20,WithOrWithOut,YENA,SMARTPHONE,2022-08-03,34,191973,False,5tazcUyCvfGdRWC1Da5rCS,3.199550
21,Obsession (feat. TEN),MINNIE,HER,2025-01-21,27,222541,False,6sEqkiXe4vRNIhOvNdZzL1,3.709017
22,My Stupid Heart (with Lauv),Walk off the Earth,My Stupid Heart (with Lauv),2023-03-03,52,160866,False,1SVOLTmC627fn0XY9ltvx2,2.681100
23,BAHAMA,aespa,Armageddon - The 1st Album,2024-05-27,44,190533,False,1FXNYp47arDhsngAsHSG9v,3.175550
24,境界線,amazarashi,七号線ロストボーイズ,2022-04-13,48,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550
25,Hate Rodrigo (Feat. YUQI),YENA,HATE XX,2023-06-27,54,181013,False,5ms7rcVKjBFUtoVh8hE0Y9,3.016883
26,Letter To Myself,TAEYEON,Letter To Myself - The 6th Mini Album,2024-11-18,63,184060,False,1Uxr0oBXAZRuLkAz27TkLc,3.067667
27,REBEL HEART,IVE,REBEL HEART,2025-01-13,66,188266,False,1jtlHteF4y7FFHKgYFld4f,3.137767
28,I Don't Wanna Wait,David Guetta,I Don't Wanna Wait,2024-04-05,85,149667,False,331l3xABO0HMr1Kkyh2LZq,2.494450
29,PINK YOUR MOMENT,MINNIE,PINK YOUR MOMENT,2023-04-26,16,131306,False,3CH6RNIVix2lZp9awUfOSQ,2.188433
30,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550
31,Getaway,MINNIE,"My Dangerous Wife, Pt. 2 (Original Television ...",2020-10-11,34,228080,False,41nBWFdECOtxYnygCpL6AH,3.801333
32,This Is The New Shit,Marilyn Manson,The Golden Age Of Grotesque,2003-01-01,63,259666,True,5P13mfqn9o3ToFPTxowEgO,4.327767
33,LEveL,SawanoHiroyuki[nZk],bLACKbLUE,2024-10-02,54,182653,False,5hakB3OS30xHJsWq6mqty7,3.044217
34,Into the Unknown (End Credit Version),TAEYEON,Frozen 2 (Korean Original Motion Picture Sound...,2019-11-15,40,189120,False,4OkHootAlj7w9Eb2zJVlWr,3.152000
35,APT.,ROSÉ,rosie,2024-12-06,92,169917,False,4wJ5Qq0jBN4ajy7ouZIV1c,2.831950
36,258,YEJI,Air,2025-03-10,41,193040,False,6jZP2gYURZhXxh45vMAliR,3.217333
37,造浪 - 《我要逆风去》电视剧主题曲,YUQI,造浪 (《我要逆风去》电视剧主题曲),2024-06-25,36,188307,False,0tNwt2ZBNkelLrLnZqOC2H,3.138450
38,Sugar,YENA,NEMONEMO,2024-09-30,49,166653,False,1T3HuFlijT5Uu4pZI60tgr,2.777550
39,50 Ways to Say Goodbye,Train,California 37,2012-04-17,70,247946,False,2NniAhAtkRACaMeYt48xlD,4.132433
40,SMILEY(Feat. BIBI),YENA,ˣ‿ˣ (SMiLEY),2022-01-17,60,173413,False,4zCIxSnVWpGNghERX4uWZF,2.890217
41,KIDDING ME,ITZY,GUESS WHO,2021-04-30,24,213960,False,1muZkKwVHfv8hS77RG2G2I,3.566000
42,Nobody - from Kaiju No. 8,OneRepublic,Artificial Paradise (Deluxe),2024-07-12,63,153626,False,3SiVMpHxTS1gspWzRZE50S,2.560433
43,My Universe,Coldplay,Music Of The Spheres,2021-10-15,77,226198,False,46HNZY1i7O6jwTA7Slo2PI,3.769967
44,UP - KARINA Solo,aespa,SYNK : PARALLEL LINE - Special Digital Single,2024-10-09,80,166640,False,5sjnkOfTLCLNfkkchI2re2,2.777333
45,Your Love,JISOO,AMORTAGE,2025-02-14,78,173232,False,6TPpCbn9z0IY5Te048iy5R,2.887200
46,Armageddon,aespa,Armageddon - The 1st Album,2024-05-27,61,196466,False,6lAvyeD3Nq43AjyCxZQj54,3.274433
47,Rum Pum Pum Pum,aespa,"2025 SMTOWN : THE CULTURE, THE FUTURE",2025-02-14,61,209613,False,00M2YcEqhsVbSW6RUKqIY3,3.493550
48,spiral,LONGMAN,10/4,2023-10-04,45,231746,False,18Y6TCF80HYi0Fu53xcUge,3.862433
49,BAD HOBBY,YENA,HATE XX,2023-06-27,41,131013,False,4XGOlD2OFGPHXLA0DBPr5M,2.183550

# Fetch Top Artist

In [7]:
extract_top_artist_data(sp,'short_term')

{'items': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6YVMFz59CuY7ngCxTxjpxE'}, 'followers': {'href': None, 'total': 8355136}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/6YVMFz59CuY7ngCxTxjpxE', 'id': '6YVMFz59CuY7ngCxTxjpxE', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebf7a1090ad3a35a34fc0ecb57', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174f7a1090ad3a35a34fc0ecb57', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178f7a1090ad3a35a34fc0ecb57', 'width': 160}], 'name': 'aespa', 'popularity': 80, 'type': 'artist', 'uri': 'spotify:artist:6YVMFz59CuY7ngCxTxjpxE'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/49muoiIu4uea4PO8vueUNN'}, 'followers': {'href': None, 'total': 806960}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/49muoiIu4uea4PO8vueUNN', 'id': '49muoiIu4uea4PO8vueUNN', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb1135e17231033a9cb4ddde8e', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051741135e17231033a9cb4ddde8e', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1781135e17231033a9cb4ddde8e', 'width': 160}], 'name': 'YENA', 'popularity': 56, 'type': 'artist', 'uri': 'spotify:artist:49muoiIu4uea4PO8vueUNN'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3HqSLMAZ3g3d5poNaI7GOU'}, 'followers': {'href': None, 'total': 9133293}, 'genres': ['k-pop', 'k-ballad'], 'href': 'https://api.spotify.com/v1/artists/3HqSLMAZ3g3d5poNaI7GOU', 'id': '3HqSLMAZ3g3d5poNaI7GOU', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebbd0642ff425698afac5caffd', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174bd0642ff425698afac5caffd', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178bd0642ff425698afac5caffd', 'width': 160}], 'name': 'IU', 'popularity': 70, 'type': 'artist', 'uri': 'spotify:artist:3HqSLMAZ3g3d5poNaI7GOU'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3qNVuliS40BLgXGxhdBdqu'}, 'followers': {'href': None, 'total': 3064356}, 'genres': ['k-pop', 'k-ballad'], 'href': 'https://api.spotify.com/v1/artists/3qNVuliS40BLgXGxhdBdqu', 'id': '3qNVuliS40BLgXGxhdBdqu', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebb5d9ebbbbe3fff5a330b40c8', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174b5d9ebbbbe3fff5a330b40c8', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178b5d9ebbbbe3fff5a330b40c8', 'width': 160}], 'name': 'TAEYEON', 'popularity': 67, 'type': 'artist', 'uri': 'spotify:artist:3qNVuliS40BLgXGxhdBdqu'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2pHkxVNynHBwQHhGaoBIXX'}, 'followers': {'href': None, 'total': 760546}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2pHkxVNynHBwQHhGaoBIXX', 'id': '2pHkxVNynHBwQHhGaoBIXX', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb1a9a17af93d76f3e7cb4befa', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051741a9a17af93d76f3e7cb4befa', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1781a9a17af93d76f3e7cb4befa', 'width': 160}], 'name': 'MINNIE', 'popularity': 63, 'type': 'artist', 'uri': 'spotify:artist:2pHkxVNynHBwQHhGaoBIXX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7n2Ycct7Beij7Dj7meI4X0'}, 'followers': {'href': None, 'total': 21661915}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/7n2Ycct7Beij7Dj7meI4X0', 'id': '7n2Ycct7Beij7Dj7meI4X0', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebca6c145421fa9ceb58d6f9d4', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174ca6c145421fa9ceb58d6f9d4', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178ca6c145421fa9ceb58d6f9d4', 'width': 160}], 'name': 'TWICE', 'popularity': 79, 'type': 'artist', 'uri': 'spotify:artist:7n2Ycct7Beij7Dj7meI4X0'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2KC9Qb60EaY0kW4eH68vr3'}, 'followers': {'href': None, 'total': 8349525}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2KC9Qb60EaY0kW4eH68vr3', 'id': '2KC9Qb60EaY0kW4eH68vr3', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb3448062884d4ad30473e964b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051743448062884d4ad30473e964b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1783448062884d4ad30473e964b', 'width': 160}], 'name': 'ITZY', 'popularity': 69, 'type': 'artist', 'uri': 'spotify:artist:2KC9Qb60EaY0kW4eH68vr3'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3skli1w2n0nOZ4qkDbvV2m'}, 'followers': {'href': None, 'total': 113471}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/3skli1w2n0nOZ4qkDbvV2m', 'id': '3skli1w2n0nOZ4qkDbvV2m', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb485cfbf516f7bf8b7b479a91', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174485cfbf516f7bf8b7b479a91', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178485cfbf516f7bf8b7b479a91', 'width': 160}], 'name': 'YEJI', 'popularity': 61, 'type': 'artist', 'uri': 'spotify:artist:3skli1w2n0nOZ4qkDbvV2m'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/22aCD8IrQZjcPgZw728QT6'}, 'followers': {'href': None, 'total': 832868}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/22aCD8IrQZjcPgZw728QT6', 'id': '22aCD8IrQZjcPgZw728QT6', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb569026949c9d74d8448c6559', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174569026949c9d74d8448c6559', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178569026949c9d74d8448c6559', 'width': 160}], 'name': 'YUQI', 'popularity': 60, 'type': 'artist', 'uri': 'spotify:artist:22aCD8IrQZjcPgZw728QT6'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/28ot3wh4oNmoFOdVajibBl'}, 'followers': {'href': None, 'total': 3605836}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/28ot3wh4oNmoFOdVajibBl', 'id': '28ot3wh4oNmoFOdVajibBl', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebb75519f6b752fce04b2e4ed7', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174b75519f6b752fce04b2e4ed7', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178b75519f6b752fce04b2e4ed7', 'width': 160}], 'name': 'NMIXX', 'popularity': 71, 'type': 'artist', 'uri': 'spotify:artist:28ot3wh4oNmoFOdVajibBl'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2AfmfGFbe0A0WsTYm0SDTx'}, 'followers': {'href': None, 'total': 10487023}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2AfmfGFbe0A0WsTYm0SDTx', 'id': '2AfmfGFbe0A0WsTYm0SDTx', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb7fd16327c86d500f83be1d6a', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051747fd16327c86d500f83be1d6a', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1787fd16327c86d500f83be1d6a', 'width': 160}], 'name': '(G)I-DLE', 'popularity': 73, 'type': 'artist', 'uri': 'spotify:artist:2AfmfGFbe0A0WsTYm0SDTx'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6RHTUrRF63xao58xh9FXYJ'}, 'followers': {'href': None, 'total': 5448007}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/6RHTUrRF63xao58xh9FXYJ', 'id': '6RHTUrRF63xao58xh9FXYJ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb538dad5b42d963e338726c26', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174538dad5b42d963e338726c26', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178538dad5b42d963e338726c26', 'width': 160}], 'name': 'IVE', 'popularity': 75, 'type': 'artist', 'uri': 'spotify:artist:6RHTUrRF63xao58xh9FXYJ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2sCc8pMRgv99AweDSrFFZt'}, 'followers': {'href': None, 'total': 30465}, 'genres': ['anime', 'j-rock', 'j-pop'], 'href': 'https://api.spotify.com/v1/artists/2sCc8pMRgv99AweDSrFFZt', 'id': '2sCc8pMRgv99AweDSrFFZt', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebca92c439ed2e43f615740056', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174ca92c439ed2e43f615740056', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178ca92c439ed2e43f615740056', 'width': 160}], 'name': 'THE SIXTH LIE', 'popularity': 40, 'type': 'artist', 'uri': 'spotify:artist:2sCc8pMRgv99AweDSrFFZt'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4TEK9tIkcoxib4GxT3O4ky'}, 'followers': {'href': None, 'total': 2125025}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/4TEK9tIkcoxib4GxT3O4ky', 'id': '4TEK9tIkcoxib4GxT3O4ky', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb33a8ccf7ddd38cea1a0eac0d', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517433a8ccf7ddd38cea1a0eac0d', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17833a8ccf7ddd38cea1a0eac0d', 'width': 160}], 'name': 'KISS OF LIFE', 'popularity': 73, 'type': 'artist', 'uri': 'spotify:artist:4TEK9tIkcoxib4GxT3O4ky'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4SpbR6yFEvexJuaBpgAU5p'}, 'followers': {'href': None, 'total': 6904886}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/4SpbR6yFEvexJuaBpgAU5p', 'id': '4SpbR6yFEvexJuaBpgAU5p', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb593f35db6f6837e1047a5e33', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174593f35db6f6837e1047a5e33', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178593f35db6f6837e1047a5e33', 'width': 160}], 'name': 'LE SSERAFIM', 'popularity': 82, 'type': 'artist', 'uri': 'spotify:artist:4SpbR6yFEvexJuaBpgAU5p'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1SIocsqdEefUTE6XKGUiVS'}, 'followers': {'href': None, 'total': 4264210}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/1SIocsqdEefUTE6XKGUiVS', 'id': '1SIocsqdEefUTE6XKGUiVS', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebb419d66ef21661311c806bfe', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174b419d66ef21661311c806bfe', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178b419d66ef21661311c806bfe', 'width': 160}], 'name': 'BABYMONSTER', 'popularity': 76, 'type': 'artist', 'uri': 'spotify:artist:1SIocsqdEefUTE6XKGUiVS'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0IwZVmMMGE7nNXS7vN9SIo'}, 'followers': {'href': None, 'total': 993816}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/0IwZVmMMGE7nNXS7vN9SIo', 'id': '0IwZVmMMGE7nNXS7vN9SIo', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb8bb0411b0375cd719eac306b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051748bb0411b0375cd719eac306b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1788bb0411b0375cd719eac306b', 'width': 160}], 'name': 'MISAMO', 'popularity': 61, 'type': 'artist', 'uri': 'spotify:artist:0IwZVmMMGE7nNXS7vN9SIo'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/779v40cWIJUUoIDtC1IGaF'}, 'followers': {'href': None, 'total': 740421}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/779v40cWIJUUoIDtC1IGaF', 'id': '779v40cWIJUUoIDtC1IGaF', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb3694064077be4d5de2e1dd9d', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051743694064077be4d5de2e1dd9d', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1783694064077be4d5de2e1dd9d', 'width': 160}], 'name': 'MIYEON', 'popularity': 47, 'type': 'artist', 'uri': 'spotify:artist:779v40cWIJUUoIDtC1IGaF'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2QM5S4yO6xHgnNvF0nbZZq'}, 'followers': {'href': None, 'total': 1212276}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2QM5S4yO6xHgnNvF0nbZZq', 'id': '2QM5S4yO6xHgnNvF0nbZZq', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb09369ae372e47fdb115bcf52', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517409369ae372e47fdb115bcf52', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17809369ae372e47fdb115bcf52', 'width': 160}], 'name': 'SEULGI', 'popularity': 63, 'type': 'artist', 'uri': 'spotify:artist:2QM5S4yO6xHgnNvF0nbZZq'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6UZ0ba50XreR4TM8u322gs'}, 'followers': {'href': None, 'total': 5678914}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/6UZ0ba50XreR4TM8u322gs', 'id': '6UZ0ba50XreR4TM8u322gs', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb9e33dd3ae51452774a133e1f', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051749e33dd3ae51452774a133e1f', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1789e33dd3ae51452774a133e1f', 'width': 160}], 'name': 'JISOO', 'popularity': 74, 'type': 'artist', 'uri': 'spotify:artist:6UZ0ba50XreR4TM8u322gs'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7F1iAHRYxR3MY7yAEuFqgL'}, 'followers': {'href': None, 'total': 978773}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/7F1iAHRYxR3MY7yAEuFqgL', 'id': '7F1iAHRYxR3MY7yAEuFqgL', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb92d8ef35f578a53e177a3e13', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517492d8ef35f578a53e177a3e13', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17892d8ef35f578a53e177a3e13', 'width': 160}], 'name': 'JIHYO', 'popularity': 54, 'type': 'artist', 'uri': 'spotify:artist:7F1iAHRYxR3MY7yAEuFqgL'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4UK2Lzi6fBfUi9rpDt6cik'}, 'followers': {'href': None, 'total': 3031501}, 'genres': ['j-pop', 'j-rock', 'japanese indie', 'anime'], 'href': 'https://api.spotify.com/v1/artists/4UK2Lzi6fBfUi9rpDt6cik', 'id': '4UK2Lzi6fBfUi9rpDt6cik', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebe62cff9c6018ae5616b01eab', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174e62cff9c6018ae5616b01eab', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178e62cff9c6018ae5616b01eab', 'width': 160}], 'name': 'ヨルシカ', 'popularity': 74, 'type': 'artist', 'uri': 'spotify:artist:4UK2Lzi6fBfUi9rpDt6cik'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0kB3Vlf3xDNZQz6NjAPJV8'}, 'followers': {'href': None, 'total': 431644}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/0kB3Vlf3xDNZQz6NjAPJV8', 'id': '0kB3Vlf3xDNZQz6NjAPJV8', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebc013b5c52bcfb6a022ac79fa', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174c013b5c52bcfb6a022ac79fa', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178c013b5c52bcfb6a022ac79fa', 'width': 160}], 'name': 'SOOJIN', 'popularity': 43, 'type': 'artist', 'uri': 'spotify:artist:0kB3Vlf3xDNZQz6NjAPJV8'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3Q5Qep7ytrjVleNnMnntgQ'}, 'followers': {'href': None, 'total': 842910}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/3Q5Qep7ytrjVleNnMnntgQ', 'id': '3Q5Qep7ytrjVleNnMnntgQ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb8f8c7f169befa177c604e028', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051748f8c7f169befa177c604e028', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1788f8c7f169befa177c604e028', 'width': 160}], 'name': 'TEN', 'popularity': 68, 'type': 'artist', 'uri': 'spotify:artist:3Q5Qep7ytrjVleNnMnntgQ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/30b9WulBM8sFuBo17nNq9c'}, 'followers': {'href': None, 'total': 3458766}, 'genres': ['k-pop', 'k-rap'], 'href': 'https://api.spotify.com/v1/artists/30b9WulBM8sFuBo17nNq9c', 'id': '30b9WulBM8sFuBo17nNq9c', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb783a6a578e8eb992bfd74765', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174783a6a578e8eb992bfd74765', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178783a6a578e8eb992bfd74765', 'width': 160}], 'name': 'G-DRAGON', 'popularity': 76, 'type': 'artist', 'uri': 'spotify:artist:30b9WulBM8sFuBo17nNq9c'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5Pwc4xIPtQLFEnJriah9YJ'}, 'followers': {'href': None, 'total': 18133553}, 'genres': ['soft pop'], 'href': 'https://api.spotify.com/v1/artists/5Pwc4xIPtQLFEnJriah9YJ', 'id': '5Pwc4xIPtQLFEnJriah9YJ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb57138b98e7ddd5a86ee97a9b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517457138b98e7ddd5a86ee97a9b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17857138b98e7ddd5a86ee97a9b', 'width': 160}], 'name': 'OneRepublic', 'popularity': 84, 'type': 'artist', 'uri': 'spotify:artist:5Pwc4xIPtQLFEnJriah9YJ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5TnQc2N1iKlFjYD7CPGvFc'}, 'followers': {'href': None, 'total': 3669904}, 'genres': ['k-rock', 'k-pop'], 'href': 'https://api.spotify.com/v1/artists/5TnQc2N1iKlFjYD7CPGvFc', 'id': '5TnQc2N1iKlFjYD7CPGvFc', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb10e83b0ca558533d0f3c376c', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517410e83b0ca558533d0f3c376c', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17810e83b0ca558533d0f3c376c', 'width': 160}], 'name': 'DAY6', 'popularity': 69, 'type': 'artist', 'uri': 'spotify:artist:5TnQc2N1iKlFjYD7CPGvFc'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'}, 'followers': {'href': None, 'total': 119909905}, 'genres': ['soft pop'], 'href': 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V', 'id': '6eUKZXaKkcviH0Ku9w2n3V', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb399444ed4eace08b549d1161', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174399444ed4eace08b549d1161', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178399444ed4eace08b549d1161', 'width': 160}], 'name': 'Ed Sheeran', 'popularity': 89, 'type': 'artist', 'uri': 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU'}, 'followers': {'href': None, 'total': 57680795}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU', 'id': '4gzpq5DPGxSnKTe4SA8HAU', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb1ba8fc5f5c73e7e9313cc6eb', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051741ba8fc5f5c73e7e9313cc6eb', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610

,artist_name,popularity,genres,artist_id
0,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE
1,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN
2,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU
3,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu
4,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX
5,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0
6,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3
7,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m
8,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6
9,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl
10,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx
11,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ
12,THE SIXTH LIE,40,"anime, j-rock, j-pop",2sCc8pMRgv99AweDSrFFZt
13,KISS OF LIFE,73,k-pop,4TEK9tIkcoxib4GxT3O4ky
14,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p
15,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS
16,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo
17,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF
18,SEULGI,63,k-pop,2QM5S4yO6xHgnNvF0nbZZq
19,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs
20,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL
21,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik
22,SOOJIN,43,k-pop,0kB3Vlf3xDNZQz6NjAPJV8
23,TEN,68,k-pop,3Q5Qep7ytrjVleNnMnntgQ
24,G-DRAGON,76,"k-pop, k-rap",30b9WulBM8sFuBo17nNq9c
25,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ
26,DAY6,69,"k-rock, k-pop",5TnQc2N1iKlFjYD7CPGvFc
27,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V
28,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU
29,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX

In [8]:
extract_top_artist_data(sp,'long_term')

{'items': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/7n2Ycct7Beij7Dj7meI4X0'}, 'followers': {'href': None, 'total': 21661915}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/7n2Ycct7Beij7Dj7meI4X0', 'id': '7n2Ycct7Beij7Dj7meI4X0', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebca6c145421fa9ceb58d6f9d4', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174ca6c145421fa9ceb58d6f9d4', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178ca6c145421fa9ceb58d6f9d4', 'width': 160}], 'name': 'TWICE', 'popularity': 79, 'type': 'artist', 'uri': 'spotify:artist:7n2Ycct7Beij7Dj7meI4X0'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2AfmfGFbe0A0WsTYm0SDTx'}, 'followers': {'href': None, 'total': 10487023}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2AfmfGFbe0A0WsTYm0SDTx', 'id': '2AfmfGFbe0A0WsTYm0SDTx', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb7fd16327c86d500f83be1d6a', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051747fd16327c86d500f83be1d6a', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1787fd16327c86d500f83be1d6a', 'width': 160}], 'name': '(G)I-DLE', 'popularity': 73, 'type': 'artist', 'uri': 'spotify:artist:2AfmfGFbe0A0WsTYm0SDTx'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'}, 'followers': {'href': None, 'total': 119909905}, 'genres': ['soft pop'], 'href': 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V', 'id': '6eUKZXaKkcviH0Ku9w2n3V', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb399444ed4eace08b549d1161', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174399444ed4eace08b549d1161', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178399444ed4eace08b549d1161', 'width': 160}], 'name': 'Ed Sheeran', 'popularity': 89, 'type': 'artist', 'uri': 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02'}, 'followers': {'href': None, 'total': 135368184}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02', 'id': '06HL4z0CvFAxyc27GXpf02', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebe672b5f553298dcdccb0e676', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174e672b5f553298dcdccb0e676', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178e672b5f553298dcdccb0e676', 'width': 160}], 'name': 'Taylor Swift', 'popularity': 98, 'type': 'artist', 'uri': 'spotify:artist:06HL4z0CvFAxyc27GXpf02'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3HqSLMAZ3g3d5poNaI7GOU'}, 'followers': {'href': None, 'total': 9133293}, 'genres': ['k-pop', 'k-ballad'], 'href': 'https://api.spotify.com/v1/artists/3HqSLMAZ3g3d5poNaI7GOU', 'id': '3HqSLMAZ3g3d5poNaI7GOU', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebbd0642ff425698afac5caffd', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174bd0642ff425698afac5caffd', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178bd0642ff425698afac5caffd', 'width': 160}], 'name': 'IU', 'popularity': 70, 'type': 'artist', 'uri': 'spotify:artist:3HqSLMAZ3g3d5poNaI7GOU'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2KC9Qb60EaY0kW4eH68vr3'}, 'followers': {'href': None, 'total': 8349525}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2KC9Qb60EaY0kW4eH68vr3', 'id': '2KC9Qb60EaY0kW4eH68vr3', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb3448062884d4ad30473e964b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051743448062884d4ad30473e964b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1783448062884d4ad30473e964b', 'width': 160}], 'name': 'ITZY', 'popularity': 69, 'type': 'artist', 'uri': 'spotify:artist:2KC9Qb60EaY0kW4eH68vr3'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6YVMFz59CuY7ngCxTxjpxE'}, 'followers': {'href': None, 'total': 8355136}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/6YVMFz59CuY7ngCxTxjpxE', 'id': '6YVMFz59CuY7ngCxTxjpxE', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebf7a1090ad3a35a34fc0ecb57', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174f7a1090ad3a35a34fc0ecb57', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178f7a1090ad3a35a34fc0ecb57', 'width': 160}], 'name': 'aespa', 'popularity': 80, 'type': 'artist', 'uri': 'spotify:artist:6YVMFz59CuY7ngCxTxjpxE'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6yhD1KjhLxIETFF7vIRf8B'}, 'followers': {'href': None, 'total': 528861}, 'genres': ['pop punk'], 'href': 'https://api.spotify.com/v1/artists/6yhD1KjhLxIETFF7vIRf8B', 'id': '6yhD1KjhLxIETFF7vIRf8B', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb469aba515a0815396f1c432c', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174469aba515a0815396f1c432c', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178469aba515a0815396f1c432c', 'width': 160}], 'name': 'Against The Current', 'popularity': 64, 'type': 'artist', 'uri': 'spotify:artist:6yhD1KjhLxIETFF7vIRf8B'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2pHkxVNynHBwQHhGaoBIXX'}, 'followers': {'href': None, 'total': 760546}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2pHkxVNynHBwQHhGaoBIXX', 'id': '2pHkxVNynHBwQHhGaoBIXX', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb1a9a17af93d76f3e7cb4befa', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051741a9a17af93d76f3e7cb4befa', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1781a9a17af93d76f3e7cb4befa', 'width': 160}], 'name': 'MINNIE', 'popularity': 63, 'type': 'artist', 'uri': 'spotify:artist:2pHkxVNynHBwQHhGaoBIXX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6RHTUrRF63xao58xh9FXYJ'}, 'followers': {'href': None, 'total': 5448007}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/6RHTUrRF63xao58xh9FXYJ', 'id': '6RHTUrRF63xao58xh9FXYJ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb538dad5b42d963e338726c26', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174538dad5b42d963e338726c26', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178538dad5b42d963e338726c26', 'width': 160}], 'name': 'IVE', 'popularity': 75, 'type': 'artist', 'uri': 'spotify:artist:6RHTUrRF63xao58xh9FXYJ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/22aCD8IrQZjcPgZw728QT6'}, 'followers': {'href': None, 'total': 832868}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/22aCD8IrQZjcPgZw728QT6', 'id': '22aCD8IrQZjcPgZw728QT6', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb569026949c9d74d8448c6559', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174569026949c9d74d8448c6559', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178569026949c9d74d8448c6559', 'width': 160}], 'name': 'YUQI', 'popularity': 60, 'type': 'artist', 'uri': 'spotify:artist:22aCD8IrQZjcPgZw728QT6'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0Oazwl71qoHvXnbSxv0wOT'}, 'followers': {'href': None, 'total': 290718}, 'genres': ['anime', 'j-rock', 'j-pop'], 'href': 'https://api.spotify.com/v1/artists/0Oazwl71qoHvXnbSxv0wOT', 'id': '0Oazwl71qoHvXnbSxv0wOT', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb6a9d231ffcd7c94bdef33b74', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051746a9d231ffcd7c94bdef33b74', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1786a9d231ffcd7c94bdef33b74', 'width': 160}], 'name': 'BURNOUT SYNDROMES', 'popularity': 56, 'type': 'artist', 'uri': 'spotify:artist:0Oazwl71qoHvXnbSxv0wOT'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2nvl0N9GwyX69RRBMEZ4OD'}, 'followers': {'href': None, 'total': 603776}, 'genres': ['anime', 'j-rock', 'j-pop'], 'href': 'https://api.spotify.com/v1/artists/2nvl0N9GwyX69RRBMEZ4OD', 'id': '2nvl0N9GwyX69RRBMEZ4OD', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb38df323a9b0d7880ae59590b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517438df323a9b0d7880ae59590b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17838df323a9b0d7880ae59590b', 'width': 160}], 'name': '結束バンド', 'popularity': 63, 'type': 'artist', 'uri': 'spotify:artist:2nvl0N9GwyX69RRBMEZ4OD'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/49muoiIu4uea4PO8vueUNN'}, 'followers': {'href': None, 'total': 806960}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/49muoiIu4uea4PO8vueUNN', 'id': '49muoiIu4uea4PO8vueUNN', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb1135e17231033a9cb4ddde8e', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051741135e17231033a9cb4ddde8e', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1781135e17231033a9cb4ddde8e', 'width': 160}], 'name': 'YENA', 'popularity': 56, 'type': 'artist', 'uri': 'spotify:artist:49muoiIu4uea4PO8vueUNN'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4UXqAaa6dQYAk18Lv7PEgX'}, 'followers': {'href': None, 'total': 11217352}, 'genres': ['emo', 'pop punk', 'emo pop'], 'href': 'https://api.spotify.com/v1/artists/4UXqAaa6dQYAk18Lv7PEgX', 'id': '4UXqAaa6dQYAk18Lv7PEgX', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb362011ebe6064c38e97e9aac', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174362011ebe6064c38e97e9aac', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178362011ebe6064c38e97e9aac', 'width': 160}], 'name': 'Fall Out Boy', 'popularity': 80, 'type': 'artist', 'uri': 'spotify:artist:4UXqAaa6dQYAk18Lv7PEgX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4UK2Lzi6fBfUi9rpDt6cik'}, 'followers': {'href': None, 'total': 3031501}, 'genres': ['j-pop', 'j-rock', 'japanese indie', 'anime'], 'href': 'https://api.spotify.com/v1/artists/4UK2Lzi6fBfUi9rpDt6cik', 'id': '4UK2Lzi6fBfUi9rpDt6cik', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebe62cff9c6018ae5616b01eab', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174e62cff9c6018ae5616b01eab', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178e62cff9c6018ae5616b01eab', 'width': 160}], 'name': 'ヨルシカ', 'popularity': 74, 'type': 'artist', 'uri': 'spotify:artist:4UK2Lzi6fBfUi9rpDt6cik'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1SIocsqdEefUTE6XKGUiVS'}, 'followers': {'href': None, 'total': 4264210}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/1SIocsqdEefUTE6XKGUiVS', 'id': '1SIocsqdEefUTE6XKGUiVS', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebb419d66ef21661311c806bfe', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174b419d66ef21661311c806bfe', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178b419d66ef21661311c806bfe', 'width': 160}], 'name': 'BABYMONSTER', 'popularity': 76, 'type': 'artist', 'uri': 'spotify:artist:1SIocsqdEefUTE6XKGUiVS'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2l35CQqtYRh3d8ZIiBep4v'}, 'followers': {'href': None, 'total': 1106811}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/2l35CQqtYRh3d8ZIiBep4v', 'id': '2l35CQqtYRh3d8ZIiBep4v', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebbc861f3d1ba68614d3a301b4', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174bc861f3d1ba68614d3a301b4', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178bc861f3d1ba68614d3a301b4', 'width': 160}], 'name': 'MKTO', 'popularity': 67, 'type': 'artist', 'uri': 'spotify:artist:2l35CQqtYRh3d8ZIiBep4v'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6jEiUoyyJNPHzSR0Nib6HX'}, 'followers': {'href': None, 'total': 810799}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/6jEiUoyyJNPHzSR0Nib6HX', 'id': '6jEiUoyyJNPHzSR0Nib6HX', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb9cc45f0fafaa6587fa6f600f', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051749cc45f0fafaa6587fa6f600f', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1789cc45f0fafaa6587fa6f600f', 'width': 160}], 'name': 'Walk off the Earth', 'popularity': 60, 'type': 'artist', 'uri': 'spotify:artist:6jEiUoyyJNPHzSR0Nib6HX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1VwDG9aBflQupaFNjUru9A'}, 'followers': {'href': None, 'total': 2886118}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/1VwDG9aBflQupaFNjUru9A', 'id': '1VwDG9aBflQupaFNjUru9A', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb8f7649273b8f02d16808a2c5', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051748f7649273b8f02d16808a2c5', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1788f7649273b8f02d16808a2c5', 'width': 160}], 'name': 'NAYEON', 'popularity': 64, 'type': 'artist', 'uri': 'spotify:artist:1VwDG9aBflQupaFNjUru9A'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0IwZVmMMGE7nNXS7vN9SIo'}, 'followers': {'href': None, 'total': 993816}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/0IwZVmMMGE7nNXS7vN9SIo', 'id': '0IwZVmMMGE7nNXS7vN9SIo', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb8bb0411b0375cd719eac306b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051748bb0411b0375cd719eac306b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1788bb0411b0375cd719eac306b', 'width': 160}], 'name': 'MISAMO', 'popularity': 61, 'type': 'artist', 'uri': 'spotify:artist:0IwZVmMMGE7nNXS7vN9SIo'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/64tJ2EAv1R6UaZqc4iOCyj'}, 'followers': {'href': None, 'total': 8994914}, 'genres': ['j-pop', 'anime'], 'href': 'https://api.spotify.com/v1/artists/64tJ2EAv1R6UaZqc4iOCyj', 'id': '64tJ2EAv1R6UaZqc4iOCyj', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebbfdd8a29d0c6bc6950055234', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174bfdd8a29d0c6bc6950055234', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178bfdd8a29d0c6bc6950055234', 'width': 160}], 'name': 'YOASOBI', 'popularity': 76, 'type': 'artist', 'uri': 'spotify:artist:64tJ2EAv1R6UaZqc4iOCyj'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/07QEuhtrNmmZ0zEcqE9SF6'}, 'followers': {'href': None, 'total': 2486320}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/07QEuhtrNmmZ0zEcqE9SF6', 'id': '07QEuhtrNmmZ0zEcqE9SF6', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebce3fbd73ae4f8b3ff54a0a5c', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174ce3fbd73ae4f8b3ff54a0a5c', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178ce3fbd73ae4f8b3ff54a0a5c', 'width': 160}], 'name': 'Owl City', 'popularity': 70, 'type': 'artist', 'uri': 'spotify:artist:07QEuhtrNmmZ0zEcqE9SF6'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5Pwc4xIPtQLFEnJriah9YJ'}, 'followers': {'href': None, 'total': 18133553}, 'genres': ['soft pop'], 'href': 'https://api.spotify.com/v1/artists/5Pwc4xIPtQLFEnJriah9YJ', 'id': '5Pwc4xIPtQLFEnJriah9YJ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb57138b98e7ddd5a86ee97a9b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517457138b98e7ddd5a86ee97a9b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17857138b98e7ddd5a86ee97a9b', 'width': 160}], 'name': 'OneRepublic', 'popularity': 84, 'type': 'artist', 'uri': 'spotify:artist:5Pwc4xIPtQLFEnJriah9YJ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU'}, 'followers': {'href': None, 'total': 57680795}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU', 'id': '4gzpq5DPGxSnKTe4SA8HAU', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb1ba8fc5f5c73e7e9313cc6eb', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051741ba8fc5f5c73e7e9313cc6eb', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1781ba8fc5f5c73e7e9313cc6eb', 'width': 160}], 'name': 'Coldplay', 'popularity': 91, 'type': 'artist', 'uri': 'spotify:artist:4gzpq5DPGxSnKTe4SA8HAU'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0blbVefuxOGltDBa00dspv'}, 'followers': {'href': None, 'total': 3369785}, 'genres': ['anime', 'j-pop', 'j-rock'], 'href': 'https://api.spotify.com/v1/artists/0blbVefuxOGltDBa00dspv', 'id': '0blbVefuxOGltDBa00dspv', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb774ac8933df7e2c8060fd1a2', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174774ac8933df7e2c8060fd1a2', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178774ac8933df7e2c8060fd1a2', 'width': 160}], 'name': 'LiSA', 'popularity': 71, 'type': 'artist', 'uri': 'spotify:artist:0blbVefuxOGltDBa00dspv'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4SpbR6yFEvexJuaBpgAU5p'}, 'followers': {'href': None, 'total': 6904886}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/4SpbR6yFEvexJuaBpgAU5p', 'id': '4SpbR6yFEvexJuaBpgAU5p', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb593f35db6f6837e1047a5e33', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174593f35db6f6837e1047a5e33', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178593f35db6f6837e1047a5e33', 'width': 160}], 'name': 'LE SSERAFIM', 'popularity': 82, 'type': 'artist', 'uri': 'spotify:artist:4SpbR6yFEvexJuaBpgAU5p'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2C2sVVXanbOpymYBMpsi89'}, 'followers': {'href': None, 'total': 561617}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/2C2sVVXanbOpymYBMpsi89', 'id': '2C2sVVXanbOpymYBMpsi89', 'images': [{'height': 563, 'url': 'https://i.scdn.co/image/ff6eb786aff45ab50e9820fe39f359656640888e', 'width': 1000}, {'height': 360, 'url': 'https://i.scdn.co/image/fc2ef2ece7668476e45d3c53d9a215988beb27a4', 'width': 640}, {'height': 113, 'url': 'https://i.scdn.co/image/ebf956c4e6e62c25187fa76d6509f0cf892d76ba', 'width': 200}, {'height': 36, 'url': 'https://i.scdn.co/image/865d5164f7a79a3d880f01f6c4369b31c6e214cd', 'width': 64}], 'name': 'The Cab', 'popularity': 56, 'type': 'artist', 'uri': 'spotify:artist:2C2sVVXanbOpymYBMpsi89'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3qNVuliS40BLgXGxhdBdqu'}, 'followers': {'href': None, 'total': 3064356}, 'genres': ['k-pop', 'k-ballad'], 'href': 'https://api.spotify.com/v1/artists/3qNVuliS40BLgXGxhdBdqu', 'id': '3qNVuliS40BLgXGxhdBdqu', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebb5d9ebbbbe3fff5a330b40c8', 'width':

,artist_name,popularity,genres,artist_id
0,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0
1,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx
2,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V
3,Taylor Swift,98,,06HL4z0CvFAxyc27GXpf02
4,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU
5,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3
6,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE
7,Against The Current,64,pop punk,6yhD1KjhLxIETFF7vIRf8B
8,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX
9,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ
10,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6
11,BURNOUT SYNDROMES,56,"anime, j-rock, j-pop",0Oazwl71qoHvXnbSxv0wOT
12,結束バンド,63,"anime, j-rock, j-pop",2nvl0N9GwyX69RRBMEZ4OD
13,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN
14,Fall Out Boy,80,"emo, pop punk, emo pop",4UXqAaa6dQYAk18Lv7PEgX
15,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik
16,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS
17,MKTO,67,,2l35CQqtYRh3d8ZIiBep4v
18,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX
19,NAYEON,64,k-pop,1VwDG9aBflQupaFNjUru9A
20,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo
21,YOASOBI,76,"j-pop, anime",64tJ2EAv1R6UaZqc4iOCyj
22,Owl City,70,,07QEuhtrNmmZ0zEcqE9SF6
23,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ
24,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU
25,LiSA,71,"anime, j-pop, j-rock",0blbVefuxOGltDBa00dspv
26,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p
27,The Cab,56,,2C2sVVXanbOpymYBMpsi89
28,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu
29,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL
30,RADWIMPS,74,"anime, j-pop, j-rock",1EowJ1WwkMzkCkRomFhui7
31,Ado,77,"j-pop, anime, vocaloid, j-rock",6mEQK9m2krja6X1cfsAjfl
32,Konomi Suzuki,53,"anime, j-pop, j-rock",3O0kLS5sLZ41XZRxjBKmLF
33,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m
34,Relaxu,45,,7Glr8id1TfFSYoK04ENmNK
35,BoyWithUke,73,,1Cd373x8qzC7SNUg5IToqp
36,Paramore,82,"pop punk, emo, emo pop",74XFHRwlV6OrjEM0A2NCMF
37,BAND-MAID,52,"j-rock, k-rock",5Wh3G01Xfxn2zzEZNpuYHH
38,Lyn,63,japanese vgm,5qEtLvXzYdv0G7c7rR6irX
39,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs
40,Glee Cast,70,christmas,0SCbttzoZTnLFebDYmAWCm
41,ROSÉ,86,k-pop,3eVa5w3URK5duf6eyVDbu9
42,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF
43,MindaRyn,43,anime,7MSns7VCEysJJhcp67gvtZ
44,TZUYU,52,k-pop,1arCVYXeStgCY2UazBNBLK
45,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl
46,fripSide,51,"anime, j-pop, j-rock",7ucOhItVkxNqunNLo8AkzN
47,amazarashi,55,"anime, j-rock, j-pop",6T4K8YuFc0JPDrYgABbxao
48,BLACKPINK,80,k-pop,41MozSoPIsD1dJM0CLPjZF
49,Panic! At The Disco,78,emo,20JZFwl6HVl6yg8a4H3ZqK

In [9]:
extract_top_artist_data(sp,'medium_term')

{'items': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/6YVMFz59CuY7ngCxTxjpxE'}, 'followers': {'href': None, 'total': 8355136}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/6YVMFz59CuY7ngCxTxjpxE', 'id': '6YVMFz59CuY7ngCxTxjpxE', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebf7a1090ad3a35a34fc0ecb57', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174f7a1090ad3a35a34fc0ecb57', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178f7a1090ad3a35a34fc0ecb57', 'width': 160}], 'name': 'aespa', 'popularity': 80, 'type': 'artist', 'uri': 'spotify:artist:6YVMFz59CuY7ngCxTxjpxE'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3HqSLMAZ3g3d5poNaI7GOU'}, 'followers': {'href': None, 'total': 9133293}, 'genres': ['k-pop', 'k-ballad'], 'href': 'https://api.spotify.com/v1/artists/3HqSLMAZ3g3d5poNaI7GOU', 'id': '3HqSLMAZ3g3d5poNaI7GOU', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebbd0642ff425698afac5caffd', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174bd0642ff425698afac5caffd', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178bd0642ff425698afac5caffd', 'width': 160}], 'name': 'IU', 'popularity': 70, 'type': 'artist', 'uri': 'spotify:artist:3HqSLMAZ3g3d5poNaI7GOU'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2pHkxVNynHBwQHhGaoBIXX'}, 'followers': {'href': None, 'total': 760546}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2pHkxVNynHBwQHhGaoBIXX', 'id': '2pHkxVNynHBwQHhGaoBIXX', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb0134f9d08f1902ec4778b531', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051740134f9d08f1902ec4778b531', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1780134f9d08f1902ec4778b531', 'width': 160}], 'name': 'MINNIE', 'popularity': 63, 'type': 'artist', 'uri': 'spotify:artist:2pHkxVNynHBwQHhGaoBIXX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/22aCD8IrQZjcPgZw728QT6'}, 'followers': {'href': None, 'total': 832868}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/22aCD8IrQZjcPgZw728QT6', 'id': '22aCD8IrQZjcPgZw728QT6', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb569026949c9d74d8448c6559', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174569026949c9d74d8448c6559', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178569026949c9d74d8448c6559', 'width': 160}], 'name': 'YUQI', 'popularity': 60, 'type': 'artist', 'uri': 'spotify:artist:22aCD8IrQZjcPgZw728QT6'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7n2Ycct7Beij7Dj7meI4X0'}, 'followers': {'href': None, 'total': 21661915}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/7n2Ycct7Beij7Dj7meI4X0', 'id': '7n2Ycct7Beij7Dj7meI4X0', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebca6c145421fa9ceb58d6f9d4', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174ca6c145421fa9ceb58d6f9d4', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178ca6c145421fa9ceb58d6f9d4', 'width': 160}], 'name': 'TWICE', 'popularity': 79, 'type': 'artist', 'uri': 'spotify:artist:7n2Ycct7Beij7Dj7meI4X0'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2AfmfGFbe0A0WsTYm0SDTx'}, 'followers': {'href': None, 'total': 10487023}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2AfmfGFbe0A0WsTYm0SDTx', 'id': '2AfmfGFbe0A0WsTYm0SDTx', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb7fd16327c86d500f83be1d6a', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051747fd16327c86d500f83be1d6a', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1787fd16327c86d500f83be1d6a', 'width': 160}], 'name': '(G)I-DLE', 'popularity': 73, 'type': 'artist', 'uri': 'spotify:artist:2AfmfGFbe0A0WsTYm0SDTx'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2KC9Qb60EaY0kW4eH68vr3'}, 'followers': {'href': None, 'total': 8349525}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/2KC9Qb60EaY0kW4eH68vr3', 'id': '2KC9Qb60EaY0kW4eH68vr3', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb3448062884d4ad30473e964b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051743448062884d4ad30473e964b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1783448062884d4ad30473e964b', 'width': 160}], 'name': 'ITZY', 'popularity': 69, 'type': 'artist', 'uri': 'spotify:artist:2KC9Qb60EaY0kW4eH68vr3'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6RHTUrRF63xao58xh9FXYJ'}, 'followers': {'href': None, 'total': 5448007}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/6RHTUrRF63xao58xh9FXYJ', 'id': '6RHTUrRF63xao58xh9FXYJ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb538dad5b42d963e338726c26', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174538dad5b42d963e338726c26', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178538dad5b42d963e338726c26', 'width': 160}], 'name': 'IVE', 'popularity': 75, 'type': 'artist', 'uri': 'spotify:artist:6RHTUrRF63xao58xh9FXYJ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/49muoiIu4uea4PO8vueUNN'}, 'followers': {'href': None, 'total': 806960}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/49muoiIu4uea4PO8vueUNN', 'id': '49muoiIu4uea4PO8vueUNN', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb1135e17231033a9cb4ddde8e', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051741135e17231033a9cb4ddde8e', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1781135e17231033a9cb4ddde8e', 'width': 160}], 'name': 'YENA', 'popularity': 56, 'type': 'artist', 'uri': 'spotify:artist:49muoiIu4uea4PO8vueUNN'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V'}, 'followers': {'href': None, 'total': 119909905}, 'genres': ['soft pop'], 'href': 'https://api.spotify.com/v1/artists/6eUKZXaKkcviH0Ku9w2n3V', 'id': '6eUKZXaKkcviH0Ku9w2n3V', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb784daff754ecfe0464ddbeb9', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174784daff754ecfe0464ddbeb9', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178784daff754ecfe0464ddbeb9', 'width': 160}], 'name': 'Ed Sheeran', 'popularity': 89, 'type': 'artist', 'uri': 'spotify:artist:6eUKZXaKkcviH0Ku9w2n3V'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3qNVuliS40BLgXGxhdBdqu'}, 'followers': {'href': None, 'total': 3064356}, 'genres': ['k-pop', 'k-ballad'], 'href': 'https://api.spotify.com/v1/artists/3qNVuliS40BLgXGxhdBdqu', 'id': '3qNVuliS40BLgXGxhdBdqu', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebb5d9ebbbbe3fff5a330b40c8', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174b5d9ebbbbe3fff5a330b40c8', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178b5d9ebbbbe3fff5a330b40c8', 'width': 160}], 'name': 'TAEYEON', 'popularity': 67, 'type': 'artist', 'uri': 'spotify:artist:3qNVuliS40BLgXGxhdBdqu'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0IwZVmMMGE7nNXS7vN9SIo'}, 'followers': {'href': None, 'total': 993816}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/0IwZVmMMGE7nNXS7vN9SIo', 'id': '0IwZVmMMGE7nNXS7vN9SIo', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb8bb0411b0375cd719eac306b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051748bb0411b0375cd719eac306b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1788bb0411b0375cd719eac306b', 'width': 160}], 'name': 'MISAMO', 'popularity': 61, 'type': 'artist', 'uri': 'spotify:artist:0IwZVmMMGE7nNXS7vN9SIo'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3skli1w2n0nOZ4qkDbvV2m'}, 'followers': {'href': None, 'total': 113471}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/3skli1w2n0nOZ4qkDbvV2m', 'id': '3skli1w2n0nOZ4qkDbvV2m', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb485cfbf516f7bf8b7b479a91', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174485cfbf516f7bf8b7b479a91', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178485cfbf516f7bf8b7b479a91', 'width': 160}], 'name': 'YEJI', 'popularity': 61, 'type': 'artist', 'uri': 'spotify:artist:3skli1w2n0nOZ4qkDbvV2m'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/7Glr8id1TfFSYoK04ENmNK'}, 'followers': {'href': None, 'total': 7849}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/7Glr8id1TfFSYoK04ENmNK', 'id': '7Glr8id1TfFSYoK04ENmNK', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb73b8b4f4631633edb5701882', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517473b8b4f4631633edb5701882', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17873b8b4f4631633edb5701882', 'width': 160}], 'name': 'Relaxu', 'popularity': 45, 'type': 'artist', 'uri': 'spotify:artist:7Glr8id1TfFSYoK04ENmNK'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/64tJ2EAv1R6UaZqc4iOCyj'}, 'followers': {'href': None, 'total': 8994914}, 'genres': ['j-pop', 'anime'], 'href': 'https://api.spotify.com/v1/artists/64tJ2EAv1R6UaZqc4iOCyj', 'id': '64tJ2EAv1R6UaZqc4iOCyj', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebbfdd8a29d0c6bc6950055234', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174bfdd8a29d0c6bc6950055234', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178bfdd8a29d0c6bc6950055234', 'width': 160}], 'name': 'YOASOBI', 'popularity': 76, 'type': 'artist', 'uri': 'spotify:artist:64tJ2EAv1R6UaZqc4iOCyj'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/1SIocsqdEefUTE6XKGUiVS'}, 'followers': {'href': None, 'total': 4264210}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/1SIocsqdEefUTE6XKGUiVS', 'id': '1SIocsqdEefUTE6XKGUiVS', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebb419d66ef21661311c806bfe', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174b419d66ef21661311c806bfe', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178b419d66ef21661311c806bfe', 'width': 160}], 'name': 'BABYMONSTER', 'popularity': 76, 'type': 'artist', 'uri': 'spotify:artist:1SIocsqdEefUTE6XKGUiVS'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3eVa5w3URK5duf6eyVDbu9'}, 'followers': {'href': None, 'total': 10932416}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/3eVa5w3URK5duf6eyVDbu9', 'id': '3eVa5w3URK5duf6eyVDbu9', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb727a1f1f508238a20ac9fdbf', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174727a1f1f508238a20ac9fdbf', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178727a1f1f508238a20ac9fdbf', 'width': 160}], 'name': 'ROSÉ', 'popularity': 86, 'type': 'artist', 'uri': 'spotify:artist:3eVa5w3URK5duf6eyVDbu9'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6jEiUoyyJNPHzSR0Nib6HX'}, 'followers': {'href': None, 'total': 810799}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/6jEiUoyyJNPHzSR0Nib6HX', 'id': '6jEiUoyyJNPHzSR0Nib6HX', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb9cc45f0fafaa6587fa6f600f', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051749cc45f0fafaa6587fa6f600f', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1789cc45f0fafaa6587fa6f600f', 'width': 160}], 'name': 'Walk off the Earth', 'popularity': 60, 'type': 'artist', 'uri': 'spotify:artist:6jEiUoyyJNPHzSR0Nib6HX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4UK2Lzi6fBfUi9rpDt6cik'}, 'followers': {'href': None, 'total': 3031501}, 'genres': ['j-pop', 'j-rock', 'japanese indie', 'anime'], 'href': 'https://api.spotify.com/v1/artists/4UK2Lzi6fBfUi9rpDt6cik', 'id': '4UK2Lzi6fBfUi9rpDt6cik', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebe62cff9c6018ae5616b01eab', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174e62cff9c6018ae5616b01eab', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178e62cff9c6018ae5616b01eab', 'width': 160}], 'name': 'ヨルシカ', 'popularity': 74, 'type': 'artist', 'uri': 'spotify:artist:4UK2Lzi6fBfUi9rpDt6cik'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/28ot3wh4oNmoFOdVajibBl'}, 'followers': {'href': None, 'total': 3605836}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/28ot3wh4oNmoFOdVajibBl', 'id': '28ot3wh4oNmoFOdVajibBl', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb2b9446440d296ce32189024e', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051742b9446440d296ce32189024e', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1782b9446440d296ce32189024e', 'width': 160}], 'name': 'NMIXX', 'popularity': 71, 'type': 'artist', 'uri': 'spotify:artist:28ot3wh4oNmoFOdVajibBl'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5qEtLvXzYdv0G7c7rR6irX'}, 'followers': {'href': None, 'total': 127388}, 'genres': ['japanese vgm'], 'href': 'https://api.spotify.com/v1/artists/5qEtLvXzYdv0G7c7rR6irX', 'id': '5qEtLvXzYdv0G7c7rR6irX', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb391264cbd0d2e2b4c335d5cb', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174391264cbd0d2e2b4c335d5cb', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178391264cbd0d2e2b4c335d5cb', 'width': 160}], 'name': 'Lyn', 'popularity': 63, 'type': 'artist', 'uri': 'spotify:artist:5qEtLvXzYdv0G7c7rR6irX'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/0hKq3u04JU5IuGNSTGyngJ'}, 'followers': {'href': None, 'total': 79977}, 'genres': [], 'href': 'https://api.spotify.com/v1/artists/0hKq3u04JU5IuGNSTGyngJ', 'id': '0hKq3u04JU5IuGNSTGyngJ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebf0722248fd9cc741474c699c', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174f0722248fd9cc741474c699c', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178f0722248fd9cc741474c699c', 'width': 160}], 'name': 'Shin Giwon Piano', 'popularity': 51, 'type': 'artist', 'uri': 'spotify:artist:0hKq3u04JU5IuGNSTGyngJ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/5Pwc4xIPtQLFEnJriah9YJ'}, 'followers': {'href': None, 'total': 18133553}, 'genres': ['soft pop'], 'href': 'https://api.spotify.com/v1/artists/5Pwc4xIPtQLFEnJriah9YJ', 'id': '5Pwc4xIPtQLFEnJriah9YJ', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb57138b98e7ddd5a86ee97a9b', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab6761610000517457138b98e7ddd5a86ee97a9b', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f17857138b98e7ddd5a86ee97a9b', 'width': 160}], 'name': 'OneRepublic', 'popularity': 84, 'type': 'artist', 'uri': 'spotify:artist:5Pwc4xIPtQLFEnJriah9YJ'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/779v40cWIJUUoIDtC1IGaF'}, 'followers': {'href': None, 'total': 740421}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/779v40cWIJUUoIDtC1IGaF', 'id': '779v40cWIJUUoIDtC1IGaF', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb3694064077be4d5de2e1dd9d', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051743694064077be4d5de2e1dd9d', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1783694064077be4d5de2e1dd9d', 'width': 160}], 'name': 'MIYEON', 'popularity': 47, 'type': 'artist', 'uri': 'spotify:artist:779v40cWIJUUoIDtC1IGaF'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6T4K8YuFc0JPDrYgABbxao'}, 'followers': {'href': None, 'total': 458301}, 'genres': ['anime', 'j-rock', 'j-pop'], 'href': 'https://api.spotify.com/v1/artists/6T4K8YuFc0JPDrYgABbxao', 'id': '6T4K8YuFc0JPDrYgABbxao', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb8c513fde7d812684131a2021', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051748c513fde7d812684131a2021', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1788c513fde7d812684131a2021', 'width': 160}], 'name': 'amazarashi', 'popularity': 55, 'type': 'artist', 'uri': 'spotify:artist:6T4K8YuFc0JPDrYgABbxao'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/6UZ0ba50XreR4TM8u322gs'}, 'followers': {'href': None, 'total': 5678914}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/6UZ0ba50XreR4TM8u322gs', 'id': '6UZ0ba50XreR4TM8u322gs', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb9e33dd3ae51452774a133e1f', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab676161000051749e33dd3ae51452774a133e1f', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f1789e33dd3ae51452774a133e1f', 'width': 160}], 'name': 'JISOO', 'popularity': 74, 'type': 'artist', 'uri': 'spotify:artist:6UZ0ba50XreR4TM8u322gs'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/250b0Wlc5Vk0CoUsaCY84M'}, 'followers': {'href': None, 'total': 9713518}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/250b0Wlc5Vk0CoUsaCY84M', 'id': '250b0Wlc5Vk0CoUsaCY84M', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eba8e3627e392a1d8f539cb575', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174a8e3627e392a1d8f539cb575', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178a8e3627e392a1d8f539cb575', 'width': 160}], 'name': 'JENNIE', 'popularity': 89, 'type': 'artist', 'uri': 'spotify:artist:250b0Wlc5Vk0CoUsaCY84M'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/4SpbR6yFEvexJuaBpgAU5p'}, 'followers': {'href': None, 'total': 6904886}, 'genres': ['k-pop'], 'href': 'https://api.spotify.com/v1/artists/4SpbR6yFEvexJuaBpgAU5p', 'id': '4SpbR6yFEvexJuaBpgAU5p', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb593f35db6f6837e1047a5e33', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174593f35db6f6837e1047a5e33', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178593f35db6f6837e1047a5e33', 'width': 160}], 'name': 'LE SSERAFIM', 'popularity': 82, 'type': 'artist', 'uri': 'spotify:artist:4SpbR6yFEvexJuaBpgAU5p'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/2sCc8pMRgv99AweDSrFFZt'}, 'followers': {'href': None, 'total': 30465}, 'genres': ['anime', 'j-rock', 'j-pop'], 'href': 'https://api.spotify.com/v1/artists/2sCc8pMRgv99AweDSrFFZt', 'id': '2sCc8pMRgv99AweDSrFFZt', 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebca92c439ed2e43f615740056', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174ca92c439ed2e43f615740056', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image

,artist_name,popularity,genres,artist_id
0,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE
1,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU
2,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX
3,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6
4,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0
5,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx
6,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3
7,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ
8,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN
9,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V
10,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu
11,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo
12,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m
13,Relaxu,45,,7Glr8id1TfFSYoK04ENmNK
14,YOASOBI,76,"j-pop, anime",64tJ2EAv1R6UaZqc4iOCyj
15,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS
16,ROSÉ,86,k-pop,3eVa5w3URK5duf6eyVDbu9
17,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX
18,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik
19,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl
20,Lyn,63,japanese vgm,5qEtLvXzYdv0G7c7rR6irX
21,Shin Giwon Piano,51,,0hKq3u04JU5IuGNSTGyngJ
22,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ
23,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF
24,amazarashi,55,"anime, j-rock, j-pop",6T4K8YuFc0JPDrYgABbxao
25,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs
26,JENNIE,89,k-pop,250b0Wlc5Vk0CoUsaCY84M
27,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p
28,THE SIXTH LIE,40,"anime, j-rock, j-pop",2sCc8pMRgv99AweDSrFFZt
29,結束バンド,63,"anime, j-rock, j-pop",2nvl0N9GwyX69RRBMEZ4OD
30,NAYEON,64,k-pop,1VwDG9aBflQupaFNjUru9A
31,アトラスサウンドチーム,70,"japanese vgm, soundtrack",4hFBhdNVZZuVk5FYThUwaN
32,LiSA,71,"anime, j-pop, j-rock",0blbVefuxOGltDBa00dspv
33,KISS OF LIFE,73,k-pop,4TEK9tIkcoxib4GxT3O4ky
34,Ado,77,"j-pop, anime, vocaloid, j-rock",6mEQK9m2krja6X1cfsAjfl
35,QWER,53,"k-rock, k-pop",0XufO9nLOKNN0w0qNrDrZy
36,TZUYU,52,k-pop,1arCVYXeStgCY2UazBNBLK
37,Taylor Swift,98,,06HL4z0CvFAxyc27GXpf02
38,2NE1,62,k-pop,1l0mKo96Jh9HVYONcRl3Yp
39,milet,64,"j-pop, anime, j-rock",45ft4DyTCEJfQwTBHXpdhM
40,Imagine Dragons,88,,53XhwfbYqKCa1cC15pYq2q
41,OFFICIAL HIGE DANDISM,71,"j-pop, anime, j-rock",5Vo1hnCRmCM6M4thZCInCj
42,Evan Call,62,anime,0nMGbTpPx4b3h5fMG9CpWJ
43,Red Velvet,70,k-pop,1z4g3DjTBBZKhvAroFlhOM
44,SEULGI,63,k-pop,2QM5S4yO6xHgnNvF0nbZZq
45,Mrs. GREEN APPLE,82,"j-pop, anime, j-rock",4QvgGvpgzgyUOo8Yp8LDm9
46,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL
47,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU
48,LISA,83,k-pop,5L1lO4eRHmJ7a0Q6csE5cT
49,Against The Current,64,pop punk,6yhD1KjhLxIETFF7vIRf8B