# Load Data

In [1]:
import pandas as pd
import numpy as np
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
import os
from pathlib import Path

# Extract credential access Spotify API

In [2]:
env_path = Path("..") / ".env"
load_dotenv(dotenv_path=env_path)
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")
REDIRECT_URI = os.getenv("REDIRECT_URI")

# Extract Spotify data

## Helper Functions

In [3]:
def extract_top_tracks_data(spotify_client,time_range)->pd.DataFrame:
    '''
    Convert JSON file extracted from spotify 
    to dataframe for analysis
    '''
    top_tracks_json = spotify_client.current_user_top_tracks(limit=50, time_range=time_range)
    track_list = []

    for item in top_tracks_json['items']:
        track_info = {
            'track_name':item['name'],
            'artist_name': item['artists'][0]['name'],
            'album_name': item['album']['name'],
            'release_date': item['album']['release_date'],
            'popularity': item['popularity'],
            'duration_ms': item['duration_ms'],
            'explicit':item['explicit'],
            'track_id': item['id']
        }
        track_list.append(track_info)
    
    data = pd.DataFrame(track_list)
    data['duration_min'] = data['duration_ms']/60000
    data['release_date'] = pd.to_datetime(data['release_date'])

    return data

def extract_top_artist_data(spotify_client,time_range)->pd.DataFrame:
    '''
    Convert JSON file extracted from Spotify
    to dataframe for analysis
    '''
    top_artist_json = spotify_client.current_user_top_artists(limit = 50,time_range = time_range)
    artist_list = []
    for item in top_artist_json['items']:
        artist_info = {
            'artist_name':item['name'],
            'popularity':item['popularity'],
            'genres': ', '.join(item['genres']),
            'artist_id': item['id'],
            # Gets the largest image if exists
            'image_url': item['images'][0]['url'] if item['images'] else None,
            'followers': item['followers']['total']
        }
        artist_list.append(artist_info)
    print(item['images'])
    data = pd.DataFrame(artist_list)
    return data

# Fetch Top Tracks

In [4]:
# Optional: remove existing cache for fresh login
if os.path.exists(".cache-my-music-app"):
    os.remove(".cache-my-music-app")

# Create the OAuth object
sp_oauth = SpotifyOAuth(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    redirect_uri=REDIRECT_URI,
    scope=["user-top-read", "user-library-read", "playlist-read-private"],
    cache_path=".cache-my-music-app"
)

# Create the Spotify client using the SpotifyOAuth instance directly
sp = spotipy.Spotify(auth_manager=sp_oauth)

# Test API call
try:
    results = sp.current_user_top_tracks(limit=10)
    for idx, item in enumerate(results['items']):
        print(f"{idx+1}. {item['name']} - {item['artists'][0]['name']}")
except spotipy.exceptions.SpotifyException as e:
    print(f"Error: {e}")

print("Fetching your top tracks...")
top_tracks = sp.current_user_top_tracks(
    limit=50, time_range='medium_term'
    )

short_term_track_data = extract_top_tracks_data(sp,'short_term')
medium_term_track_data = extract_top_tracks_data(sp,'medium_term')
long_term_track_data = extract_top_tracks_data(sp,'long_term')

1. CASANOVA POSSE - ALI
2. HER - MINNIE
3. Imaginary Friend - ITZY
4. Air - YEJI
5. I TRUST YOU - エミリア(CV:高橋李依)
6. Shopper - IU
7. Secret - IU
8. Whiplash - aespa
9. FREAK - YUQI
10. NEMONEMO - YENA
Fetching your top tracks...

In [5]:
long_term_track_data

,track_name,artist_name,album_name,release_date,popularity,duration_ms,explicit,track_id,duration_min
0,Nobody - from Kaiju No. 8,OneRepublic,Nobody (from Kaiju No. 8),2024-04-12,70,153626,False,47N81NMkB488fuOwOC3Oip,2.560433
1,I GOT YOU,TWICE,I GOT YOU,2024-02-02,59,173240,False,35dhwUoJNlxrPyEIJkfDnx,2.887333
2,FREAK,YUQI,YUQ1,2024-04-23,57,171080,False,6ERs9uORCo1MfV0m9ixCuv,2.851333
3,DIVE,TWICE,DIVE,2024-07-10,57,181860,False,5vK3WrTOp6rEoASx1jAsp1,3.031000
4,Fate,(G)I-DLE,2,2024-01-29,62,161546,False,2vNPGH1x5ZwxTjlvzLCyc2,2.692433
5,Doughnut,TWICE,Celebrate,2022-07-27,53,263680,False,65rmgd5uMb4Rgqb5dSiU0p,4.394667
6,MORE & MORE,TWICE,MORE & MORE,2020-06-01,63,199653,False,3omvXShuRPM3zbDpWYqf5g,3.327550
7,Red Rover,YUQI,YUQ1,2024-04-23,48,123320,False,4TQBHR8LcbBUv0LvLmn54H,2.055333
8,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550
9,YES or YES,TWICE,YES or YES,2018-11-05,68,237680,False,26OVhEqFDQH0Ij77QtmGP9,3.961333
10,"""good guy""",Against The Current,"""good guy""",2023-04-21,48,208052,True,3bfElZNhtvtGvWMVgCBgZK,3.467533
11,Shopper,IU,The Winning,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333
12,POP!,NAYEON,IM NAYEON,2022-06-24,72,168106,False,3lOMJTQTd6J34faYwASc33,2.801767
13,青のすみか,Tatsuya Kitani,青のすみか,2023-07-07,72,196466,False,12usPU2WnqgCHAW1EK2dfd,3.274433
14,CASANOVA POSSE,ALI,CASANOVA POSSE,2025-01-10,65,240653,False,26Lip4WX1oWceF9tb8m2qw,4.010883
15,Talk that Talk,TWICE,BETWEEN 1&2,2022-08-26,69,177466,False,0RDqNCRBGrSegk16Avfzuq,2.957767
16,Perfect World,TWICE,Perfect World,2021-07-28,58,182680,False,0iuZMy88H6vxDA2oaJNhJg,3.044667
17,晴る,ヨルシカ,晴る,2024-01-05,74,270705,False,5eY7692tmgHB9dbmq6wa2M,4.511750
18,Super Lady,(G)I-DLE,2,2024-01-29,64,152186,False,5qI5EUqfDJpQ7w6sMECK7U,2.536433
19,Long Live (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),2023-07-07,73,317960,False,4hqJ4bSlYJOXb6Z4SRmzxs,5.299333
20,Klaxon,(G)I-DLE,I SWAY,2024-07-08,63,175106,False,294hRgOqnGW2BemqP8D35X,2.918433
21,No Celestial,LE SSERAFIM,ANTIFRAGILE,2022-10-17,60,166491,False,21ApmVGIzIAIDSBdHu6SVt,2.774850
22,ONE SPARK,TWICE,With YOU-th,2024-02-23,67,183559,False,7cIn67LEvk16v6komC8znS,3.059317
23,Live My Life,aespa,Armageddon - The 1st Album,2024-05-27,63,159133,False,1x1oCGsFUDViOvcISuoKW0,2.652217
24,Imaginary Friend,ITZY,GOLD,2024-10-15,66,202429,False,06BeeZaS4YArThfTMu80QS,3.373817
25,Air,YEJI,AIR,2025-03-10,75,194800,False,6HSns0qPQQfgekCrBF0Dkf,3.246667
26,HER,MINNIE,HER,2025-01-21,69,159797,False,2MbPhDgeXVipowltFneRH2,2.663283
27,境界線,amazarashi,七号線ロストボーイズ,2022-04-13,48,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550
28,I TRUST YOU,エミリア(CV:高橋李依),"SONG FROM TV SERIES ""RE:ZERO -STARTING LIFE IN...",2024-11-14,34,255396,False,7Ccvd3UVSfORSNyeOO069h,4.256600
29,Alcohol-Free,TWICE,Taste of Love,2021-06-11,66,210573,False,0BTaaKT4RMbs5M73tOHX5Y,3.509550
30,Beyond the Horizon,TWICE,DIVE,2024-07-17,47,212826,False,27f7ZEBoJIJ3HzOpzqmDqO,3.547100
31,Ocean Deep,TWICE,DIVE,2024-07-17,47,220106,False,6jya1u1sEhObLCDFGyWuAW,3.668433
32,Sunshine,OneRepublic,Sunshine,2021-11-10,74,163854,False,5r43qanLhUCdBj8HN3fa6B,2.730900
33,LOVE FOOLISH,TWICE,Feel Special,2019-09-23,53,191226,False,1MdEg2lk4EakgWnCvFUGEZ,3.187100
34,DIVE,TWICE,DIVE,2024-07-17,57,181860,False,3JstVDAZKy4O8SZ5yoXdQr,3.031000
35,Feel Special,TWICE,Feel Special,2019-09-23,71,206866,False,3Hz3tTQwOdM6XkA0ALB2G9,3.447767
36,Hare Hare,TWICE,Hare Hare,2023-05-31,46,203546,False,3QcJghvqRS17RoPPP0C2sp,3.392433
37,MOONLIGHT SUNRISE,TWICE,READY TO BE,2023-03-10,61,180320,False,5IN9W6eUfk3014My9awagX,3.005333
38,Baby Blue Love,TWICE,Taste of Love,2021-06-11,50,166666,False,7Jzo3IObpANz6giPTUrihB,2.777767
39,Wife,(G)I-DLE,Wife,2024-01-21,56,121226,False,6hWU8LrnjLyYHShDyNWFZj,2.020433
40,Secret,IU,Last Fantasy,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867
41,Likey,TWICE,Twicetagram,2017-10-30,66,207813,False,0IEVKWduAaMcZepZQVr80T,3.463550
42,Mine (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),2023-07-07,74,231706,False,7G0gBu6nLdhFDPRLc0HdDG,3.861767
43,Whiplash,aespa,Whiplash - The 5th Mini Album,2024-10-21,78,183226,False,6uPnrBgweGOcwjFL4ItAvV,3.053767
44,I GOT YOU,TWICE,With YOU-th,2024-02-23,54,173240,False,0mgveJEIGjcN51w4JIQtI6,2.887333
45,ABCD,NAYEON,NA,2024-06-14,72,162840,False,0V2passWyAXnON67kfAj7y,2.714000
46,Wife,(G)I-DLE,2,2024-01-29,60,121226,False,1j8jqwFpFQ8YqsIJAiYFLZ,2.020433
47,Killin’ Me Good,JIHYO,ZONE,2023-08-18,64,185920,False,4Cyf87ul1le0xTWRFBoYd7,3.098667
48,NEMONEMO,YENA,NEMONEMO,2024-09-30,67,178026,False,4UwsXGVppRRJpKBHy0mtyK,2.967100
49,Just Imagine It,MKTO,Bad Girls EP,2015-07-24,50,250746,False,0mtmrbRFsectINNpHdDkUQ,4.179100

In [6]:
short_term_track_data

,track_name,artist_name,album_name,release_date,popularity,duration_ms,explicit,track_id,duration_min
0,Air,YEJI,Air,2025-03-10,55,194800,False,2HhIndg75YiKjuUgGiMjSA,3.246667
1,Draw the Moon (feat. MIYAVI),MINNIE,"Webtoon <Myst, Might, Mayhem> OST Part. 2 Draw...",2025-03-21,45,210146,False,4B3JCEcAeTofpsfsEianeS,3.502433
2,Radio (Dum-Dum),YUQI,Radio (Dum-Dum),2025-03-17,67,152373,False,0mXXjVVAhaasNXga2HMgJK,2.539550
3,I,TAEYEON,I - The 1st Mini Album,2015-10-07,61,206038,False,5ZkITfPpcNPnyYGTibkO6m,3.433967
4,Invasion,YEJI,Air,2025-03-10,40,167800,False,3ePablAj7jk2c1j5CKEtAv,2.796667
5,HAPPY,DAY6,Fourever,2024-03-18,64,189934,False,1k68vKHNQXU5CHqcM7Yp7N,3.165567
6,"Can’t Slow Me, No",YEJI,Air,2025-03-10,38,178573,False,7EbaA7z7wP3G7xfYZVlVJS,2.976217
7,Shopper,IU,The Winning,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333
8,SMILEY-Japanese Ver.- (feat.ちゃんみな),YENA,SMILEY-Japanese Ver.- (feat.ちゃんみな),2023-08-07,39,176882,False,4RhkH4fGvvEzxvRlUcYH9L,2.948033
9,NEMONEMO,YENA,NEMONEMO,2024-09-30,67,178026,False,4UwsXGVppRRJpKBHy0mtyK,2.967100
10,Lxxk 2 U,YENA,ˣ‿ˣ (SMiLEY),2022-01-17,43,182853,False,5U7emXCoCl8EOEJUVNbguC,3.047550
11,Supernova,aespa,Armageddon - The 1st Album,2024-05-27,64,178880,False,2JhbSmNAyM9kYiqwa8Tpla,2.981333
12,FOREVER,BABYMONSTER,DRIP,2024-11-01,62,212734,False,7a6vvAM1cjAuyVQpqv9pmu,3.545567
13,Autumn morning,IU,가을 아침 [Gaeul Achim] : Autumn morning,2017-09-22,49,218884,False,100N8P8WYnz9eCYuLYGflV,3.648067
14,Secret,IU,Last Fantasy,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867
15,Whiplash,aespa,Whiplash - The 5th Mini Album,2024-10-21,73,183226,False,7Cnpb1vBbC46RgVyyKLH7p,3.053767
16,HER,MINNIE,HER,2025-01-21,45,159797,False,1Jm2piFQ1Nq3fGHwu3fyvT,2.663283
17,ひたむき,SUPER BEAVER,音楽,2024-02-21,50,246800,False,4Jp91ygcS0CBz8MwtvoBrU,4.113333
18,Well… (ROCK VER.),IU,Growing Up,2009-04-23,39,190589,False,6zpiGeoHYRF5vtrboE3rAC,3.176483
19,Live My Life,aespa,Armageddon - The 1st Album,2024-05-27,58,159133,False,71lnolmea3IZeG90Gj7jHg,2.652217
20,WithOrWithOut,YENA,SMARTPHONE,2022-08-03,34,191973,False,5tazcUyCvfGdRWC1Da5rCS,3.199550
21,Obsession (feat. TEN),MINNIE,HER,2025-01-21,27,222541,False,6sEqkiXe4vRNIhOvNdZzL1,3.709017
22,My Stupid Heart (with Lauv),Walk off the Earth,My Stupid Heart (with Lauv),2023-03-03,52,160866,False,1SVOLTmC627fn0XY9ltvx2,2.681100
23,BAHAMA,aespa,Armageddon - The 1st Album,2024-05-27,44,190533,False,1FXNYp47arDhsngAsHSG9v,3.175550
24,境界線,amazarashi,七号線ロストボーイズ,2022-04-13,48,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550
25,Hate Rodrigo (Feat. YUQI),YENA,HATE XX,2023-06-27,54,181013,False,5ms7rcVKjBFUtoVh8hE0Y9,3.016883
26,Letter To Myself,TAEYEON,Letter To Myself - The 6th Mini Album,2024-11-18,63,184060,False,1Uxr0oBXAZRuLkAz27TkLc,3.067667
27,REBEL HEART,IVE,REBEL HEART,2025-01-13,66,188266,False,1jtlHteF4y7FFHKgYFld4f,3.137767
28,I Don't Wanna Wait,David Guetta,I Don't Wanna Wait,2024-04-05,85,149667,False,331l3xABO0HMr1Kkyh2LZq,2.494450
29,PINK YOUR MOMENT,MINNIE,PINK YOUR MOMENT,2023-04-26,16,131306,False,3CH6RNIVix2lZp9awUfOSQ,2.188433
30,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550
31,Getaway,MINNIE,"My Dangerous Wife, Pt. 2 (Original Television ...",2020-10-11,34,228080,False,41nBWFdECOtxYnygCpL6AH,3.801333
32,This Is The New Shit,Marilyn Manson,The Golden Age Of Grotesque,2003-01-01,63,259666,True,5P13mfqn9o3ToFPTxowEgO,4.327767
33,LEveL,SawanoHiroyuki[nZk],bLACKbLUE,2024-10-02,54,182653,False,5hakB3OS30xHJsWq6mqty7,3.044217
34,Into the Unknown (End Credit Version),TAEYEON,Frozen 2 (Korean Original Motion Picture Sound...,2019-11-15,40,189120,False,4OkHootAlj7w9Eb2zJVlWr,3.152000
35,APT.,ROSÉ,rosie,2024-12-06,92,169917,False,4wJ5Qq0jBN4ajy7ouZIV1c,2.831950
36,258,YEJI,Air,2025-03-10,41,193040,False,6jZP2gYURZhXxh45vMAliR,3.217333
37,造浪 - 《我要逆风去》电视剧主题曲,YUQI,造浪 (《我要逆风去》电视剧主题曲),2024-06-25,36,188307,False,0tNwt2ZBNkelLrLnZqOC2H,3.138450
38,Sugar,YENA,NEMONEMO,2024-09-30,49,166653,False,1T3HuFlijT5Uu4pZI60tgr,2.777550
39,50 Ways to Say Goodbye,Train,California 37,2012-04-17,70,247946,False,2NniAhAtkRACaMeYt48xlD,4.132433
40,SMILEY(Feat. BIBI),YENA,ˣ‿ˣ (SMiLEY),2022-01-17,60,173413,False,4zCIxSnVWpGNghERX4uWZF,2.890217
41,KIDDING ME,ITZY,GUESS WHO,2021-04-30,24,213960,False,1muZkKwVHfv8hS77RG2G2I,3.566000
42,Nobody - from Kaiju No. 8,OneRepublic,Artificial Paradise (Deluxe),2024-07-12,63,153626,False,3SiVMpHxTS1gspWzRZE50S,2.560433
43,My Universe,Coldplay,Music Of The Spheres,2021-10-15,77,226198,False,46HNZY1i7O6jwTA7Slo2PI,3.769967
44,UP - KARINA Solo,aespa,SYNK : PARALLEL LINE - Special Digital Single,2024-10-09,80,166640,False,5sjnkOfTLCLNfkkchI2re2,2.777333
45,Your Love,JISOO,AMORTAGE,2025-02-14,78,173232,False,6TPpCbn9z0IY5Te048iy5R,2.887200
46,Armageddon,aespa,Armageddon - The 1st Album,2024-05-27,61,196466,False,6lAvyeD3Nq43AjyCxZQj54,3.274433
47,Rum Pum Pum Pum,aespa,"2025 SMTOWN : THE CULTURE, THE FUTURE",2025-02-14,61,209613,False,00M2YcEqhsVbSW6RUKqIY3,3.493550
48,spiral,LONGMAN,10/4,2023-10-04,45,231746,False,18Y6TCF80HYi0Fu53xcUge,3.862433
49,BAD HOBBY,YENA,HATE XX,2023-06-27,41,131013,False,4XGOlD2OFGPHXLA0DBPr5M,2.183550

# Fetch Top Artist

In [7]:
extract_top_artist_data(sp,'short_term')

[{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebf9736f54357de6014f551fca', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174f9736f54357de6014f551fca', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178f9736f54357de6014f551fca', 'width': 160}]

,artist_name,popularity,genres,artist_id,image_url,followers
0,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE,https://i.scdn.co/image/ab6761610000e5ebf7a109...,8355136
1,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN,https://i.scdn.co/image/ab6761610000e5eb1135e1...,806960
2,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU,https://i.scdn.co/image/ab6761610000e5ebbd0642...,9133293
3,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu,https://i.scdn.co/image/ab6761610000e5ebb5d9eb...,3064356
4,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX,https://i.scdn.co/image/ab6761610000e5eb1a9a17...,760546
5,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0,https://i.scdn.co/image/ab6761610000e5ebca6c14...,21661915
6,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3,https://i.scdn.co/image/ab6761610000e5eb344806...,8349525
7,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m,https://i.scdn.co/image/ab6761610000e5eb485cfb...,113471
8,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6,https://i.scdn.co/image/ab6761610000e5eb569026...,832868
9,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl,https://i.scdn.co/image/ab6761610000e5ebb75519...,3605836
10,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx,https://i.scdn.co/image/ab6761610000e5eb7fd163...,10487023
11,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ,https://i.scdn.co/image/ab6761610000e5eb538dad...,5448007
12,THE SIXTH LIE,40,"anime, j-rock, j-pop",2sCc8pMRgv99AweDSrFFZt,https://i.scdn.co/image/ab6761610000e5ebca92c4...,30465
13,KISS OF LIFE,73,k-pop,4TEK9tIkcoxib4GxT3O4ky,https://i.scdn.co/image/ab6761610000e5eb33a8cc...,2125025
14,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p,https://i.scdn.co/image/ab6761610000e5eb593f35...,6904886
15,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS,https://i.scdn.co/image/ab6761610000e5ebb419d6...,4264210
16,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo,https://i.scdn.co/image/ab6761610000e5eb8bb041...,993816
17,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF,https://i.scdn.co/image/ab6761610000e5eb369406...,740421
18,SEULGI,63,k-pop,2QM5S4yO6xHgnNvF0nbZZq,https://i.scdn.co/image/ab6761610000e5eb09369a...,1212276
19,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs,https://i.scdn.co/image/ab6761610000e5eb9e33dd...,5678914
20,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL,https://i.scdn.co/image/ab6761610000e5eb92d8ef...,978773
21,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik,https://i.scdn.co/image/ab6761610000e5ebe62cff...,3031501
22,SOOJIN,43,k-pop,0kB3Vlf3xDNZQz6NjAPJV8,https://i.scdn.co/image/ab6761610000e5ebc013b5...,431644
23,TEN,68,k-pop,3Q5Qep7ytrjVleNnMnntgQ,https://i.scdn.co/image/ab6761610000e5eb8f8c7f...,842910
24,G-DRAGON,76,"k-pop, k-rap",30b9WulBM8sFuBo17nNq9c,https://i.scdn.co/image/ab6761610000e5eb783a6a...,3458766
25,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ,https://i.scdn.co/image/ab6761610000e5eb57138b...,18133553
26,DAY6,69,"k-rock, k-pop",5TnQc2N1iKlFjYD7CPGvFc,https://i.scdn.co/image/ab6761610000e5eb10e83b...,3669904
27,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V,https://i.scdn.co/image/ab6761610000e5eb399444...,119909905
28,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...,57680795
29,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX,https://i.scdn.co/image/ab6761610000e5ebf9736f...,810799

In [8]:
extract_top_artist_data(sp,'long_term')

[{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebb256ae9a4b82bfff97776ae2', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174b256ae9a4b82bfff97776ae2', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178b256ae9a4b82bfff97776ae2', 'width': 160}]

,artist_name,popularity,genres,artist_id,image_url,followers
0,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0,https://i.scdn.co/image/ab6761610000e5ebca6c14...,21661915
1,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx,https://i.scdn.co/image/ab6761610000e5eb7fd163...,10487023
2,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V,https://i.scdn.co/image/ab6761610000e5eb784daf...,119909905
3,Taylor Swift,98,,06HL4z0CvFAxyc27GXpf02,https://i.scdn.co/image/ab6761610000e5ebe672b5...,135368184
4,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU,https://i.scdn.co/image/ab6761610000e5ebbd0642...,9133293
5,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3,https://i.scdn.co/image/ab6761610000e5eb344806...,8349525
6,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE,https://i.scdn.co/image/ab6761610000e5ebf7a109...,8355136
7,Against The Current,64,pop punk,6yhD1KjhLxIETFF7vIRf8B,https://i.scdn.co/image/ab6761610000e5eb469aba...,528861
8,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX,https://i.scdn.co/image/ab6761610000e5eb1a9a17...,760546
9,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ,https://i.scdn.co/image/ab6761610000e5eb538dad...,5448007
10,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6,https://i.scdn.co/image/ab6761610000e5eb569026...,832868
11,BURNOUT SYNDROMES,56,"anime, j-rock, j-pop",0Oazwl71qoHvXnbSxv0wOT,https://i.scdn.co/image/ab6761610000e5eb6a9d23...,290718
12,結束バンド,63,"anime, j-rock, j-pop",2nvl0N9GwyX69RRBMEZ4OD,https://i.scdn.co/image/ab6761610000e5eb38df32...,603776
13,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN,https://i.scdn.co/image/ab6761610000e5eb1135e1...,806960
14,Fall Out Boy,80,"emo, pop punk, emo pop",4UXqAaa6dQYAk18Lv7PEgX,https://i.scdn.co/image/ab6761610000e5eb362011...,11217352
15,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik,https://i.scdn.co/image/ab6761610000e5ebe62cff...,3031501
16,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS,https://i.scdn.co/image/ab6761610000e5ebb419d6...,4264210
17,MKTO,67,,2l35CQqtYRh3d8ZIiBep4v,https://i.scdn.co/image/ab6761610000e5ebbc861f...,1106811
18,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX,https://i.scdn.co/image/ab6761610000e5eb9cc45f...,810799
19,NAYEON,64,k-pop,1VwDG9aBflQupaFNjUru9A,https://i.scdn.co/image/ab6761610000e5eb8f7649...,2886118
20,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo,https://i.scdn.co/image/ab6761610000e5eb8bb041...,993816
21,YOASOBI,76,"j-pop, anime",64tJ2EAv1R6UaZqc4iOCyj,https://i.scdn.co/image/ab6761610000e5ebbfdd8a...,8994914
22,Owl City,70,,07QEuhtrNmmZ0zEcqE9SF6,https://i.scdn.co/image/ab6761610000e5ebce3fbd...,2486320
23,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ,https://i.scdn.co/image/ab6761610000e5eb57138b...,18133553
24,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...,57680795
25,LiSA,71,"anime, j-pop, j-rock",0blbVefuxOGltDBa00dspv,https://i.scdn.co/image/ab6761610000e5eb774ac8...,3369785
26,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p,https://i.scdn.co/image/ab6761610000e5eb593f35...,6904886
27,The Cab,56,,2C2sVVXanbOpymYBMpsi89,https://i.scdn.co/image/ff6eb786aff45ab50e9820...,561617
28,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu,https://i.scdn.co/image/ab6761610000e5ebb5d9eb...,3064356
29,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL,https://i.scdn.co/image/ab6761610000e5eb92d8ef...,978773
30,RADWIMPS,74,"anime, j-pop, j-rock",1EowJ1WwkMzkCkRomFhui7,https://i.scdn.co/image/ab6761610000e5eb78cca9...,4454022
31,Ado,77,"j-pop, anime, vocaloid, j-rock",6mEQK9m2krja6X1cfsAjfl,https://i.scdn.co/image/ab6761610000e5ebbcb1c1...,5845982
32,Konomi Suzuki,53,"anime, j-pop, j-rock",3O0kLS5sLZ41XZRxjBKmLF,https://i.scdn.co/image/ab6761610000e5ebce9e87...,218871
33,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m,https://i.scdn.co/image/ab6761610000e5eb485cfb...,113471
34,Relaxu,45,,7Glr8id1TfFSYoK04ENmNK,https://i.scdn.co/image/ab6761610000e5eb73b8b4...,7849
35,BoyWithUke,73,,1Cd373x8qzC7SNUg5IToqp,https://i.scdn.co/image/ab6761610000e5ebc69a43...,4495236
36,Paramore,82,"pop punk, emo, emo pop",74XFHRwlV6OrjEM0A2NCMF,https://i.scdn.co/image/ab6761610000e5ebb10c34...,9299446
37,BAND-MAID,52,"j-rock, k-rock",5Wh3G01Xfxn2zzEZNpuYHH,https://i.scdn.co/image/ab6761610000e5eb3dc779...,332620
38,Lyn,63,japanese vgm,5qEtLvXzYdv0G7c7rR6irX,https://i.scdn.co/image/ab6761610000e5eb391264...,127388
39,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs,https://i.scdn.co/image/ab6761610000e5eb9e33dd...,5678914
40,Glee Cast,70,christmas,0SCbttzoZTnLFebDYmAWCm,https://i.scdn.co/image/5b5a95f260ac429405e871...,1537293
41,ROSÉ,86,k-pop,3eVa5w3URK5duf6eyVDbu9,https://i.scdn.co/image/ab6761610000e5eb727a1f...,10932416
42,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF,https://i.scdn.co/image/ab6761610000e5eb369406...,740421
43,MindaRyn,43,anime,7MSns7VCEysJJhcp67gvtZ,https://i.scdn.co/image/ab6761610000e5eb4e52ed...,46217
44,TZUYU,52,k-pop,1arCVYXeStgCY2UazBNBLK,https://i.scdn.co/image/ab6761610000e5eb9f631e...,308199
45,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl,https://i.scdn.co/image/ab6761610000e5ebb75519...,3605836
46,fripSide,51,"anime, j-pop, j-rock",7ucOhItVkxNqunNLo8AkzN,https://i.scdn.co/image/ab6761610000e5eb799924...,237315
47,amazarashi,55,"anime, j-rock, j-pop",6T4K8YuFc0JPDrYgABbxao,https://i.scdn.co/image/ab6761610000e5eb8c513f...,458301
48,BLACKPINK,80,k-pop,41MozSoPIsD1dJM0CLPjZF,https://i.scdn.co/image/ab6761610000e5ebc9690b...,53472383
49,Panic! At The Disco,78,emo,20JZFwl6HVl6yg8a4H3ZqK,https://i.scdn.co/image/ab6761610000e5ebb256ae...,12574955

In [9]:
extract_top_artist_data(sp,'medium_term')

[{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5eb469aba515a0815396f1c432c', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174469aba515a0815396f1c432c', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178469aba515a0815396f1c432c', 'width': 160}]

,artist_name,popularity,genres,artist_id,image_url,followers
0,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE,https://i.scdn.co/image/ab6761610000e5ebf7a109...,8355136
1,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU,https://i.scdn.co/image/ab6761610000e5ebbd0642...,9133293
2,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX,https://i.scdn.co/image/ab6761610000e5eb1a9a17...,760546
3,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6,https://i.scdn.co/image/ab6761610000e5eb569026...,832868
4,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0,https://i.scdn.co/image/ab6761610000e5ebca6c14...,21661915
5,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx,https://i.scdn.co/image/ab6761610000e5eb7fd163...,10487023
6,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3,https://i.scdn.co/image/ab6761610000e5eb344806...,8349525
7,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ,https://i.scdn.co/image/ab6761610000e5eb538dad...,5448007
8,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN,https://i.scdn.co/image/ab6761610000e5eb1135e1...,806960
9,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V,https://i.scdn.co/image/ab6761610000e5eb399444...,119909905
10,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu,https://i.scdn.co/image/ab6761610000e5ebb5d9eb...,3064356
11,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo,https://i.scdn.co/image/ab6761610000e5eb8bb041...,993816
12,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m,https://i.scdn.co/image/ab6761610000e5eb485cfb...,113471
13,Relaxu,45,,7Glr8id1TfFSYoK04ENmNK,https://i.scdn.co/image/ab6761610000e5eb73b8b4...,7849
14,YOASOBI,76,"j-pop, anime",64tJ2EAv1R6UaZqc4iOCyj,https://i.scdn.co/image/ab6761610000e5ebbfdd8a...,8994914
15,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS,https://i.scdn.co/image/ab6761610000e5ebb419d6...,4264210
16,ROSÉ,86,k-pop,3eVa5w3URK5duf6eyVDbu9,https://i.scdn.co/image/ab6761610000e5eb727a1f...,10932416
17,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX,https://i.scdn.co/image/ab6761610000e5eb9cc45f...,810799
18,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik,https://i.scdn.co/image/ab6761610000e5ebe62cff...,3031501
19,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl,https://i.scdn.co/image/ab6761610000e5ebb75519...,3605836
20,Lyn,63,japanese vgm,5qEtLvXzYdv0G7c7rR6irX,https://i.scdn.co/image/ab6761610000e5eb391264...,127388
21,Shin Giwon Piano,51,,0hKq3u04JU5IuGNSTGyngJ,https://i.scdn.co/image/ab6761610000e5ebf07222...,79977
22,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ,https://i.scdn.co/image/ab6761610000e5eb57138b...,18133553
23,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF,https://i.scdn.co/image/ab6761610000e5eb369406...,740421
24,amazarashi,55,"anime, j-rock, j-pop",6T4K8YuFc0JPDrYgABbxao,https://i.scdn.co/image/ab6761610000e5eb8c513f...,458301
25,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs,https://i.scdn.co/image/ab6761610000e5ebcb6017...,5678914
26,JENNIE,89,k-pop,250b0Wlc5Vk0CoUsaCY84M,https://i.scdn.co/image/ab6761610000e5eba8e362...,9713518
27,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p,https://i.scdn.co/image/ab6761610000e5eb593f35...,6904886
28,THE SIXTH LIE,40,"anime, j-rock, j-pop",2sCc8pMRgv99AweDSrFFZt,https://i.scdn.co/image/ab6761610000e5ebca92c4...,30465
29,結束バンド,63,"anime, j-rock, j-pop",2nvl0N9GwyX69RRBMEZ4OD,https://i.scdn.co/image/ab6761610000e5eb38df32...,603776
30,NAYEON,64,k-pop,1VwDG9aBflQupaFNjUru9A,https://i.scdn.co/image/ab6761610000e5eb8f7649...,2886118
31,アトラスサウンドチーム,70,"japanese vgm, soundtrack",4hFBhdNVZZuVk5FYThUwaN,https://i.scdn.co/image/ab6761610000e5eb5de4fc...,196082
32,LiSA,71,"anime, j-pop, j-rock",0blbVefuxOGltDBa00dspv,https://i.scdn.co/image/ab6761610000e5eb774ac8...,3369785
33,KISS OF LIFE,73,k-pop,4TEK9tIkcoxib4GxT3O4ky,https://i.scdn.co/image/ab6761610000e5eb33a8cc...,2125025
34,Ado,77,"j-pop, anime, vocaloid, j-rock",6mEQK9m2krja6X1cfsAjfl,https://i.scdn.co/image/ab6761610000e5ebf3bb04...,5845982
35,QWER,53,"k-rock, k-pop",0XufO9nLOKNN0w0qNrDrZy,https://i.scdn.co/image/ab6761610000e5ebdde5e6...,232146
36,TZUYU,52,k-pop,1arCVYXeStgCY2UazBNBLK,https://i.scdn.co/image/ab6761610000e5eb9f631e...,308199
37,Taylor Swift,98,,06HL4z0CvFAxyc27GXpf02,https://i.scdn.co/image/ab6761610000e5ebe672b5...,135368184
38,2NE1,62,k-pop,1l0mKo96Jh9HVYONcRl3Yp,https://i.scdn.co/image/ab6761610000e5ebcd3114...,2685867
39,milet,64,"j-pop, anime, j-rock",45ft4DyTCEJfQwTBHXpdhM,https://i.scdn.co/image/ab6761610000e5ebe56b36...,921887
40,Imagine Dragons,88,,53XhwfbYqKCa1cC15pYq2q,https://i.scdn.co/image/ab6761610000e5ebab47d8...,56910485
41,OFFICIAL HIGE DANDISM,71,"j-pop, anime, j-rock",5Vo1hnCRmCM6M4thZCInCj,https://i.scdn.co/image/ab6761610000e5ebf9f751...,7076192
42,Evan Call,62,anime,0nMGbTpPx4b3h5fMG9CpWJ,https://i.scdn.co/image/ab6761610000e5ebfaf4db...,66734
43,Red Velvet,70,k-pop,1z4g3DjTBBZKhvAroFlhOM,https://i.scdn.co/image/ab6761610000e5eb02a562...,9473578
44,SEULGI,63,k-pop,2QM5S4yO6xHgnNvF0nbZZq,https://i.scdn.co/image/ab6761610000e5eb9879ac...,1212276
45,Mrs. GREEN APPLE,82,"j-pop, anime, j-rock",4QvgGvpgzgyUOo8Yp8LDm9,https://i.scdn.co/image/ab6761610000e5eb968120...,5355036
46,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL,https://i.scdn.co/image/ab6761610000e5eb92d8ef...,978773
47,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...,57680795
48,LISA,83,k-pop,5L1lO4eRHmJ7a0Q6csE5cT,https://i.scdn.co/image/ab6761610000e5eb426fae...,11379854
49,Against The Current,64,pop punk,6yhD1KjhLxIETFF7vIRf8B,https://i.scdn.co/image/ab6761610000e5eb469aba...,528861