# Load Data

In [1]:
import pandas as pd
import numpy as np
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
import os
from pathlib import Path

# Extract credential access Spotify API

In [2]:
env_path = Path("..") / ".env"
load_dotenv(dotenv_path=env_path)
CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRET = os.getenv("CLIENT_SECRET")
REDIRECT_URI = os.getenv("REDIRECT_URI")

# Extract Spotify data

## Helper Functions

In [3]:
def extract_top_tracks_data(spotify_client,time_range)->pd.DataFrame:
    '''
    Convert JSON file extracted from spotify 
    to dataframe for analysis
    '''
    top_tracks_json = spotify_client.current_user_top_tracks(limit=50, time_range=time_range)
    track_list = []

    for item in top_tracks_json['items']:
        track_info = {
            'track_name':item['name'],
            'artist_name': item['artists'][0]['name'],
            'album_name': item['album']['name'],
            'album_id': item['album']['id'],
            'release_date': item['album']['release_date'],
            'popularity': item['popularity'],
            'duration_ms': item['duration_ms'],
            'explicit':item['explicit'],
            'track_id': item['id']
        }
        track_list.append(track_info)
    
    data = pd.DataFrame(track_list)
    data['duration_min'] = data['duration_ms']/60000
    data['release_date'] = pd.to_datetime(data['release_date'])

    return data

def extract_top_artist_data(spotify_client,time_range)->pd.DataFrame:
    '''
    Convert JSON file extracted from Spotify
    to dataframe for analysis
    '''
    top_artist_json = spotify_client.current_user_top_artists(limit = 50,time_range = time_range)
    artist_list = []
    for item in top_artist_json['items']:
        artist_info = {
            'artist_name':item['name'],
            'popularity':item['popularity'],
            'genres': ', '.join(item['genres']),
            'artist_id': item['id'],
            'followers': item['followers']['total'],
            # Gets the largest image if exists
            'image_url': item['images'][0]['url'] if item['images'] else None
        }
        artist_list.append(artist_info)
    data = pd.DataFrame(artist_list)
    return data

def get_albums_info(spotify_client,album_ids)->pd.DataFrame:
    '''
    Extract album information from top songs 
    '''
    album_data = [] 

    for i in range(0,len(album_ids),20):
        # Spotify API limit requests to 20 albums per call 
        batch = album_ids[i:i+20]
        albums = spotify_client.albums(batch)['albums']
        for album in albums:
            album_info = {
        'album_id': album['id'],
        'album_name': album['name'],
        'release_date': album['release_date'],
        'total_tracks': album['total_tracks'],
        'label': album.get('label', ''),
        'popularity': album.get('popularity'),
        'album_type': album['album_type'],
        'external_url': album['external_urls']['spotify'],
        'album_uri': album['uri'],
        'release_date_precision': album['release_date_precision'],
        'images': [image['url'] for image in album['images']] if album['images'] else [],  # List of images with varying sizes
        'genres': ', '.join(album['genres']) if 'genres' in album else '',  # Check if genres are present
        'artists': ', '.join([artist['name'] for artist in album['artists']]),  # Add artist names
        'track_ids': [track['id'] for track in album['tracks']['items']],  # Extract track IDs
        'available_markets': album.get('available_markets', []),  # Get available markets for the album
        }
            album_data.append(album_info)
    data = pd.DataFrame(album_data)
    return data

def get_tracks_info(spotify_client,track_ids)->pd.DataFrame:
    '''
    Extract additional information on top tracks
    '''
    track_data = [] 

    for i in range(0,len(track_ids),50):
        batch = track_ids[i:i+50]
        tracks = spotify_client.tracks(batch)['tracks']
        for track in tracks:
            track_info = {
                'track_id':track['id'],
                'track_name':track['name'],
                'popularity':track['popularity'],
                'explicit':track['explicit'],
                'artist_id':track['artists'][0]['id'],
                'album_id':track['album']['id'],
                # URL provide 30s preview of track
                'preview_url':track.get('preview_url',''),
                # URL of track page in spotify 
                'track_url':track['external_urls']['spotify'],
                # External Identifier to track songs globally
                'track_external_id':track['external_ids'].get('isrc',''),
                # Check whether track saved in user device
                'is_local':track['is_local'],
            }
            track_data.append(track_info)

    track_data = pd.DataFrame(track_data)
    return track_data

# Fetch Top Tracks

In [4]:
# Optional: remove existing cache for fresh login
if os.path.exists(".cache-my-music-app"):
    os.remove(".cache-my-music-app")

# Create the OAuth object
sp_oauth = SpotifyOAuth(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    redirect_uri=REDIRECT_URI,
    scope=["user-top-read", "user-library-read", "playlist-read-private"],
    cache_path=".cache-my-music-app"
)

# Create the Spotify client using the SpotifyOAuth instance directly
sp = spotipy.Spotify(auth_manager=sp_oauth)

# Test API call
try:
    results = sp.current_user_top_tracks(limit=10)
    for idx, item in enumerate(results['items']):
        print(f"{idx+1}. {item['name']} - {item['artists'][0]['name']}")
except spotipy.exceptions.SpotifyException as e:
    print(f"Error: {e}")

print("Fetching your top tracks...")
top_tracks = sp.current_user_top_tracks(
    limit=50, time_range='medium_term'
    )

short_term_track_data = extract_top_tracks_data(sp,'short_term')
medium_term_track_data = extract_top_tracks_data(sp,'medium_term')
long_term_track_data = extract_top_tracks_data(sp,'long_term')

1. CASANOVA POSSE - ALI
2. HER - MINNIE
3. Imaginary Friend - ITZY
4. Air - YEJI
5. I TRUST YOU - エミリア(CV:高橋李依)
6. Shopper - IU
7. Secret - IU
8. Whiplash - aespa
9. FREAK - YUQI
10. NEMONEMO - YENA
Fetching your top tracks...

In [5]:
long_term_track_data

,track_name,artist_name,album_name,album_id,release_date,popularity,duration_ms,explicit,track_id,duration_min
0,Nobody - from Kaiju No. 8,OneRepublic,Nobody (from Kaiju No. 8),3YmKf1haPAblZIrIPpuRTf,2024-04-12,70,153626,False,47N81NMkB488fuOwOC3Oip,2.560433
1,I GOT YOU,TWICE,I GOT YOU,6RZHj6L3NqrvcKeiBHQbjL,2024-02-02,59,173240,False,35dhwUoJNlxrPyEIJkfDnx,2.887333
2,FREAK,YUQI,YUQ1,7LYc8ngbhwha4aGJ5kVauc,2024-04-23,57,171080,False,6ERs9uORCo1MfV0m9ixCuv,2.851333
3,DIVE,TWICE,DIVE,0riep5s1F9ynpobjOSzbcr,2024-07-10,57,181860,False,5vK3WrTOp6rEoASx1jAsp1,3.031000
4,Fate,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,62,161546,False,2vNPGH1x5ZwxTjlvzLCyc2,2.692433
5,Doughnut,TWICE,Celebrate,1nqz3cEjuvCMo8RHLBI9kM,2022-07-27,53,263680,False,65rmgd5uMb4Rgqb5dSiU0p,4.394667
6,MORE & MORE,TWICE,MORE & MORE,5KsduuDNWzt65TaHzmtciv,2020-06-01,63,199653,False,3omvXShuRPM3zbDpWYqf5g,3.327550
7,Red Rover,YUQI,YUQ1,7LYc8ngbhwha4aGJ5kVauc,2024-04-23,48,123320,False,4TQBHR8LcbBUv0LvLmn54H,2.055333
8,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,20Bf2RVERC5Bc2eo3vyvJv,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550
9,YES or YES,TWICE,YES or YES,25VunQEW0x2W6ALND2Mh4g,2018-11-05,68,237680,False,26OVhEqFDQH0Ij77QtmGP9,3.961333
10,"""good guy""",Against The Current,"""good guy""",6bj1lsHiVqvJyqjv7qtrV4,2023-04-21,48,208052,True,3bfElZNhtvtGvWMVgCBgZK,3.467533
11,Shopper,IU,The Winning,08CvAj58nVMpq1Nw7T6maj,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333
12,POP!,NAYEON,IM NAYEON,0wqjfojWuTcbEvwaizvTMw,2022-06-24,72,168106,False,3lOMJTQTd6J34faYwASc33,2.801767
13,青のすみか,Tatsuya Kitani,青のすみか,4QjNVlIw8Rx6jItSZtn2VS,2023-07-07,72,196466,False,12usPU2WnqgCHAW1EK2dfd,3.274433
14,CASANOVA POSSE,ALI,CASANOVA POSSE,2xfq9tUp4QOlCGT6j4k0g9,2025-01-10,65,240653,False,26Lip4WX1oWceF9tb8m2qw,4.010883
15,Talk that Talk,TWICE,BETWEEN 1&2,3NZ94nQbqimcu2i71qhc4f,2022-08-26,69,177466,False,0RDqNCRBGrSegk16Avfzuq,2.957767
16,Perfect World,TWICE,Perfect World,17rk8h2IU4wwSFXw9j2uR6,2021-07-28,58,182680,False,0iuZMy88H6vxDA2oaJNhJg,3.044667
17,晴る,ヨルシカ,晴る,4O53dhmIctih3p2suAAgga,2024-01-05,74,270705,False,5eY7692tmgHB9dbmq6wa2M,4.511750
18,Super Lady,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,64,152186,False,5qI5EUqfDJpQ7w6sMECK7U,2.536433
19,Long Live (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),5AEDGbliTTfjOB8TSm1sxt,2023-07-07,73,317960,False,4hqJ4bSlYJOXb6Z4SRmzxs,5.299333
20,Klaxon,(G)I-DLE,I SWAY,5WzUVTkKAvOayPui3DnsDz,2024-07-08,63,175106,False,294hRgOqnGW2BemqP8D35X,2.918433
21,No Celestial,LE SSERAFIM,ANTIFRAGILE,3u0ggfmK0vjuHMNdUbtaa9,2022-10-17,60,166491,False,21ApmVGIzIAIDSBdHu6SVt,2.774850
22,ONE SPARK,TWICE,With YOU-th,575TQDOQqc0MAheeEeKWUR,2024-02-23,67,183559,False,7cIn67LEvk16v6komC8znS,3.059317
23,Live My Life,aespa,Armageddon - The 1st Album,3gHhPm8z8tid1kvpniUKuK,2024-05-27,63,159133,False,1x1oCGsFUDViOvcISuoKW0,2.652217
24,Imaginary Friend,ITZY,GOLD,4CRfobFgSG0GOzplgTI79s,2024-10-15,66,202429,False,06BeeZaS4YArThfTMu80QS,3.373817
25,Air,YEJI,AIR,6sJnzoRI9pXUo0gZxIviUS,2025-03-10,75,194800,False,6HSns0qPQQfgekCrBF0Dkf,3.246667
26,HER,MINNIE,HER,3sbZ4PoHTIZL8bLSLwt84h,2025-01-21,69,159797,False,2MbPhDgeXVipowltFneRH2,2.663283
27,境界線,amazarashi,七号線ロストボーイズ,0pqrWNxpcWBvR9A5A9JHHl,2022-04-13,48,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550
28,I TRUST YOU,エミリア(CV:高橋李依),"SONG FROM TV SERIES ""RE:ZERO -STARTING LIFE IN...",530vXGXkG5czn3hHdMPSMD,2024-11-14,34,255396,False,7Ccvd3UVSfORSNyeOO069h,4.256600
29,Alcohol-Free,TWICE,Taste of Love,00vb6sViDbJLmLLchfbRh4,2021-06-11,66,210573,False,0BTaaKT4RMbs5M73tOHX5Y,3.509550
30,Beyond the Horizon,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,47,212826,False,27f7ZEBoJIJ3HzOpzqmDqO,3.547100
31,Ocean Deep,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,47,220106,False,6jya1u1sEhObLCDFGyWuAW,3.668433
32,Sunshine,OneRepublic,Sunshine,2YSlIS6gM38w7ZJNj8F3s6,2021-11-10,74,163854,False,5r43qanLhUCdBj8HN3fa6B,2.730900
33,LOVE FOOLISH,TWICE,Feel Special,3NQBPabmRm3LzVcmtkTLfo,2019-09-23,53,191226,False,1MdEg2lk4EakgWnCvFUGEZ,3.187100
34,DIVE,TWICE,DIVE,7tgTOUXm74GKA12wsQIUPu,2024-07-17,57,181860,False,3JstVDAZKy4O8SZ5yoXdQr,3.031000
35,Feel Special,TWICE,Feel Special,3NQBPabmRm3LzVcmtkTLfo,2019-09-23,71,206866,False,3Hz3tTQwOdM6XkA0ALB2G9,3.447767
36,Hare Hare,TWICE,Hare Hare,7hF6oiU4zaIQIGjLhje1eG,2023-05-31,46,203546,False,3QcJghvqRS17RoPPP0C2sp,3.392433
37,MOONLIGHT SUNRISE,TWICE,READY TO BE,7hzP5i7StxYG4StECA0rrJ,2023-03-10,61,180320,False,5IN9W6eUfk3014My9awagX,3.005333
38,Baby Blue Love,TWICE,Taste of Love,00vb6sViDbJLmLLchfbRh4,2021-06-11,50,166666,False,7Jzo3IObpANz6giPTUrihB,2.777767
39,Wife,(G)I-DLE,Wife,0C8qSTYZDkVcfnY6tIHIzK,2024-01-21,56,121226,False,6hWU8LrnjLyYHShDyNWFZj,2.020433
40,Secret,IU,Last Fantasy,149BHv6qAyMgJ483vPi77C,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867
41,Likey,TWICE,Twicetagram,3hJXmK5gWN9P6jtZL0Lr2y,2017-10-30,66,207813,False,0IEVKWduAaMcZepZQVr80T,3.463550
42,Mine (Taylor's Version),Taylor Swift,Speak Now (Taylor's Version),5AEDGbliTTfjOB8TSm1sxt,2023-07-07,74,231706,False,7G0gBu6nLdhFDPRLc0HdDG,3.861767
43,Whiplash,aespa,Whiplash - The 5th Mini Album,3OaW4df1SA62k0arNpn6bK,2024-10-21,78,183226,False,6uPnrBgweGOcwjFL4ItAvV,3.053767
44,I GOT YOU,TWICE,With YOU-th,575TQDOQqc0MAheeEeKWUR,2024-02-23,54,173240,False,0mgveJEIGjcN51w4JIQtI6,2.887333
45,ABCD,NAYEON,NA,5zQI9dFbS9TrhvC9clgjz7,2024-06-14,72,162840,False,0V2passWyAXnON67kfAj7y,2.714000
46,Wife,(G)I-DLE,2,0mC9MXPddkzggVsOXh5gd3,2024-01-29,60,121226,False,1j8jqwFpFQ8YqsIJAiYFLZ,2.020433
47,Killin’ Me Good,JIHYO,ZONE,1GIkapvyAw5lwdNw66hI44,2023-08-18,64,185920,False,4Cyf87ul1le0xTWRFBoYd7,3.098667
48,NEMONEMO,YENA,NEMONEMO,6FLiJ4318RtpA5lYWJt2cL,2024-09-30,67,178026,False,4UwsXGVppRRJpKBHy0mtyK,2.967100
49,Just Imagine It,MKTO,Bad Girls EP,1TCiADBOmKJgdxULZPrK2a,2015-07-24,50,250746,False,0mtmrbRFsectINNpHdDkUQ,4.179100

In [6]:
short_term_track_data

,track_name,artist_name,album_name,album_id,release_date,popularity,duration_ms,explicit,track_id,duration_min
0,Air,YEJI,Air,4ILxYaUCwfA9EJ36wPwTWz,2025-03-10,55,194800,False,2HhIndg75YiKjuUgGiMjSA,3.246667
1,Draw the Moon (feat. MIYAVI),MINNIE,"Webtoon <Myst, Might, Mayhem> OST Part. 2 Draw...",2dD84O2WUFNCjs963yWsbh,2025-03-21,45,210146,False,4B3JCEcAeTofpsfsEianeS,3.502433
2,Radio (Dum-Dum),YUQI,Radio (Dum-Dum),1jrJTnOMuLs5v0qTDTc0kR,2025-03-17,67,152373,False,0mXXjVVAhaasNXga2HMgJK,2.539550
3,I,TAEYEON,I - The 1st Mini Album,4e7kLQu7SKBUiMtV5WH3A1,2015-10-07,61,206038,False,5ZkITfPpcNPnyYGTibkO6m,3.433967
4,Invasion,YEJI,Air,4ILxYaUCwfA9EJ36wPwTWz,2025-03-10,40,167800,False,3ePablAj7jk2c1j5CKEtAv,2.796667
5,HAPPY,DAY6,Fourever,29pgfsXVV0cLsvfylWRZJ9,2024-03-18,64,189934,False,1k68vKHNQXU5CHqcM7Yp7N,3.165567
6,"Can’t Slow Me, No",YEJI,Air,4ILxYaUCwfA9EJ36wPwTWz,2025-03-10,38,178573,False,7EbaA7z7wP3G7xfYZVlVJS,2.976217
7,Shopper,IU,The Winning,08CvAj58nVMpq1Nw7T6maj,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333
8,SMILEY-Japanese Ver.- (feat.ちゃんみな),YENA,SMILEY-Japanese Ver.- (feat.ちゃんみな),405JFvqLG79ifF84IKlWJC,2023-08-07,39,176882,False,4RhkH4fGvvEzxvRlUcYH9L,2.948033
9,NEMONEMO,YENA,NEMONEMO,6FLiJ4318RtpA5lYWJt2cL,2024-09-30,67,178026,False,4UwsXGVppRRJpKBHy0mtyK,2.967100
10,Lxxk 2 U,YENA,ˣ‿ˣ (SMiLEY),7qldKtsOWklzmwgll5NjCw,2022-01-17,43,182853,False,5U7emXCoCl8EOEJUVNbguC,3.047550
11,Supernova,aespa,Armageddon - The 1st Album,3vk3MR4IL2EMC4ksN5pCo4,2024-05-27,64,178880,False,2JhbSmNAyM9kYiqwa8Tpla,2.981333
12,FOREVER,BABYMONSTER,DRIP,7JCNpE1d2ivc2YPSqEVShc,2024-11-01,62,212734,False,7a6vvAM1cjAuyVQpqv9pmu,3.545567
13,Autumn morning,IU,가을 아침 [Gaeul Achim] : Autumn morning,4QvzYMXuU58cNpFrRQ9Aqi,2017-09-22,49,218884,False,100N8P8WYnz9eCYuLYGflV,3.648067
14,Secret,IU,Last Fantasy,149BHv6qAyMgJ483vPi77C,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867
15,Whiplash,aespa,Whiplash - The 5th Mini Album,6RRuiUup6Z0Y0MxkCXOGyU,2024-10-21,73,183226,False,7Cnpb1vBbC46RgVyyKLH7p,3.053767
16,HER,MINNIE,HER,7a5VJXSKmOJLyWYDKsGubq,2025-01-21,45,159797,False,1Jm2piFQ1Nq3fGHwu3fyvT,2.663283
17,ひたむき,SUPER BEAVER,音楽,2CBL0ep4HNPCrCkQGhWJ1M,2024-02-21,50,246800,False,4Jp91ygcS0CBz8MwtvoBrU,4.113333
18,Well… (ROCK VER.),IU,Growing Up,2xJZSgxlKvcOCR2aLA8Pq2,2009-04-23,39,190589,False,6zpiGeoHYRF5vtrboE3rAC,3.176483
19,Live My Life,aespa,Armageddon - The 1st Album,3vk3MR4IL2EMC4ksN5pCo4,2024-05-27,58,159133,False,71lnolmea3IZeG90Gj7jHg,2.652217
20,WithOrWithOut,YENA,SMARTPHONE,0lbUf1aVf8xmveSuspuNW0,2022-08-03,34,191973,False,5tazcUyCvfGdRWC1Da5rCS,3.199550
21,Obsession (feat. TEN),MINNIE,HER,7a5VJXSKmOJLyWYDKsGubq,2025-01-21,27,222541,False,6sEqkiXe4vRNIhOvNdZzL1,3.709017
22,My Stupid Heart (with Lauv),Walk off the Earth,My Stupid Heart (with Lauv),6yT57VsTlEjkZz6539dA8i,2023-03-03,52,160866,False,1SVOLTmC627fn0XY9ltvx2,2.681100
23,BAHAMA,aespa,Armageddon - The 1st Album,3vk3MR4IL2EMC4ksN5pCo4,2024-05-27,44,190533,False,1FXNYp47arDhsngAsHSG9v,3.175550
24,境界線,amazarashi,七号線ロストボーイズ,0pqrWNxpcWBvR9A5A9JHHl,2022-04-13,48,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550
25,Hate Rodrigo (Feat. YUQI),YENA,HATE XX,3aYLtPSWEqmcLTCfM0ZYl7,2023-06-27,54,181013,False,5ms7rcVKjBFUtoVh8hE0Y9,3.016883
26,Letter To Myself,TAEYEON,Letter To Myself - The 6th Mini Album,47f7hcYu2nGCYcRx5d8zCM,2024-11-18,63,184060,False,1Uxr0oBXAZRuLkAz27TkLc,3.067667
27,REBEL HEART,IVE,REBEL HEART,7wDskR5Q6K1qqLPEG8W8kB,2025-01-13,66,188266,False,1jtlHteF4y7FFHKgYFld4f,3.137767
28,I Don't Wanna Wait,David Guetta,I Don't Wanna Wait,0wCLHkBRKcndhMQQpeo8Ji,2024-04-05,85,149667,False,331l3xABO0HMr1Kkyh2LZq,2.494450
29,PINK YOUR MOMENT,MINNIE,PINK YOUR MOMENT,3zSmrdJtL6jp6H6KKYMu7a,2023-04-26,16,131306,False,3CH6RNIVix2lZp9awUfOSQ,2.188433
30,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,20Bf2RVERC5Bc2eo3vyvJv,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550
31,Getaway,MINNIE,"My Dangerous Wife, Pt. 2 (Original Television ...",7nwFxexvXGarWydafSsUrC,2020-10-11,34,228080,False,41nBWFdECOtxYnygCpL6AH,3.801333
32,This Is The New Shit,Marilyn Manson,The Golden Age Of Grotesque,3KExM8E3KgpsS2bHVSJzTc,2003-01-01,63,259666,True,5P13mfqn9o3ToFPTxowEgO,4.327767
33,LEveL,SawanoHiroyuki[nZk],bLACKbLUE,1ulr9SX47HJ1SNRvGPFOli,2024-10-02,54,182653,False,5hakB3OS30xHJsWq6mqty7,3.044217
34,Into the Unknown (End Credit Version),TAEYEON,Frozen 2 (Korean Original Motion Picture Sound...,7JWtvxwYAwzuSDPzvbvXHP,2019-11-15,40,189120,False,4OkHootAlj7w9Eb2zJVlWr,3.152000
35,APT.,ROSÉ,rosie,7kFyd5oyJdVX2pIi6P4iHE,2024-12-06,92,169917,False,4wJ5Qq0jBN4ajy7ouZIV1c,2.831950
36,258,YEJI,Air,4ILxYaUCwfA9EJ36wPwTWz,2025-03-10,41,193040,False,6jZP2gYURZhXxh45vMAliR,3.217333
37,造浪 - 《我要逆风去》电视剧主题曲,YUQI,造浪 (《我要逆风去》电视剧主题曲),4O6qchYcxBl6LunbOAhwxj,2024-06-25,36,188307,False,0tNwt2ZBNkelLrLnZqOC2H,3.138450
38,Sugar,YENA,NEMONEMO,6FLiJ4318RtpA5lYWJt2cL,2024-09-30,49,166653,False,1T3HuFlijT5Uu4pZI60tgr,2.777550
39,50 Ways to Say Goodbye,Train,California 37,5zseibu9WEsPaZmkJUMkz1,2012-04-17,70,247946,False,2NniAhAtkRACaMeYt48xlD,4.132433
40,SMILEY(Feat. BIBI),YENA,ˣ‿ˣ (SMiLEY),7qldKtsOWklzmwgll5NjCw,2022-01-17,60,173413,False,4zCIxSnVWpGNghERX4uWZF,2.890217
41,KIDDING ME,ITZY,GUESS WHO,2XpMmJUrM3e5qdCUpJqXA7,2021-04-30,24,213960,False,1muZkKwVHfv8hS77RG2G2I,3.566000
42,Nobody - from Kaiju No. 8,OneRepublic,Artificial Paradise (Deluxe),4yHDaLGrPSwUfJNVUIvFgg,2024-07-12,63,153626,False,3SiVMpHxTS1gspWzRZE50S,2.560433
43,My Universe,Coldplay,Music Of The Spheres,06mXfvDsRZNfnsGZvX2zpb,2021-10-15,77,226198,False,46HNZY1i7O6jwTA7Slo2PI,3.769967
44,UP - KARINA Solo,aespa,SYNK : PARALLEL LINE - Special Digital Single,4vLGHlTnlIIxMSfefCY0cU,2024-10-09,80,166640,False,5sjnkOfTLCLNfkkchI2re2,2.777333
45,Your Love,JISOO,AMORTAGE,1hmW4opQGq4hIYTbEWsyqW,2025-02-14,78,173232,False,6TPpCbn9z0IY5Te048iy5R,2.887200
46,Armageddon,aespa,Armageddon - The 1st Album,3vk3MR4IL2EMC4ksN5pCo4,2024-05-27,61,196466,False,6lAvyeD3Nq43AjyCxZQj54,3.274433
47,Rum Pum Pum Pum,aespa,"2025 SMTOWN : THE CULTURE, THE FUTURE",7tbmvcs2vAe7mijL8Pfven,2025-02-14,61,209613,False,00M2YcEqhsVbSW6RUKqIY3,3.493550
48,spiral,LONGMAN,10/4,1puG16lwC2NGE5nmlj0eab,2023-10-04,45,231746,False,18Y6TCF80HYi0Fu53xcUge,3.862433
49,BAD HOBBY,YENA,HATE XX,3aYLtPSWEqmcLTCfM0ZYl7,2023-06-27,41,131013,False,4XGOlD2OFGPHXLA0DBPr5M,2.183550

# Fetch Top Artist

In [7]:
extract_top_artist_data(sp,'short_term')

,artist_name,popularity,genres,artist_id,followers,image_url
0,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE,8361617,https://i.scdn.co/image/ab6761610000e5ebf7a109...
1,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN,807593,https://i.scdn.co/image/ab6761610000e5eb1135e1...
2,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU,9135223,https://i.scdn.co/image/ab6761610000e5ebbd0642...
3,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu,3064731,https://i.scdn.co/image/ab6761610000e5ebb5d9eb...
4,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX,761745,https://i.scdn.co/image/ab6761610000e5eb0134f9...
5,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0,21665446,https://i.scdn.co/image/ab6761610000e5ebca6c14...
6,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3,8351660,https://i.scdn.co/image/ab6761610000e5eb344806...
7,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m,114620,https://i.scdn.co/image/ab6761610000e5eb485cfb...
8,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6,833634,https://i.scdn.co/image/ab6761610000e5eb569026...
9,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl,3607044,https://i.scdn.co/image/ab6761610000e5ebb75519...
10,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx,10489801,https://i.scdn.co/image/ab6761610000e5eb7fd163...
11,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ,5451531,https://i.scdn.co/image/ab6761610000e5eb538dad...
12,THE SIXTH LIE,40,"anime, j-rock, j-pop",2sCc8pMRgv99AweDSrFFZt,30484,https://i.scdn.co/image/ab6761610000e5ebca92c4...
13,KISS OF LIFE,73,k-pop,4TEK9tIkcoxib4GxT3O4ky,2125187,https://i.scdn.co/image/ab6761610000e5eb33a8cc...
14,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p,6909574,https://i.scdn.co/image/ab6761610000e5eb593f35...
15,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS,4271004,https://i.scdn.co/image/ab6761610000e5ebb419d6...
16,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo,994169,https://i.scdn.co/image/ab6761610000e5eb8bb041...
17,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF,740603,https://i.scdn.co/image/ab6761610000e5eb369406...
18,SEULGI,63,k-pop,2QM5S4yO6xHgnNvF0nbZZq,1212544,https://i.scdn.co/image/ab6761610000e5eb9879ac...
19,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs,5685017,https://i.scdn.co/image/ab6761610000e5eb9e33dd...
20,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL,979380,https://i.scdn.co/image/ab6761610000e5eb92d8ef...
21,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik,3032922,https://i.scdn.co/image/ab6761610000e5ebe62cff...
22,CSR,35,"bubblegum pop, k-pop",06MX3Ecb8PHyNFmq8irTWC,90161,https://i.scdn.co/image/ab6761610000e5eba6b8bd...
23,SOOJIN,43,k-pop,0kB3Vlf3xDNZQz6NjAPJV8,431729,https://i.scdn.co/image/ab6761610000e5ebc013b5...
24,TEN,68,k-pop,3Q5Qep7ytrjVleNnMnntgQ,843666,https://i.scdn.co/image/ab6761610000e5eb8f8c7f...
25,G-DRAGON,76,"k-pop, k-rap",30b9WulBM8sFuBo17nNq9c,3461202,https://i.scdn.co/image/ab6761610000e5eb783a6a...
26,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ,18137033,https://i.scdn.co/image/ab6761610000e5eb57138b...
27,DAY6,69,"k-rock, k-pop",5TnQc2N1iKlFjYD7CPGvFc,3670925,https://i.scdn.co/image/ab6761610000e5eb10e83b...
28,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V,119923718,https://i.scdn.co/image/ab6761610000e5eb399444...
29,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU,57698296,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...
30,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX,810891,https://i.scdn.co/image/ab6761610000e5ebf9736f...

In [8]:
extract_top_artist_data(sp,'long_term')

,artist_name,popularity,genres,artist_id,followers,image_url
0,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0,21665446,https://i.scdn.co/image/ab6761610000e5ebca6c14...
1,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx,10489801,https://i.scdn.co/image/ab6761610000e5eb7fd163...
2,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V,119923718,https://i.scdn.co/image/ab6761610000e5eb399444...
3,Taylor Swift,98,,06HL4z0CvFAxyc27GXpf02,135420613,https://i.scdn.co/image/ab6761610000e5ebe672b5...
4,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU,9135223,https://i.scdn.co/image/ab6761610000e5ebbd0642...
5,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3,8351660,https://i.scdn.co/image/ab6761610000e5eb344806...
6,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE,8361617,https://i.scdn.co/image/ab6761610000e5ebf7a109...
7,Against The Current,64,pop punk,6yhD1KjhLxIETFF7vIRf8B,528949,https://i.scdn.co/image/ab6761610000e5eb469aba...
8,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX,761745,https://i.scdn.co/image/ab6761610000e5eb0134f9...
9,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ,5451531,https://i.scdn.co/image/ab6761610000e5eb538dad...
10,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6,833634,https://i.scdn.co/image/ab6761610000e5eb569026...
11,BURNOUT SYNDROMES,56,"anime, j-rock, j-pop",0Oazwl71qoHvXnbSxv0wOT,290783,https://i.scdn.co/image/ab6761610000e5eb6a9d23...
12,結束バンド,63,"anime, j-rock, j-pop",2nvl0N9GwyX69RRBMEZ4OD,604207,https://i.scdn.co/image/ab6761610000e5eb38df32...
13,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN,807593,https://i.scdn.co/image/ab6761610000e5eb1135e1...
14,Fall Out Boy,80,"emo, pop punk, emo pop",4UXqAaa6dQYAk18Lv7PEgX,11219001,https://i.scdn.co/image/ab6761610000e5eb362011...
15,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik,3032922,https://i.scdn.co/image/ab6761610000e5ebe62cff...
16,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS,4271004,https://i.scdn.co/image/ab6761610000e5ebb419d6...
17,MKTO,67,,2l35CQqtYRh3d8ZIiBep4v,1106949,https://i.scdn.co/image/ab6761610000e5ebbc861f...
18,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX,810891,https://i.scdn.co/image/ab6761610000e5eb9cc45f...
19,NAYEON,64,k-pop,1VwDG9aBflQupaFNjUru9A,2888086,https://i.scdn.co/image/ab6761610000e5eb8f7649...
20,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo,994169,https://i.scdn.co/image/ab6761610000e5eb8bb041...
21,YOASOBI,76,"j-pop, anime",64tJ2EAv1R6UaZqc4iOCyj,8997684,https://i.scdn.co/image/ab6761610000e5ebbfdd8a...
22,Owl City,70,,07QEuhtrNmmZ0zEcqE9SF6,2486691,https://i.scdn.co/image/ab6761610000e5ebce3fbd...
23,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ,18137033,https://i.scdn.co/image/ab6761610000e5eb57138b...
24,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU,57698296,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...
25,LiSA,71,"anime, j-pop, j-rock",0blbVefuxOGltDBa00dspv,3370607,https://i.scdn.co/image/ab6761610000e5eb774ac8...
26,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p,6909574,https://i.scdn.co/image/ab6761610000e5eb593f35...
27,The Cab,56,,2C2sVVXanbOpymYBMpsi89,561668,https://i.scdn.co/image/ff6eb786aff45ab50e9820...
28,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu,3064731,https://i.scdn.co/image/ab6761610000e5ebb5d9eb...
29,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL,979380,https://i.scdn.co/image/ab6761610000e5eb92d8ef...
30,RADWIMPS,74,"anime, j-pop, j-rock",1EowJ1WwkMzkCkRomFhui7,4455350,https://i.scdn.co/image/ab6761610000e5eb78cca9...
31,Ado,77,"j-pop, anime, vocaloid, j-rock",6mEQK9m2krja6X1cfsAjfl,5850156,https://i.scdn.co/image/ab6761610000e5ebbcb1c1...
32,Konomi Suzuki,53,"anime, j-pop, j-rock",3O0kLS5sLZ41XZRxjBKmLF,218930,https://i.scdn.co/image/ab6761610000e5ebce9e87...
33,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m,114620,https://i.scdn.co/image/ab6761610000e5eb485cfb...
34,Relaxu,45,,7Glr8id1TfFSYoK04ENmNK,7874,https://i.scdn.co/image/ab6761610000e5eb73b8b4...
35,BoyWithUke,73,,1Cd373x8qzC7SNUg5IToqp,4495994,https://i.scdn.co/image/ab6761610000e5ebc69a43...
36,Paramore,82,"pop punk, emo, emo pop",74XFHRwlV6OrjEM0A2NCMF,9302550,https://i.scdn.co/image/ab6761610000e5ebb10c34...
37,BAND-MAID,52,"j-rock, k-rock",5Wh3G01Xfxn2zzEZNpuYHH,332808,https://i.scdn.co/image/ab6761610000e5eb3dc779...
38,Lyn,63,japanese vgm,5qEtLvXzYdv0G7c7rR6irX,127494,https://i.scdn.co/image/ab6761610000e5eb391264...
39,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs,5685017,https://i.scdn.co/image/ab6761610000e5eb9e33dd...
40,Glee Cast,70,christmas,0SCbttzoZTnLFebDYmAWCm,1537373,https://i.scdn.co/image/5b5a95f260ac429405e871...
41,ROSÉ,86,k-pop,3eVa5w3URK5duf6eyVDbu9,10941714,https://i.scdn.co/image/ab6761610000e5eb727a1f...
42,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF,740603,https://i.scdn.co/image/ab6761610000e5eb369406...
43,MindaRyn,43,anime,7MSns7VCEysJJhcp67gvtZ,46241,https://i.scdn.co/image/ab6761610000e5eb4e52ed...
44,TZUYU,52,k-pop,1arCVYXeStgCY2UazBNBLK,308945,https://i.scdn.co/image/ab6761610000e5eb9f631e...
45,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl,3607044,https://i.scdn.co/image/ab6761610000e5ebb75519...
46,fripSide,51,"anime, j-pop, j-rock",7ucOhItVkxNqunNLo8AkzN,237351,https://i.scdn.co/image/ab6761610000e5eb799924...
47,amazarashi,55,"anime, j-rock, j-pop",6T4K8YuFc0JPDrYgABbxao,458389,https://i.scdn.co/image/ab6761610000e5eb8c513f...
48,BLACKPINK,80,k-pop,41MozSoPIsD1dJM0CLPjZF,53481762,https://i.scdn.co/image/ab6761610000e5ebc9690b...
49,Panic! At The Disco,78,emo,20JZFwl6HVl6yg8a4H3ZqK,12576152,https://i.scdn.co/image/ab6761610000e5ebb256ae...

In [9]:
extract_top_artist_data(sp,'medium_term')

,artist_name,popularity,genres,artist_id,followers,image_url
0,aespa,80,k-pop,6YVMFz59CuY7ngCxTxjpxE,8361617,https://i.scdn.co/image/ab6761610000e5ebf7a109...
1,IU,70,"k-pop, k-ballad",3HqSLMAZ3g3d5poNaI7GOU,9135223,https://i.scdn.co/image/ab6761610000e5ebbd0642...
2,MINNIE,63,k-pop,2pHkxVNynHBwQHhGaoBIXX,761745,https://i.scdn.co/image/ab6761610000e5eb1a9a17...
3,YUQI,60,k-pop,22aCD8IrQZjcPgZw728QT6,833634,https://i.scdn.co/image/ab6761610000e5eb569026...
4,TWICE,79,k-pop,7n2Ycct7Beij7Dj7meI4X0,21665446,https://i.scdn.co/image/ab6761610000e5ebca6c14...
5,(G)I-DLE,73,k-pop,2AfmfGFbe0A0WsTYm0SDTx,10489801,https://i.scdn.co/image/ab6761610000e5eb7fd163...
6,ITZY,69,k-pop,2KC9Qb60EaY0kW4eH68vr3,8351660,https://i.scdn.co/image/ab6761610000e5eb344806...
7,IVE,75,k-pop,6RHTUrRF63xao58xh9FXYJ,5451531,https://i.scdn.co/image/ab6761610000e5eb538dad...
8,YENA,56,k-pop,49muoiIu4uea4PO8vueUNN,807593,https://i.scdn.co/image/ab6761610000e5eb1135e1...
9,Ed Sheeran,89,soft pop,6eUKZXaKkcviH0Ku9w2n3V,119923718,https://i.scdn.co/image/ab6761610000e5eb784daf...
10,TAEYEON,67,"k-pop, k-ballad",3qNVuliS40BLgXGxhdBdqu,3064731,https://i.scdn.co/image/ab6761610000e5ebb5d9eb...
11,MISAMO,61,k-pop,0IwZVmMMGE7nNXS7vN9SIo,994169,https://i.scdn.co/image/ab6761610000e5eb8bb041...
12,YEJI,61,k-pop,3skli1w2n0nOZ4qkDbvV2m,114620,https://i.scdn.co/image/ab6761610000e5eb485cfb...
13,Relaxu,45,,7Glr8id1TfFSYoK04ENmNK,7874,https://i.scdn.co/image/ab6761610000e5eb73b8b4...
14,YOASOBI,76,"j-pop, anime",64tJ2EAv1R6UaZqc4iOCyj,8997684,https://i.scdn.co/image/ab6761610000e5ebbfdd8a...
15,BABYMONSTER,76,k-pop,1SIocsqdEefUTE6XKGUiVS,4271004,https://i.scdn.co/image/ab6761610000e5ebb419d6...
16,ROSÉ,86,k-pop,3eVa5w3URK5duf6eyVDbu9,10941714,https://i.scdn.co/image/ab6761610000e5eb727a1f...
17,Walk off the Earth,60,,6jEiUoyyJNPHzSR0Nib6HX,810891,https://i.scdn.co/image/ab6761610000e5eb9cc45f...
18,ヨルシカ,74,"j-pop, j-rock, japanese indie, anime",4UK2Lzi6fBfUi9rpDt6cik,3032922,https://i.scdn.co/image/ab6761610000e5ebe62cff...
19,NMIXX,71,k-pop,28ot3wh4oNmoFOdVajibBl,3607044,https://i.scdn.co/image/ab6761610000e5ebb75519...
20,Lyn,63,japanese vgm,5qEtLvXzYdv0G7c7rR6irX,127494,https://i.scdn.co/image/ab6761610000e5eb391264...
21,Shin Giwon Piano,51,,0hKq3u04JU5IuGNSTGyngJ,80010,https://i.scdn.co/image/ab6761610000e5ebf07222...
22,OneRepublic,84,soft pop,5Pwc4xIPtQLFEnJriah9YJ,18137033,https://i.scdn.co/image/ab6761610000e5eb57138b...
23,MIYEON,47,k-pop,779v40cWIJUUoIDtC1IGaF,740603,https://i.scdn.co/image/ab6761610000e5eb369406...
24,amazarashi,55,"anime, j-rock, j-pop",6T4K8YuFc0JPDrYgABbxao,458389,https://i.scdn.co/image/ab6761610000e5eb8c513f...
25,JISOO,74,k-pop,6UZ0ba50XreR4TM8u322gs,5685017,https://i.scdn.co/image/ab6761610000e5eb9e33dd...
26,JENNIE,89,k-pop,250b0Wlc5Vk0CoUsaCY84M,9726022,https://i.scdn.co/image/ab6761610000e5ebcab652...
27,LE SSERAFIM,82,k-pop,4SpbR6yFEvexJuaBpgAU5p,6909574,https://i.scdn.co/image/ab6761610000e5eb593f35...
28,THE SIXTH LIE,40,"anime, j-rock, j-pop",2sCc8pMRgv99AweDSrFFZt,30484,https://i.scdn.co/image/ab6761610000e5ebca92c4...
29,結束バンド,63,"anime, j-rock, j-pop",2nvl0N9GwyX69RRBMEZ4OD,604207,https://i.scdn.co/image/ab6761610000e5eb38df32...
30,NAYEON,64,k-pop,1VwDG9aBflQupaFNjUru9A,2888086,https://i.scdn.co/image/ab6761610000e5eb8f7649...
31,アトラスサウンドチーム,70,"japanese vgm, soundtrack",4hFBhdNVZZuVk5FYThUwaN,196211,https://i.scdn.co/image/ab6761610000e5eb5de4fc...
32,LiSA,71,"anime, j-pop, j-rock",0blbVefuxOGltDBa00dspv,3370607,https://i.scdn.co/image/ab6761610000e5eb774ac8...
33,KISS OF LIFE,73,k-pop,4TEK9tIkcoxib4GxT3O4ky,2125187,https://i.scdn.co/image/ab6761610000e5eb33a8cc...
34,Ado,77,"j-pop, anime, vocaloid, j-rock",6mEQK9m2krja6X1cfsAjfl,5850156,https://i.scdn.co/image/ab6761610000e5ebbcb1c1...
35,QWER,53,"k-rock, k-pop",0XufO9nLOKNN0w0qNrDrZy,232390,https://i.scdn.co/image/ab6761610000e5ebdde5e6...
36,TZUYU,52,k-pop,1arCVYXeStgCY2UazBNBLK,308945,https://i.scdn.co/image/ab6761610000e5eb9f631e...
37,Taylor Swift,98,,06HL4z0CvFAxyc27GXpf02,135420613,https://i.scdn.co/image/ab6761610000e5ebe672b5...
38,2NE1,62,k-pop,1l0mKo96Jh9HVYONcRl3Yp,2686506,https://i.scdn.co/image/ab6761610000e5ebcd3114...
39,milet,64,"j-pop, anime, j-rock",45ft4DyTCEJfQwTBHXpdhM,922280,https://i.scdn.co/image/ab6761610000e5ebe56b36...
40,Imagine Dragons,88,,53XhwfbYqKCa1cC15pYq2q,56918534,https://i.scdn.co/image/ab6761610000e5ebab47d8...
41,OFFICIAL HIGE DANDISM,71,"j-pop, anime, j-rock",5Vo1hnCRmCM6M4thZCInCj,7077624,https://i.scdn.co/image/ab6761610000e5ebf9f751...
42,Evan Call,62,anime,0nMGbTpPx4b3h5fMG9CpWJ,66781,https://i.scdn.co/image/ab6761610000e5ebfaf4db...
43,Red Velvet,70,k-pop,1z4g3DjTBBZKhvAroFlhOM,9474555,https://i.scdn.co/image/ab6761610000e5eb02a562...
44,SEULGI,63,k-pop,2QM5S4yO6xHgnNvF0nbZZq,1212544,https://i.scdn.co/image/ab6761610000e5eb9879ac...
45,Mrs. GREEN APPLE,82,"j-pop, anime, j-rock",4QvgGvpgzgyUOo8Yp8LDm9,5360029,https://i.scdn.co/image/ab6761610000e5eb3745f8...
46,JIHYO,54,k-pop,7F1iAHRYxR3MY7yAEuFqgL,979380,https://i.scdn.co/image/ab6761610000e5eb92d8ef...
47,Coldplay,91,,4gzpq5DPGxSnKTe4SA8HAU,57698296,https://i.scdn.co/image/ab6761610000e5eb1ba8fc...
48,LISA,83,k-pop,5L1lO4eRHmJ7a0Q6csE5cT,11384975,https://i.scdn.co/image/ab6761610000e5eb5cd3b3...
49,Against The Current,64,pop punk,6yhD1KjhLxIETFF7vIRf8B,528949,https://i.scdn.co/image/ab6761610000e5eb469aba...

# Extract Album Information

In [10]:
album_ids = short_term_track_data['album_id'].unique().tolist()
get_albums_info(sp,album_ids)

,album_id,album_name,release_date,total_tracks,label,popularity,album_type,external_url,album_uri,release_date_precision,images,genres,artists,track_ids,available_markets
0,4ILxYaUCwfA9EJ36wPwTWz,Air,2025-03-10,4,WM Japan,46,single,https://open.spotify.com/album/4ILxYaUCwfA9EJ3...,spotify:album:4ILxYaUCwfA9EJ36wPwTWz,day,[https://i.scdn.co/image/ab67616d0000b273dfd81...,,YEJI,"[6HSns0qPQQfgekCrBF0Dkf, 5xOUBAvwWYyuPmej4iRcV...",[JP]
1,2dD84O2WUFNCjs963yWsbh,"Webtoon <Myst, Might, Mayhem> OST Part. 2 Draw...",2025-03-21,2,GRAYGAMES,34,single,https://open.spotify.com/album/2dD84O2WUFNCjs9...,spotify:album:2dD84O2WUFNCjs963yWsbh,day,[https://i.scdn.co/image/ab67616d0000b273a17a4...,,MINNIE,"[4B3JCEcAeTofpsfsEianeS, 0tq66QKocw9dXtpN9E3T2O]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
2,1jrJTnOMuLs5v0qTDTc0kR,Radio (Dum-Dum),2025-03-17,1,BMG Rights Management (US) LLC,55,single,https://open.spotify.com/album/1jrJTnOMuLs5v0q...,spotify:album:1jrJTnOMuLs5v0qTDTc0kR,day,[https://i.scdn.co/image/ab67616d0000b2737c841...,,YUQI,[0mXXjVVAhaasNXga2HMgJK],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
3,4e7kLQu7SKBUiMtV5WH3A1,I - The 1st Mini Album,2015-10-07,6,SM Entertainment,53,single,https://open.spotify.com/album/4e7kLQu7SKBUiMt...,spotify:album:4e7kLQu7SKBUiMtV5WH3A1,day,[https://i.scdn.co/image/ab67616d0000b273f531f...,,TAEYEON,"[5ZkITfPpcNPnyYGTibkO6m, 2DlBwbXR5mA8qhTuTMh6e...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
4,29pgfsXVV0cLsvfylWRZJ9,Fourever,2024-03-18,7,Republic Records - DAY6,58,album,https://open.spotify.com/album/29pgfsXVV0cLsvf...,spotify:album:29pgfsXVV0cLsvfylWRZJ9,day,[https://i.scdn.co/image/ab67616d0000b27303099...,,DAY6,"[6je5cTal6PyeITNrOzkCoS, 1k68vKHNQXU5CHqcM7Yp7...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
5,08CvAj58nVMpq1Nw7T6maj,The Winning,2024-02-20,5,EDAM Entertainment,55,single,https://open.spotify.com/album/08CvAj58nVMpq1N...,spotify:album:08CvAj58nVMpq1Nw7T6maj,day,[https://i.scdn.co/image/ab67616d0000b2735048e...,,IU,"[1c6kkrWnpy68eYDfBdxNtF, 0UTtK6hregIBOsefavRI2...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
6,405JFvqLG79ifF84IKlWJC,SMILEY-Japanese Ver.- (feat.ちゃんみな),2023-08-07,2,DREAMUSIC,30,single,https://open.spotify.com/album/405JFvqLG79ifF8...,spotify:album:405JFvqLG79ifF84IKlWJC,day,[https://i.scdn.co/image/ab67616d0000b27393b11...,,YENA,"[4RhkH4fGvvEzxvRlUcYH9L, 5c0IvE05IS3ETib8Uv69mG]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
7,6FLiJ4318RtpA5lYWJt2cL,NEMONEMO,2024-09-30,3,"Genie Music Corporation, Stone Music Entertain...",56,single,https://open.spotify.com/album/6FLiJ4318RtpA5l...,spotify:album:6FLiJ4318RtpA5lYWJt2cL,day,[https://i.scdn.co/image/ab67616d0000b27376bc3...,,YENA,"[4UwsXGVppRRJpKBHy0mtyK, 1T3HuFlijT5Uu4pZI60tg...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
8,7qldKtsOWklzmwgll5NjCw,ˣ‿ˣ (SMiLEY),2022-01-17,5,"Genie Music Corporation, Stone Music Entertain...",50,single,https://open.spotify.com/album/7qldKtsOWklzmwg...,spotify:album:7qldKtsOWklzmwgll5NjCw,day,[https://i.scdn.co/image/ab67616d0000b273a435b...,,YENA,"[2l1igayfoeUbe8xjYTRGqi, 4zCIxSnVWpGNghERX4uWZ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
9,3vk3MR4IL2EMC4ksN5pCo4,Armageddon - The 1st Album,2024-05-27,10,SM Entertainment,59,album,https://open.spotify.com/album/3vk3MR4IL2EMC4k...,spotify:album:3vk3MR4IL2EMC4ksN5pCo4,day,[https://i.scdn.co/image/ab67616d0000b2731a956...,,aespa,"[2VdSktBqFfkW7y6q5Ik4Z4, 5eWcGfUCrVFMoYskyfkEP...",[JP]
10,7JCNpE1d2ivc2YPSqEVShc,DRIP,2024-11-01,9,Sony Music Labels Inc.,64,album,https://open.spotify.com/album/7JCNpE1d2ivc2YP...,spotify:album:7JCNpE1d2ivc2YPSqEVShc,day,[https://i.scdn.co/image/ab67616d0000b273b00f5...,,BABYMONSTER,"[0Rq9lIn9fl4wiW9Tg72ifr, 198zDKzyktXRG1PGpidY9...",[JP]
11,4QvzYMXuU58cNpFrRQ9Aqi,가을 아침 [Gaeul Achim] : Autumn morning,2017-09-22,1,Fave Entertainment,38,single,https://open.spotify.com/album/4QvzYMXuU58cNpF...,spotify:album:4QvzYMXuU58cNpFrRQ9Aqi,day,[https://i.scdn.co/image/ab67616d0000b2731627e...,,IU,[100N8P8WYnz9eCYuLYGflV],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
12,149BHv6qAyMgJ483vPi77C,Last Fantasy,2011-11-29,13,Kakao Entertainment,45,album,https://open.spotify.com/album/149BHv6qAyMgJ48...,spotify:album:149BHv6qAyMgJ483vPi77C,day,[https://i.scdn.co/image/ab67616d0000b273bf5f4...,,IU,"[38HJ2NhRdr68S1UAi9r3vc, 79PkC8ii2W7Grvvkqazgf...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
13,6RRuiUup6Z0Y0MxkCXOGyU,Whiplash - The 5th Mini Album,2024-10-21,6,SM Entertainment,63,single,https://open.spotify.com/album/6RRuiUup6Z0Y0Mx...,spotify:album:6RRuiUup6Z0Y0MxkCXOGyU,day,[https://i.scdn.co/image/ab67616d0000b273f0f92...,,aespa,"[6uPnrBgweGOcwjFL4ItAvV, 7dYEUpcXJLDcI22m0dgmn...",[JP]
14,7a5VJXSKmOJLyWYDKsGubq,HER,2025-01-21,7,CUBE ENTERTAINMENT INC.,35,album,https://open.spotify.com/album/7a5VJXSKmOJLyWY...,spotify:album:7a5VJXSKmOJLyWYDKsGubq,day,[https://i.scdn.co/image/ab67616d0000b2739624f...,,MINNIE,"[4wqyCBpp9zwtpSehLRciXT, 6XtNw289lraKPESASgB5H...",[JP]
15,2CBL0ep4HNPCrCkQGhWJ1M,音楽,2024-02-21,12,Sony Music Labels Inc.,54,album,https://open.spotify.com/album/2CBL0ep4HNPCrCk...,spotify:album:2CBL0ep4HNPCrCkQGhWJ1M,day,[https://i.scdn.co/image/ab67616d0000b27323614...,,SUPER BEAVER,"[7vjOo9fJElFH24nXraNRYK, 79z4gwvetIY6Du3qx9fyP...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
16,2xJZSgxlKvcOCR2aLA8Pq2,Growing Up,2009-04-23,16,Kakao Entertainment,37,album,https://open.spotify.com/album/2xJZSgxlKvcOCR2...,spotify:album:2xJZSgxlKvcOCR2aLA8Pq2,day,[https://i.scdn.co/image/ab67616d0000b273e7a1b...,,IU,"[1dIMDyUh1tC5uuESauhEM6, 6i7mQOXDa23mOJb5TjPqQ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
17,0lbUf1aVf8xmveSuspuNW0,SMARTPHONE,2022-08-03,5,"Genie Music Corporation, Stone Music Entertain...",38,single,https://open.spotify.com/album/0lbUf1aVf8xmveS...,spotify:album:0lbUf1aVf8xmveSuspuNW0,day,[https://i.scdn.co/image/ab67616d0000b273d39be...,,YENA,"[65QbuMLHOGsUTjcMzCoHEE, 3660VWl7PCUsXhZlakn0K...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
18,6yT57VsTlEjkZz6539dA8i,My Stupid Heart (with Lauv),2023-03-03,1,Golden Carrot Records,40,single,https://open.spotify.com/album/6yT57VsTlEjkZz6...,spotify:album:6yT57VsTlEjkZz6539dA8i,day,[https://i.scdn.co/image/ab67616d0000b273c4bc5...,,"Walk off the Earth, Lauv",[1SVOLTmC627fn0XY9ltvx2],"[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
19,0pqrWNxpcWBvR9A5A9JHHl,七号線ロストボーイズ,2022-04-13,11,Sony Music Labels Inc.,41,album,https://open.spotify.com/album/0pqrWNxpcWBvR9A...,spotify:album:0pqrWNxpcWBvR9A5A9JHHl,day,[https://i.scdn.co/image/ab67616d0000b2730262e...,,amazarashi,"[4g5yln7dtUaWz2bhD7s3Lp, 6C7rH9snYqVLTeFkmXv0g...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
20,3aYLtPSWEqmcLTCfM0ZYl7,HATE XX,2023-06-27,3,"Genie Music Corporation, Stone Music Entertain...",47,single,https://open.spotify.com/album/3aYLtPSWEqmcLTC...,spotify:album:3aYLtPSWEqmcLTCfM0ZYl7,day,[https://i.scdn.co/image/ab67616d0000b273afedc...,,YENA,"[4XGOlD2OFGPHXLA0DBPr5M, 5ms7rcVKjBFUtoVh8hE0Y...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
21,47f7hcYu2nGCYcRx5d8zCM,Letter To Myself - The 6th Mini Album,2024-11-18,6,SM Entertainment,58,single,https://open.spotify.com/album/47f7hcYu2nGCYcR...,spotify:album:47f7hcYu2nGCYcRx5d8zCM,day,[https://i.scdn.co/image/ab67616d0000b273fd445...,,TAEYEON,"[1Uxr0oBXAZRuLkAz27TkLc, 1905x5T3TtMOofjc5gokc...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
22,7wDskR5Q6K1qqLPEG8W8kB,REBEL HEART,2025-01-13,1,Sony Music Labels Inc.,55,single,https://open.spotify.com/album/7wDskR5Q6K1qqLP...,spotify:album:7wDskR5Q6K1qqLPEG8W8kB,day,[https://i.scdn.co/image/ab67616d0000b273772a2...,,IVE,[0qdPpfbrgdBs6ie9bTtQ1d],[JP]
23,0wCLHkBRKcndhMQQpeo8Ji,I Don't Wanna Wait,2024-04-05,2,Parlophone UK,73,single,https://open.spotify.com/album/0wCLHkBRKcndhMQ...,spotify:album:0wCLHkBRKcndhMQQpeo8Ji,day,[https://i.scdn.co/image/ab67616d0000b2732f479...,,"David Guetta, OneRepublic","[331l3xABO0HMr1Kkyh2LZq, 5inQmzgChEgxO03LjYloQM]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
24,3zSmrdJtL6jp6H6KKYMu7a,PINK YOUR MOMENT,2023-04-26,1,285,7,single,https://open.spotify.com/album/3zSmrdJtL6jp6H6...,spotify:album:3zSmrdJtL6jp6H6KKYMu7a,day,[https://i.scdn.co/image/ab6742d3000053b7b709c...,,MINNIE,[3CH6RNIVix2lZp9awUfOSQ],"[AD, AE, AM, AR, AT, AU, BA, BE, BG, BO, BR, C..."
25,20Bf2RVERC5Bc2eo3vyvJv,Persona 3 Reload Original Soundtrack,2024-04-24,62,ATLUS GAME MUSIC,71,album,https://open.spotify.com/album/20Bf2RVERC5Bc2e...,spotify:album:20Bf2RVERC5Bc2eo3vyvJv,day,[https://i.scdn.co/image/ab67616d0000b273e59bd...,,"アトラスサウンドチーム, ATLUS GAME MUSIC","[3Jl2LQmRwbXEF2lO1RTvxn, 1d5r3NM4fqH8po53LkMzB...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
26,7nwFxexvXGarWydafSsUrC,"My Dangerous Wife, Pt. 2 (Original Television ...",2020-10-11,2,JTBC 스튜디오 (MBN방송),23,single,https://open.spotify.com/album/7nwFxexvXGarWyd...,spotify:album:7nwFxexvXGarWydafSsUrC,day,[https://i.scdn.co/image/ab67616d0000b27343f00...,,MINNIE,"[41nBWFdECOtxYnygCpL6AH, 2vPRIEyfRmc0L94HhLgpQ4]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
27,3KExM8E3KgpsS2bHVSJzTc,The Golden Age Of Grotesque,2003-01-01,16,Marilyn Manson / Interscope,59,album,https://open.spotify.com/album/3KExM8E3KgpsS2b...,spotify:album:3KExM8E3KgpsS2bHVSJzTc,day,[https://i.scdn.co/image/ab67616d0000b273dcca2...,,Marilyn Manson,"[0HbadG1UeqY6qEGRmRtfLy, 5P13mfqn9o3ToFPTxowEg...","[AR, AU, AT, BE, BO, BR, BG, CL, CO, CR, CY, C..."
28,1ulr9SX47HJ1SNRvGPFOli,bLACKbLUE,2024-10-02,38,Sony Music Labels Inc.,55,album,https://open.spotify.com/album/1ulr9SX47HJ1SNR...,spotify:album:1ulr9SX47HJ1SNRvGPFOli,day,[https://i.scdn.co/image/ab67616d0000b27365873...,,SawanoHiroyuki[nZk],"[5DEDt6ptuhDvjcBVq7vP7g, 1Gfn6OxrQnW3rdUq7H63o...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
29,7JWtvxwYAwzuSDPzvbvXHP,Frozen 2 (Korean Original Motion Picture Sound...,2019-11-15,12,Walt Disney Records,39,compilation,https://open.spotify.com/album/7JWtvxwYAwzuSDP...,spotify:album:7JWtvxwYAwzuSDPzvbvXHP,day,[https://i.scdn.co/image/ab67616d0000b273b9c8e...,,Various Artists,"[0KnKNAX8BIc0II4SR7CuoE, 7KFZhvBjEESN2PRSm9i7B...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
30,7kFyd5oyJdVX2pIi6P4iHE,rosie,2024-12-06,12,Atlantic Records,88,album,https://open.spotify.com/album/7kFyd5oyJdVX2pI...,spotify:album:7kFyd5oyJdVX2pIi6P4iHE,day,[https://i.scdn.co/image/ab67616d0000b2735074b...,,ROSÉ,"[1lcBt7LoEikqYmhUoa2cez, 3y4q6bBdbXsTIaPiwiiUf...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
31,4O6qchYcxBl6LunbOAhwxj,造浪 (《我要逆风去》电视剧主题曲),2024-06-25,2,Sony Music Entertainment,25,single,https://open.spotify.com/album/4O6qchYcxBl6Lun...,spotify:album:4O6qchYcxBl6LunbOAhwxj,day,[https://i.scdn.co/image/ab67616d0000b2734109b...,,YUQI,"[0tNwt2ZBNkelLrLnZqOC2H, 6zZdQgoBxYybNjvtpoqhTK]","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
32,5zseibu9WEsPaZmkJUMkz1,California 37,2012-04-17,11,Columbia,73,album,https://open.spotify.com/album/5zseibu9WEsPaZm...,spotify:album:5zseibu9WEsPaZmkJUMkz1,day,[https://i.scdn.co/image/ab67616d0000b273bde34...,,Train,"[69iQM8CLaJFn8oqEefgPYw, 0KAiuUOrLTIkzkpfpn9jb...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
33,2XpMmJUrM3e5qdCUpJqXA7,GUESS WHO,2021-04-30,6,WM Japan,35,single,https://open.spotify.com/album/2XpMmJUrM3e5qdC...,spotify:album:2XpMmJUrM3e5qdCUpJqXA7,day,[https://i.scdn.co/image/ab67616d0000b273a24cf...,,ITZY,"[1Wcr8zrKqbUX0zwN8Dbr16, 4BV9bZOeH869aewS9lwTt...",[JP]
34,4yHDaLGrPSwUfJNVUIvFgg,Artificial Paradise (Deluxe),2024-07-12,18,Mosley Music/Interscope Records,71,album,https://open.spotify.com/album/4yHDaLGrPSwUfJN...,spotify:album:4yHDaLGrPSwUfJNVUIvFgg,day,[https://i.scdn.co/image/ab67616d0000b273d9b91...,,OneRepublic,"[0Sz9vpLuoVoeSq8sauSGSI, 6eZEuLvZDa5cQy8bX22oZ...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
35,06mXfvDsRZNfnsGZvX2zpb,Music Of The Spheres,2021-10-15,12,Parlophone UK,70,album,https://open.spotify.com/album/06mXfvDsRZNfnsG...,spotify:album:06mXfvDsRZNfnsGZvX2zpb,day,[https://i.scdn.co/image/ab67616d0000b273ec10f...,,Coldplay,"[1a3G9SNslcKsPAOuIikaxd, 65OR4ywy8Cgs3FDHK82Id...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
36,4vLGHlTnlIIxMSfefCY0cU,SYNK : PARALLEL LINE - Special Digital Single,2024-10-09,4,SM Entertainment,71,single,https://open.spotify.com/album/4vLGHlTnlIIxMSf...,spotify:album:4vLGHlTnlIIxMSfefCY0cU,day,[https://i.scdn.co/image/ab67616d0000b27325309...,,aespa,"[5sjnkOfTLCLNfkkchI2re2, 6pIuPm3u7QgUFAX1V0D9w...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
37,1hmW4opQGq4hIYTbEWsyqW,AMORTAGE,2025-02-14,4,Warner Records,77,single,https://open.spotify.com/album/1hmW4opQGq4hIYT...,spotify:album:1hmW4opQGq4hIYTbEWsyqW,day,[https://i.scdn.co/image/ab67616d0000b27355701...,,JISOO,"[10zywlg5b0gQOC3q1A7ADx, 6TPpCbn9z0IY5Te048iy5...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
38,7tbmvcs2vAe7mijL8Pfven,"2025 SMTOWN : THE CULTURE, THE FUTURE",2025-02-14,17,SM Entertainment,60,album,https://open.spotify.com/album/7tbmvcs2vAe7mij...,spotify:album:7tbmvcs2vAe7mijL8Pfven,day,[https://i.scdn.co/image/ab67616d0000b2731de0a...,,SMTOWN,"[1M1fDf9pNSThwDdXByP121, 0AsUylHV1dZdj5N8knxiS...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."
39,1puG16lwC2NGE5nmlj0eab,10/4,2023-10-04,12,Sony Music Labels Inc.,34,album,https://open.spotify.com/album/1puG16lwC2NGE5n...,spotify:album:1puG16lwC2NGE5nmlj0eab,day,[https://i.scdn.co/image/ab67616d0000b27371f37...,,LONGMAN,"[0sLhu5ZxptRywKJm0PbKcM, 4drTmPKAUBmCgDPsRJ9qr...","[AR, AU, AT, BE, BO, BR, BG, CA, CL, CO, CR, C..."

# Extract additional track information

In [11]:
short_term_track_data.columns

Index(['track_name', 'artist_name', 'album_name', 'album_id', 'release_date',
       'popularity', 'duration_ms', 'explicit', 'track_id', 'duration_min'],
      dtype='object')

In [16]:
track_ids = short_term_track_data['track_id'].unique().tolist()
data = get_tracks_info(sp,track_ids)
data

,track_id,track_name,popularity,explicit,artist_id,album_id,preview_url,track_url,track_external_id,is_local
0,2HhIndg75YiKjuUgGiMjSA,Air,55,False,3skli1w2n0nOZ4qkDbvV2m,4ILxYaUCwfA9EJ36wPwTWz,None,https://open.spotify.com/track/2HhIndg75YiKjuU...,US5TA2500003,False
1,4B3JCEcAeTofpsfsEianeS,Draw the Moon (feat. MIYAVI),45,False,2pHkxVNynHBwQHhGaoBIXX,2dD84O2WUFNCjs963yWsbh,None,https://open.spotify.com/track/4B3JCEcAeTofpsf...,KRA382501968,False
2,0mXXjVVAhaasNXga2HMgJK,Radio (Dum-Dum),67,False,22aCD8IrQZjcPgZw728QT6,1jrJTnOMuLs5v0qTDTc0kR,None,https://open.spotify.com/track/0mXXjVVAhaasNXg...,KRA392500001,False
3,5ZkITfPpcNPnyYGTibkO6m,I,61,False,3qNVuliS40BLgXGxhdBdqu,4e7kLQu7SKBUiMtV5WH3A1,None,https://open.spotify.com/track/5ZkITfPpcNPnyYG...,KRA301500490,False
4,3ePablAj7jk2c1j5CKEtAv,Invasion,40,False,3skli1w2n0nOZ4qkDbvV2m,4ILxYaUCwfA9EJ36wPwTWz,None,https://open.spotify.com/track/3ePablAj7jk2c1j...,US5TA2500004,False
5,1k68vKHNQXU5CHqcM7Yp7N,HAPPY,64,False,5TnQc2N1iKlFjYD7CPGvFc,29pgfsXVV0cLsvfylWRZJ9,None,https://open.spotify.com/track/1k68vKHNQXU5CHq...,US5TA2400040,False
6,7EbaA7z7wP3G7xfYZVlVJS,"Can’t Slow Me, No",38,False,3skli1w2n0nOZ4qkDbvV2m,4ILxYaUCwfA9EJ36wPwTWz,None,https://open.spotify.com/track/7EbaA7z7wP3G7xf...,US5TA2500005,False
7,1c6kkrWnpy68eYDfBdxNtF,Shopper,55,False,3HqSLMAZ3g3d5poNaI7GOU,08CvAj58nVMpq1Nw7T6maj,None,https://open.spotify.com/track/1c6kkrWnpy68eYD...,KRA382401058,False
8,4RhkH4fGvvEzxvRlUcYH9L,SMILEY-Japanese Ver.- (feat.ちゃんみな),39,False,49muoiIu4uea4PO8vueUNN,405JFvqLG79ifF84IKlWJC,None,https://open.spotify.com/track/4RhkH4fGvvEzxvR...,JPN902301730,False
9,4UwsXGVppRRJpKBHy0mtyK,NEMONEMO,67,False,49muoiIu4uea4PO8vueUNN,6FLiJ4318RtpA5lYWJt2cL,None,https://open.spotify.com/track/4UwsXGVppRRJpKB...,KRMIM2465530,False
10,5U7emXCoCl8EOEJUVNbguC,Lxxk 2 U,43,False,49muoiIu4uea4PO8vueUNN,7qldKtsOWklzmwgll5NjCw,None,https://open.spotify.com/track/5U7emXCoCl8EOEJ...,KRMIM2201804,False
11,2JhbSmNAyM9kYiqwa8Tpla,Supernova,64,False,6YVMFz59CuY7ngCxTxjpxE,3vk3MR4IL2EMC4ksN5pCo4,None,https://open.spotify.com/track/2JhbSmNAyM9kYiq...,KRA302400092,False
12,7a6vvAM1cjAuyVQpqv9pmu,FOREVER,62,False,1SIocsqdEefUTE6XKGUiVS,7JCNpE1d2ivc2YPSqEVShc,None,https://open.spotify.com/track/7a6vvAM1cjAuyVQ...,KRA402400062,False
13,100N8P8WYnz9eCYuLYGflV,Autumn morning,49,False,3HqSLMAZ3g3d5poNaI7GOU,4QvzYMXuU58cNpFrRQ9Aqi,None,https://open.spotify.com/track/100N8P8WYnz9eCY...,KRA381702215,False
14,38HJ2NhRdr68S1UAi9r3vc,Secret,37,False,3HqSLMAZ3g3d5poNaI7GOU,149BHv6qAyMgJ483vPi77C,None,https://open.spotify.com/track/38HJ2NhRdr68S1U...,KRA381002288,False
15,7Cnpb1vBbC46RgVyyKLH7p,Whiplash,73,False,6YVMFz59CuY7ngCxTxjpxE,6RRuiUup6Z0Y0MxkCXOGyU,None,https://open.spotify.com/track/7Cnpb1vBbC46RgV...,KRA302400341,False
16,1Jm2piFQ1Nq3fGHwu3fyvT,HER,45,False,2pHkxVNynHBwQHhGaoBIXX,7a5VJXSKmOJLyWYDKsGubq,None,https://open.spotify.com/track/1Jm2piFQ1Nq3fGH...,KRA392400036,False
17,4Jp91ygcS0CBz8MwtvoBrU,ひたむき,50,False,0SMhG4gXGD4gzLMMz08cQU,2CBL0ep4HNPCrCkQGhWJ1M,None,https://open.spotify.com/track/4Jp91ygcS0CBz8M...,JPU902202256,False
18,6zpiGeoHYRF5vtrboE3rAC,Well… (ROCK VER.),39,False,3HqSLMAZ3g3d5poNaI7GOU,2xJZSgxlKvcOCR2aLA8Pq2,None,https://open.spotify.com/track/6zpiGeoHYRF5vtr...,KRA380900708,False
19,71lnolmea3IZeG90Gj7jHg,Live My Life,58,False,6YVMFz59CuY7ngCxTxjpxE,3vk3MR4IL2EMC4ksN5pCo4,None,https://open.spotify.com/track/71lnolmea3IZeG9...,KRA302400118,False
20,5tazcUyCvfGdRWC1Da5rCS,WithOrWithOut,34,False,49muoiIu4uea4PO8vueUNN,0lbUf1aVf8xmveSuspuNW0,None,https://open.spotify.com/track/5tazcUyCvfGdRWC...,KRMIM2242963,False
21,6sEqkiXe4vRNIhOvNdZzL1,Obsession (feat. TEN),27,False,2pHkxVNynHBwQHhGaoBIXX,7a5VJXSKmOJLyWYDKsGubq,None,https://open.spotify.com/track/6sEqkiXe4vRNIhO...,KRA392400041,False
22,1SVOLTmC627fn0XY9ltvx2,My Stupid Heart (with Lauv),52,False,6jEiUoyyJNPHzSR0Nib6HX,6yT57VsTlEjkZz6539dA8i,None,https://open.spotify.com/track/1SVOLTmC627fn0X...,QM4TW2393157,False
23,1FXNYp47arDhsngAsHSG9v,BAHAMA,44,False,6YVMFz59CuY7ngCxTxjpxE,3vk3MR4IL2EMC4ksN5pCo4,None,https://open.spotify.com/track/1FXNYp47arDhsng...,KRA302400115,False
24,3jfSorOGnWLPgYqtIuL6OI,境界線,48,False,6T4K8YuFc0JPDrYgABbxao,0pqrWNxpcWBvR9A5A9JHHl,None,https://open.spotify.com/track/3jfSorOGnWLPgYq...,JPU902102765,False
25,5ms7rcVKjBFUtoVh8hE0Y9,Hate Rodrigo (Feat. YUQI),54,False,49muoiIu4uea4PO8vueUNN,3aYLtPSWEqmcLTCfM0ZYl7,None,https://open.spotify.com/track/5ms7rcVKjBFUtoV...,KRMIM2364497,False
26,1Uxr0oBXAZRuLkAz27TkLc,Letter To Myself,63,False,3qNVuliS40BLgXGxhdBdqu,47f7hcYu2nGCYcRx5d8zCM,None,https://open.spotify.com/track/1Uxr0oBXAZRuLkA...,KRA302400436,False
27,1jtlHteF4y7FFHKgYFld4f,REBEL HEART,66,False,6RHTUrRF63xao58xh9FXYJ,7wDskR5Q6K1qqLPEG8W8kB,None,https://open.spotify.com/track/1jtlHteF4y7FFHK...,QMFMF2434277,False
28,331l3xABO0HMr1Kkyh2LZq,I Don't Wanna Wait,85,False,1Cs0zKBU1kc0i8ypK3B9ai,0wCLHkBRKcndhMQQpeo8Ji,None,https://open.spotify.com/track/331l3xABO0HMr1K...,UKWLG2400013,False
29,3CH6RNIVix2lZp9awUfOSQ,PINK YOUR MOMENT,16,False,2pHkxVNynHBwQHhGaoBIXX,3zSmrdJtL6jp6H6KKYMu7a,None,https://open.spotify.com/track/3CH6RNIVix2lZp9...,KRZ212300281,False
30,3Jl2LQmRwbXEF2lO1RTvxn,Full Moon Full Life,65,False,4VeqFgWkP7P9eEGwzPuXcM,20Bf2RVERC5Bc2eo3vyvJv,None,https://open.spotify.com/track/3Jl2LQmRwbXEF2l...,JPK652300101,False
31,41nBWFdECOtxYnygCpL6AH,Getaway,34,False,2pHkxVNynHBwQHhGaoBIXX,7nwFxexvXGarWydafSsUrC,None,https://open.spotify.com/track/41nBWFdECOtxYny...,KRF702000123,False
32,5P13mfqn9o3ToFPTxowEgO,This Is The New Shit,63,True,2VYQTNDsvvKN9wmU5W7xpj,3KExM8E3KgpsS2bHVSJzTc,None,https://open.spotify.com/track/5P13mfqn9o3ToFP...,USIR10300252,False
33,5hakB3OS30xHJsWq6mqty7,LEveL,54,False,2EWXgN0xWOnbqJOxa9pWNO,1ulr9SX47HJ1SNRvGPFOli,None,https://open.spotify.com/track/5hakB3OS30xHJsW...,JPU902301820,False
34,4OkHootAlj7w9Eb2zJVlWr,Into the Unknown (End Credit Version),40,False,3qNVuliS40BLgXGxhdBdqu,7JWtvxwYAwzuSDPzvbvXHP,None,https://open.spotify.com/track/4OkHootAlj7w9Eb...,USWD11995409,False
35,4wJ5Qq0jBN4ajy7ouZIV1c,APT.,92,False,3eVa5w3URK5duf6eyVDbu9,7kFyd5oyJdVX2pIi6P4iHE,None,https://open.spotify.com/track/4wJ5Qq0jBN4ajy7...,USAT22409172,False
36,6jZP2gYURZhXxh45vMAliR,258,41,False,3skli1w2n0nOZ4qkDbvV2m,4ILxYaUCwfA9EJ36wPwTWz,None,https://open.spotify.com/track/6jZP2gYURZhXxh4...,US5TA2500006,False
37,0tNwt2ZBNkelLrLnZqOC2H,造浪 - 《我要逆风去》电视剧主题曲,36,False,22aCD8IrQZjcPgZw728QT6,4O6qchYcxBl6LunbOAhwxj,None,https://open.spotify.com/track/0tNwt2ZBNkelLrL...,CNZ632301361,False
38,1T3HuFlijT5Uu4pZI60tgr,Sugar,49,False,49muoiIu4uea4PO8vueUNN,6FLiJ4318RtpA5lYWJt2cL,None,https://open.spotify.com/track/1T3HuFlijT5Uu4p...,KRMIM2465531,False
39,2NniAhAtkRACaMeYt48xlD,50 Ways to Say Goodbye,70,False,3FUY2gzHeIiaesXtOAdB7A,5zseibu9WEsPaZmkJUMkz1,None,https://open.spotify.com/track/2NniAhAtkRACaMe...,USSM11201533,False
40,4zCIxSnVWpGNghERX4uWZF,SMILEY(Feat. BIBI),60,False,49muoiIu4uea4PO8vueUNN,7qldKtsOWklzmwgll5NjCw,None,https://open.spotify.com/track/4zCIxSnVWpGNghE...,KRMIM2201803,False
41,1muZkKwVHfv8hS77RG2G2I,KIDDING ME,24,False,2KC9Qb60EaY0kW4eH68vr3,2XpMmJUrM3e5qdCUpJqXA7,None,https://open.spotify.com/track/1muZkKwVHfv8hS7...,US5TA2100005,False
42,3SiVMpHxTS1gspWzRZE50S,Nobody - from Kaiju No. 8,63,False,5Pwc4xIPtQLFEnJriah9YJ,4yHDaLGrPSwUfJNVUIvFgg,None,https://open.spotify.com/track/3SiVMpHxTS1gspW...,USUM72403147,False
43,46HNZY1i7O6jwTA7Slo2PI,My Universe,77,False,4gzpq5DPGxSnKTe4SA8HAU,06mXfvDsRZNfnsGZvX2zpb,None,https://open.spotify.com/track/46HNZY1i7O6jwTA...,GBAYE2100952,False
44,5sjnkOfTLCLNfkkchI2re2,UP - KARINA Solo,80,False,6YVMFz59CuY7ngCxTxjpxE,4vLGHlTnlIIxMSfefCY0cU,None,https://open.spotify.com/track/5sjnkOfTLCLNfkk...,KRA302400367,False
45,6TPpCbn9z0IY5Te048iy5R,Your Love,78,False,6UZ0ba50XreR4TM8u322gs,1hmW4opQGq4hIYTbEWsyqW,None,https://open.spotify.com/track/6TPpCbn9z0IY5Te...,USWB12500152,False
46,6lAvyeD3Nq43AjyCxZQj54,Armageddon,61,False,6YVMFz59CuY7ngCxTxjpxE,3vk3MR4IL2EMC4ksN5pCo4,None,https://open.spotify.com/track/6lAvyeD3Nq43Ajy...,KRA302400111,False
47,00M2YcEqhsVbSW6RUKqIY3,Rum Pum Pum Pum,61,False,6YVMFz59CuY7ngCxTxjpxE,7tbmvcs2vAe7mijL8Pfven,None,https://open.spotify.com/track/00M2YcEqhsVbSW6...,KRA302500018,False
48,18Y6TCF80HYi0Fu53xcUge,spiral,45,False,0MBIT0F93uiCv6uLQfH7i7,1puG16lwC2NGE5nmlj0eab,None,https://open.spotify.com/track/18Y6TCF80HYi0Fu...,JPU902302264,False
49,4XGOlD2OFGPHXLA0DBPr5M,BAD HOBBY,41,False,49muoiIu4uea4PO8vueUNN,3aYLtPSWEqmcLTCfM0ZYl7,None,https://open.spotify.com/track/4XGOlD2OFGPHXLA...,KRMIM2364496,False

In [13]:
short_term_track_data

,track_name,artist_name,album_name,album_id,release_date,popularity,duration_ms,explicit,track_id,duration_min
0,Air,YEJI,Air,4ILxYaUCwfA9EJ36wPwTWz,2025-03-10,55,194800,False,2HhIndg75YiKjuUgGiMjSA,3.246667
1,Draw the Moon (feat. MIYAVI),MINNIE,"Webtoon <Myst, Might, Mayhem> OST Part. 2 Draw...",2dD84O2WUFNCjs963yWsbh,2025-03-21,45,210146,False,4B3JCEcAeTofpsfsEianeS,3.502433
2,Radio (Dum-Dum),YUQI,Radio (Dum-Dum),1jrJTnOMuLs5v0qTDTc0kR,2025-03-17,67,152373,False,0mXXjVVAhaasNXga2HMgJK,2.539550
3,I,TAEYEON,I - The 1st Mini Album,4e7kLQu7SKBUiMtV5WH3A1,2015-10-07,61,206038,False,5ZkITfPpcNPnyYGTibkO6m,3.433967
4,Invasion,YEJI,Air,4ILxYaUCwfA9EJ36wPwTWz,2025-03-10,40,167800,False,3ePablAj7jk2c1j5CKEtAv,2.796667
5,HAPPY,DAY6,Fourever,29pgfsXVV0cLsvfylWRZJ9,2024-03-18,64,189934,False,1k68vKHNQXU5CHqcM7Yp7N,3.165567
6,"Can’t Slow Me, No",YEJI,Air,4ILxYaUCwfA9EJ36wPwTWz,2025-03-10,38,178573,False,7EbaA7z7wP3G7xfYZVlVJS,2.976217
7,Shopper,IU,The Winning,08CvAj58nVMpq1Nw7T6maj,2024-02-20,55,215720,False,1c6kkrWnpy68eYDfBdxNtF,3.595333
8,SMILEY-Japanese Ver.- (feat.ちゃんみな),YENA,SMILEY-Japanese Ver.- (feat.ちゃんみな),405JFvqLG79ifF84IKlWJC,2023-08-07,39,176882,False,4RhkH4fGvvEzxvRlUcYH9L,2.948033
9,NEMONEMO,YENA,NEMONEMO,6FLiJ4318RtpA5lYWJt2cL,2024-09-30,67,178026,False,4UwsXGVppRRJpKBHy0mtyK,2.967100
10,Lxxk 2 U,YENA,ˣ‿ˣ (SMiLEY),7qldKtsOWklzmwgll5NjCw,2022-01-17,43,182853,False,5U7emXCoCl8EOEJUVNbguC,3.047550
11,Supernova,aespa,Armageddon - The 1st Album,3vk3MR4IL2EMC4ksN5pCo4,2024-05-27,64,178880,False,2JhbSmNAyM9kYiqwa8Tpla,2.981333
12,FOREVER,BABYMONSTER,DRIP,7JCNpE1d2ivc2YPSqEVShc,2024-11-01,62,212734,False,7a6vvAM1cjAuyVQpqv9pmu,3.545567
13,Autumn morning,IU,가을 아침 [Gaeul Achim] : Autumn morning,4QvzYMXuU58cNpFrRQ9Aqi,2017-09-22,49,218884,False,100N8P8WYnz9eCYuLYGflV,3.648067
14,Secret,IU,Last Fantasy,149BHv6qAyMgJ483vPi77C,2011-11-29,37,246772,False,38HJ2NhRdr68S1UAi9r3vc,4.112867
15,Whiplash,aespa,Whiplash - The 5th Mini Album,6RRuiUup6Z0Y0MxkCXOGyU,2024-10-21,73,183226,False,7Cnpb1vBbC46RgVyyKLH7p,3.053767
16,HER,MINNIE,HER,7a5VJXSKmOJLyWYDKsGubq,2025-01-21,45,159797,False,1Jm2piFQ1Nq3fGHwu3fyvT,2.663283
17,ひたむき,SUPER BEAVER,音楽,2CBL0ep4HNPCrCkQGhWJ1M,2024-02-21,50,246800,False,4Jp91ygcS0CBz8MwtvoBrU,4.113333
18,Well… (ROCK VER.),IU,Growing Up,2xJZSgxlKvcOCR2aLA8Pq2,2009-04-23,39,190589,False,6zpiGeoHYRF5vtrboE3rAC,3.176483
19,Live My Life,aespa,Armageddon - The 1st Album,3vk3MR4IL2EMC4ksN5pCo4,2024-05-27,58,159133,False,71lnolmea3IZeG90Gj7jHg,2.652217
20,WithOrWithOut,YENA,SMARTPHONE,0lbUf1aVf8xmveSuspuNW0,2022-08-03,34,191973,False,5tazcUyCvfGdRWC1Da5rCS,3.199550
21,Obsession (feat. TEN),MINNIE,HER,7a5VJXSKmOJLyWYDKsGubq,2025-01-21,27,222541,False,6sEqkiXe4vRNIhOvNdZzL1,3.709017
22,My Stupid Heart (with Lauv),Walk off the Earth,My Stupid Heart (with Lauv),6yT57VsTlEjkZz6539dA8i,2023-03-03,52,160866,False,1SVOLTmC627fn0XY9ltvx2,2.681100
23,BAHAMA,aespa,Armageddon - The 1st Album,3vk3MR4IL2EMC4ksN5pCo4,2024-05-27,44,190533,False,1FXNYp47arDhsngAsHSG9v,3.175550
24,境界線,amazarashi,七号線ロストボーイズ,0pqrWNxpcWBvR9A5A9JHHl,2022-04-13,48,295893,False,3jfSorOGnWLPgYqtIuL6OI,4.931550
25,Hate Rodrigo (Feat. YUQI),YENA,HATE XX,3aYLtPSWEqmcLTCfM0ZYl7,2023-06-27,54,181013,False,5ms7rcVKjBFUtoVh8hE0Y9,3.016883
26,Letter To Myself,TAEYEON,Letter To Myself - The 6th Mini Album,47f7hcYu2nGCYcRx5d8zCM,2024-11-18,63,184060,False,1Uxr0oBXAZRuLkAz27TkLc,3.067667
27,REBEL HEART,IVE,REBEL HEART,7wDskR5Q6K1qqLPEG8W8kB,2025-01-13,66,188266,False,1jtlHteF4y7FFHKgYFld4f,3.137767
28,I Don't Wanna Wait,David Guetta,I Don't Wanna Wait,0wCLHkBRKcndhMQQpeo8Ji,2024-04-05,85,149667,False,331l3xABO0HMr1Kkyh2LZq,2.494450
29,PINK YOUR MOMENT,MINNIE,PINK YOUR MOMENT,3zSmrdJtL6jp6H6KKYMu7a,2023-04-26,16,131306,False,3CH6RNIVix2lZp9awUfOSQ,2.188433
30,Full Moon Full Life,高橋あず美,Persona 3 Reload Original Soundtrack,20Bf2RVERC5Bc2eo3vyvJv,2024-04-24,65,293493,False,3Jl2LQmRwbXEF2lO1RTvxn,4.891550
31,Getaway,MINNIE,"My Dangerous Wife, Pt. 2 (Original Television ...",7nwFxexvXGarWydafSsUrC,2020-10-11,34,228080,False,41nBWFdECOtxYnygCpL6AH,3.801333
32,This Is The New Shit,Marilyn Manson,The Golden Age Of Grotesque,3KExM8E3KgpsS2bHVSJzTc,2003-01-01,63,259666,True,5P13mfqn9o3ToFPTxowEgO,4.327767
33,LEveL,SawanoHiroyuki[nZk],bLACKbLUE,1ulr9SX47HJ1SNRvGPFOli,2024-10-02,54,182653,False,5hakB3OS30xHJsWq6mqty7,3.044217
34,Into the Unknown (End Credit Version),TAEYEON,Frozen 2 (Korean Original Motion Picture Sound...,7JWtvxwYAwzuSDPzvbvXHP,2019-11-15,40,189120,False,4OkHootAlj7w9Eb2zJVlWr,3.152000
35,APT.,ROSÉ,rosie,7kFyd5oyJdVX2pIi6P4iHE,2024-12-06,92,169917,False,4wJ5Qq0jBN4ajy7ouZIV1c,2.831950
36,258,YEJI,Air,4ILxYaUCwfA9EJ36wPwTWz,2025-03-10,41,193040,False,6jZP2gYURZhXxh45vMAliR,3.217333
37,造浪 - 《我要逆风去》电视剧主题曲,YUQI,造浪 (《我要逆风去》电视剧主题曲),4O6qchYcxBl6LunbOAhwxj,2024-06-25,36,188307,False,0tNwt2ZBNkelLrLnZqOC2H,3.138450
38,Sugar,YENA,NEMONEMO,6FLiJ4318RtpA5lYWJt2cL,2024-09-30,49,166653,False,1T3HuFlijT5Uu4pZI60tgr,2.777550
39,50 Ways to Say Goodbye,Train,California 37,5zseibu9WEsPaZmkJUMkz1,2012-04-17,70,247946,False,2NniAhAtkRACaMeYt48xlD,4.132433
40,SMILEY(Feat. BIBI),YENA,ˣ‿ˣ (SMiLEY),7qldKtsOWklzmwgll5NjCw,2022-01-17,60,173413,False,4zCIxSnVWpGNghERX4uWZF,2.890217
41,KIDDING ME,ITZY,GUESS WHO,2XpMmJUrM3e5qdCUpJqXA7,2021-04-30,24,213960,False,1muZkKwVHfv8hS77RG2G2I,3.566000
42,Nobody - from Kaiju No. 8,OneRepublic,Artificial Paradise (Deluxe),4yHDaLGrPSwUfJNVUIvFgg,2024-07-12,63,153626,False,3SiVMpHxTS1gspWzRZE50S,2.560433
43,My Universe,Coldplay,Music Of The Spheres,06mXfvDsRZNfnsGZvX2zpb,2021-10-15,77,226198,False,46HNZY1i7O6jwTA7Slo2PI,3.769967
44,UP - KARINA Solo,aespa,SYNK : PARALLEL LINE - Special Digital Single,4vLGHlTnlIIxMSfefCY0cU,2024-10-09,80,166640,False,5sjnkOfTLCLNfkkchI2re2,2.777333
45,Your Love,JISOO,AMORTAGE,1hmW4opQGq4hIYTbEWsyqW,2025-02-14,78,173232,False,6TPpCbn9z0IY5Te048iy5R,2.887200
46,Armageddon,aespa,Armageddon - The 1st Album,3vk3MR4IL2EMC4ksN5pCo4,2024-05-27,61,196466,False,6lAvyeD3Nq43AjyCxZQj54,3.274433
47,Rum Pum Pum Pum,aespa,"2025 SMTOWN : THE CULTURE, THE FUTURE",7tbmvcs2vAe7mijL8Pfven,2025-02-14,61,209613,False,00M2YcEqhsVbSW6RUKqIY3,3.493550
48,spiral,LONGMAN,10/4,1puG16lwC2NGE5nmlj0eab,2023-10-04,45,231746,False,18Y6TCF80HYi0Fu53xcUge,3.862433
49,BAD HOBBY,YENA,HATE XX,3aYLtPSWEqmcLTCfM0ZYl7,2023-06-27,41,131013,False,4XGOlD2OFGPHXLA0DBPr5M,2.183550